# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Notification.Declaration do
  @moduledoc """
  Record schema `app.bsky.notification.declaration`.


  ## Fields

  - `allow_subscriptions`: A declaration of the user's preference for allowing activity subscriptions from other users. Absence of a record implies 'followers'.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.notification.declaration"

  @enforce_keys [:allow_subscriptions]
  defstruct allow_subscriptions: nil, extra: %{}

  @type t :: %__MODULE__{allow_subscriptions: String.t()}

  @fields %{allow_subscriptions: "allowSubscriptions"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_allow_subscriptions, e1} =
      Runtime.get_string(attrs, :allow_subscriptions, "allowSubscriptions", required: true)

    errors = e1

    if errors == [] do
      {:ok, %__MODULE__{allow_subscriptions: f_allow_subscriptions, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("allowSubscriptions", struct.allow_subscriptions)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end