# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Calendar.Event do
  @moduledoc """
  Record schema `community.lexicon.calendar.event`.


  ## Fields

  - `created_at`: Client-declared timestamp when the event was created.
  - `description`: The description of the event.
  - `ends_at`: Client-declared timestamp when the event ends.
  - `locations`: The locations where the event takes place.
  - `mode`: ref `community.lexicon.calendar.event#mode`
  - `name`: The name of the event.
  - `rsvp_expected`: Whether a response is requested from attendees.
  - `starts_at`: Client-declared timestamp when the event starts.
  - `status`: ref `community.lexicon.calendar.event#status`
  - `uris`: URIs associated with the event.
  """

  alias Exosphere.Bsky.Runtime

  alias Exosphere.Community.Calendar.Event.Uri
  alias Exosphere.Community.Location.Address
  alias Exosphere.Community.Location.Fsq
  alias Exosphere.Community.Location.Geo
  alias Exosphere.Community.Location.Hthree
  @type_id "community.lexicon.calendar.event"
  @variants_locations [
    {"community.lexicon.calendar.event#uri", Exosphere.Community.Calendar.Event.Uri},
    {"community.lexicon.location.address", Exosphere.Community.Location.Address},
    {"community.lexicon.location.fsq", Exosphere.Community.Location.Fsq},
    {"community.lexicon.location.geo", Exosphere.Community.Location.Geo},
    {"community.lexicon.location.hthree", Exosphere.Community.Location.Hthree}
  ]

  @enforce_keys [:created_at, :name]
  defstruct created_at: nil,
            description: nil,
            ends_at: nil,
            locations: nil,
            mode: nil,
            name: nil,
            rsvp_expected: nil,
            starts_at: nil,
            status: nil,
            uris: nil,
            extra: %{}

  @type t :: %__MODULE__{
          created_at: String.t(),
          description: String.t() | nil,
          ends_at: String.t() | nil,
          locations: [Uri.t() | Address.t() | Fsq.t() | Geo.t() | Hthree.t() | map()] | nil,
          mode: term() | nil,
          name: String.t(),
          rsvp_expected: boolean() | nil,
          starts_at: String.t() | nil,
          status: term() | nil,
          uris: [Uri.t()] | nil
        }

  @fields %{
    created_at: "createdAt",
    description: "description",
    ends_at: "endsAt",
    locations: "locations",
    mode: "mode",
    name: "name",
    rsvp_expected: "rsvpExpected",
    starts_at: "startsAt",
    status: "status",
    uris: "uris"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_description, e2} = Runtime.get_string(attrs, :description, "description", [])
    {f_ends_at, e3} = Runtime.get_string(attrs, :ends_at, "endsAt", format: "datetime")

    {f_locations, e4} =
      Runtime.get_array(attrs, :locations, "locations", [], fn v, path ->
        Runtime.item_union(v, path, @variants_locations)
      end)

    {f_mode, e5} = Runtime.get_any(attrs, :mode, "mode", [])
    {f_name, e6} = Runtime.get_string(attrs, :name, "name", required: true)
    {f_rsvp_expected, e7} = Runtime.get_boolean(attrs, :rsvp_expected, "rsvpExpected", [])
    {f_starts_at, e8} = Runtime.get_string(attrs, :starts_at, "startsAt", format: "datetime")
    {f_status, e9} = Runtime.get_any(attrs, :status, "status", [])

    {f_uris, e10} =
      Runtime.get_array(attrs, :uris, "uris", [], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Community.Calendar.Event.Uri)
      end)

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8 ++ e9 ++ e10

    if errors == [] do
      {:ok,
       %__MODULE__{
         created_at: f_created_at,
         description: f_description,
         ends_at: f_ends_at,
         locations: f_locations,
         mode: f_mode,
         name: f_name,
         rsvp_expected: f_rsvp_expected,
         starts_at: f_starts_at,
         status: f_status,
         uris: f_uris,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field("endsAt", struct.ends_at)
    |> Runtime.put_field("locations", struct.locations, &encode_locations/1)
    |> Runtime.put_field("mode", struct.mode)
    |> Runtime.put_field("name", struct.name)
    |> Runtime.put_field("rsvpExpected", struct.rsvp_expected)
    |> Runtime.put_field("startsAt", struct.starts_at)
    |> Runtime.put_field("status", struct.status)
    |> Runtime.put_field("uris", struct.uris, &encode_uris/1)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_locations(values), do: Enum.map(values, &encode_locations_item/1)

  defp encode_locations_item(v) when is_struct(v, Exosphere.Community.Calendar.Event.Uri),
    do: Map.put(Uri.to_map(v), "$type", "community.lexicon.calendar.event#uri")

  defp encode_locations_item(v) when is_struct(v, Exosphere.Community.Location.Address),
    do: Map.put(Address.to_map(v), "$type", "community.lexicon.location.address")

  defp encode_locations_item(v) when is_struct(v, Exosphere.Community.Location.Fsq),
    do: Map.put(Fsq.to_map(v), "$type", "community.lexicon.location.fsq")

  defp encode_locations_item(v) when is_struct(v, Exosphere.Community.Location.Geo),
    do: Map.put(Geo.to_map(v), "$type", "community.lexicon.location.geo")

  defp encode_locations_item(v) when is_struct(v, Exosphere.Community.Location.Hthree),
    do: Map.put(Hthree.to_map(v), "$type", "community.lexicon.location.hthree")

  defp encode_locations_item(v) when is_map(v), do: v

  defp encode_uris(values), do: Enum.map(values, &encode_uris_item/1)

  defp encode_uris_item(v), do: encode_ref(v, Exosphere.Community.Calendar.Event.Uri)
end
