# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.App.Defs.AccountIndicator do
  @moduledoc """
  A record whose presence in an account can indicate that the account probably uses this app.

  Object schema `community.lexicon.app.defs##accountIndicator`.


  ## Fields

  - `collection`: Record collection to look for in an account repository.
  - `rkey`: Optional record key to look for within the collection.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.app.defs#accountIndicator"

  @enforce_keys [:collection]
  defstruct collection: nil, rkey: nil, extra: %{}

  @type t :: %__MODULE__{collection: String.t(), rkey: String.t() | nil}

  @fields %{collection: "collection", rkey: "rkey"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_collection, e1} =
      Runtime.get_string(attrs, :collection, "collection", required: true, format: "nsid")

    {f_rkey, e2} = Runtime.get_string(attrs, :rkey, "rkey", format: "record-key")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{collection: f_collection, rkey: f_rkey, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("collection", struct.collection)
    |> Runtime.put_field("rkey", struct.rkey)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end