# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.App.Defs.AspectRatio do
  @moduledoc """
  width:height represents an aspect ratio. It may be approximate.

  Object schema `community.lexicon.app.defs##aspectRatio`.


  ## Fields

  - `height`: integer
  - `width`: integer
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.app.defs#aspectRatio"

  @enforce_keys [:height, :width]
  defstruct height: nil, width: nil, extra: %{}

  @type t :: %__MODULE__{height: integer(), width: integer()}

  @fields %{height: "height", width: "width"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_height, e1} = Runtime.get_integer(attrs, :height, "height", required: true, minimum: 1)
    {f_width, e2} = Runtime.get_integer(attrs, :width, "width", required: true, minimum: 1)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{height: f_height, width: f_width, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("height", struct.height)
    |> Runtime.put_field("width", struct.width)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end