# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.App.Defs.Image do
  @moduledoc """
  An image associated with an app, including accessibility and display metadata. Exactly one of `image` (ATProto blob) or `uri` (remote URL) MUST be present. Consumers SHOULD ignore image items that have neither or both.

  Object schema `community.lexicon.app.defs##image`.


  ## Fields

  - `alt`: Alt text description of the image, for accessibility.
  - `aspect_ratio`: ref `#aspectRatio`
  - `image`: The raw image file.
  - `purpose`: How directories and stores should use the image. Omit this field when no known purpose fits.
  - `uri`: Remote image URI.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.app.defs#image"

  @enforce_keys [:alt]
  defstruct alt: nil, aspect_ratio: nil, image: nil, purpose: nil, uri: nil, extra: %{}

  @type t :: %__MODULE__{
          alt: String.t(),
          aspect_ratio: Exosphere.Community.App.Defs.AspectRatio.t() | nil,
          image: term() | nil,
          purpose: String.t() | nil,
          uri: String.t() | nil
        }

  @fields %{
    alt: "alt",
    aspect_ratio: "aspectRatio",
    image: "image",
    purpose: "purpose",
    uri: "uri"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_alt, e1} =
      Runtime.get_string(attrs, :alt, "alt", required: true, max_length: 1000, max_graphemes: 300)

    {f_aspect_ratio, e2} =
      Runtime.get_ref(
        attrs,
        :aspect_ratio,
        "aspectRatio",
        [],
        Exosphere.Community.App.Defs.AspectRatio
      )

    {f_image, e3} = Runtime.get_any(attrs, :image, "image", [])
    {f_purpose, e4} = Runtime.get_string(attrs, :purpose, "purpose", [])
    {f_uri, e5} = Runtime.get_string(attrs, :uri, "uri", format: "uri")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5

    if errors == [] do
      {:ok,
       %__MODULE__{
         alt: f_alt,
         aspect_ratio: f_aspect_ratio,
         image: f_image,
         purpose: f_purpose,
         uri: f_uri,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("alt", struct.alt)
    |> Runtime.put_field("aspectRatio", struct.aspect_ratio, &encode_aspect_ratio/1)
    |> Runtime.put_field("image", struct.image)
    |> Runtime.put_field("purpose", struct.purpose)
    |> Runtime.put_field("uri", struct.uri)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_aspect_ratio(v), do: encode_ref(v, Exosphere.Community.App.Defs.AspectRatio)
end