# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.App.Defs.LexiconInterop do
  @moduledoc """
  Self-declared AT Protocol lexicon interoperability signals.

  Object schema `community.lexicon.app.defs##lexiconInterop`.


  ## Fields

  - `consumes`: Lexicon collections this app reads, displays, imports, or otherwise consumes.
  - `produces`: Lexicon collections this app creates or publishes records for.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.app.defs#lexiconInterop"

  @enforce_keys []
  defstruct consumes: nil, produces: nil, extra: %{}

  @type t :: %__MODULE__{consumes: [String.t()] | nil, produces: [String.t()] | nil}

  @fields %{consumes: "consumes", produces: "produces"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_consumes, e1} =
      Runtime.get_array(attrs, :consumes, "consumes", [], fn v, path ->
        Runtime.item_string(v, path, format: "nsid")
      end)

    {f_produces, e2} =
      Runtime.get_array(attrs, :produces, "produces", [], fn v, path ->
        Runtime.item_string(v, path, format: "nsid")
      end)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{consumes: f_consumes, produces: f_produces, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("consumes", struct.consumes)
    |> Runtime.put_field("produces", struct.produces)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end
