# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Community.App.Defs.Link do
  @moduledoc """
  A labeled URI associated with an app.

  Object schema `community.lexicon.app.defs##link`.


  ## Fields

  - `label`: Human-readable label for the URI.
  - `role`: ref `#linkRole`
  - `uri`: Destination URI.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.app.defs#link"

  @enforce_keys [:uri]
  defstruct label: nil, role: nil, uri: nil, extra: %{}

  @type t :: %__MODULE__{label: String.t() | nil, role: term() | nil, uri: String.t()}

  @fields %{label: "label", role: "role", uri: "uri"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_label, e1} = Runtime.get_string(attrs, :label, "label", max_length: 100, max_graphemes: 50)
    {f_role, e2} = Runtime.get_any(attrs, :role, "role", [])
    {f_uri, e3} = Runtime.get_string(attrs, :uri, "uri", required: true, format: "uri")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %__MODULE__{label: f_label, role: f_role, uri: f_uri, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("label", struct.label)
    |> Runtime.put_field("role", struct.role)
    |> Runtime.put_field("uri", struct.uri)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end