# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Bookmarks.Bookmark do
  @moduledoc """
  Record schema `community.lexicon.bookmarks.bookmark`.


  ## Fields

  - `created_at`: string, format `datetime`
  - `subject`: string, format `uri`
  - `tags`: Tags for content the bookmark may be related to, for example 'news' or 'funny videos'
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.bookmarks.bookmark"

  @enforce_keys [:created_at, :subject]
  defstruct created_at: nil, subject: nil, tags: nil, extra: %{}

  @type t :: %__MODULE__{created_at: String.t(), subject: String.t(), tags: [String.t()] | nil}

  @fields %{created_at: "createdAt", subject: "subject", tags: "tags"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_subject, e2} =
      Runtime.get_string(attrs, :subject, "subject", required: true, format: "uri")

    {f_tags, e3} =
      Runtime.get_array(attrs, :tags, "tags", [], fn v, path ->
        Runtime.item_string(v, path, [])
      end)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %__MODULE__{created_at: f_created_at, subject: f_subject, tags: f_tags, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("subject", struct.subject)
    |> Runtime.put_field("tags", struct.tags)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end
