# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.App.Entry do
  @moduledoc """
  Record schema `community.lexicon.app.entry`.


  ## Fields

  - `account_indicators`: Records whose presence in an account can indicate that the account probably uses this app.
  - `created_at`: Client-declared timestamp when this entry was created.
  - `description`: A short description of what the app does.
  - `images`: Visual assets for directories and stores, such as icons, hero images, screenshots, banners, and social cards.
  - `langs`: Human language of this entry's text. This describes the listing, not the languages supported by the app.
  - `lexicons`: ref `community.lexicon.app.defs#lexiconInterop`
  - `links`: Relevant destinations for the app. The first link should be the primary destination.
  - `name`: The display name of the app.
  - `platforms`: Platforms where this app is available.
  - `profile_did`: DID expected to publish the canonical app profile at community.lexicon.app.profile/self.
  - `status`: ref `community.lexicon.app.defs#status`
  - `tags`: Open discovery tags for filtering and search, preferably lowercase. Do not use tags for platforms, lexicon interoperability, or listing language.
  - `updated_at`: Client-declared timestamp when this entry was last updated.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.app.entry"

  @enforce_keys [:created_at, :links, :name]
  defstruct account_indicators: nil,
            created_at: nil,
            description: nil,
            images: nil,
            langs: nil,
            lexicons: nil,
            links: nil,
            name: nil,
            platforms: nil,
            profile_did: nil,
            status: nil,
            tags: nil,
            updated_at: nil,
            extra: %{}

  @type t :: %__MODULE__{
          account_indicators: [Exosphere.Community.App.Defs.AccountIndicator.t()] | nil,
          created_at: String.t(),
          description: String.t() | nil,
          images: [Exosphere.Community.App.Defs.Image.t()] | nil,
          langs: [String.t()] | nil,
          lexicons: Exosphere.Community.App.Defs.LexiconInterop.t() | nil,
          links: [Exosphere.Community.App.Defs.Link.t()],
          name: String.t(),
          platforms: [term()] | nil,
          profile_did: String.t() | nil,
          status: term() | nil,
          tags: [String.t()] | nil,
          updated_at: String.t() | nil
        }

  @fields %{
    account_indicators: "accountIndicators",
    created_at: "createdAt",
    description: "description",
    images: "images",
    langs: "langs",
    lexicons: "lexicons",
    links: "links",
    name: "name",
    platforms: "platforms",
    profile_did: "profileDid",
    status: "status",
    tags: "tags",
    updated_at: "updatedAt"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_account_indicators, e1} =
      Runtime.get_array(attrs, :account_indicators, "accountIndicators", [max_length: 12], fn v,
                                                                                              path ->
        Runtime.item_ref(v, path, Exosphere.Community.App.Defs.AccountIndicator)
      end)

    {f_created_at, e2} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_description, e3} =
      Runtime.get_string(attrs, :description, "description", max_length: 3000, max_graphemes: 300)

    {f_images, e4} =
      Runtime.get_array(attrs, :images, "images", [max_length: 24], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Community.App.Defs.Image)
      end)

    {f_langs, e5} =
      Runtime.get_array(attrs, :langs, "langs", [max_length: 3], fn v, path ->
        Runtime.item_string(v, path, format: "language")
      end)

    {f_lexicons, e6} =
      Runtime.get_ref(
        attrs,
        :lexicons,
        "lexicons",
        [],
        Exosphere.Community.App.Defs.LexiconInterop
      )

    {f_links, e7} =
      Runtime.get_array(
        attrs,
        :links,
        "links",
        [required: true, min_length: 1, max_length: 12],
        fn v, path -> Runtime.item_ref(v, path, Exosphere.Community.App.Defs.Link) end
      )

    {f_name, e8} =
      Runtime.get_string(attrs, :name, "name",
        required: true,
        max_length: 200,
        max_graphemes: 100
      )

    {f_platforms, e9} =
      Runtime.get_array(attrs, :platforms, "platforms", [max_length: 12], fn v, _path ->
        {:ok, v}
      end)

    {f_profile_did, e10} = Runtime.get_string(attrs, :profile_did, "profileDid", format: "did")
    {f_status, e11} = Runtime.get_any(attrs, :status, "status", [])

    {f_tags, e12} =
      Runtime.get_array(attrs, :tags, "tags", [max_length: 10], fn v, path ->
        Runtime.item_string(v, path, max_length: 64, max_graphemes: 32)
      end)

    {f_updated_at, e13} = Runtime.get_string(attrs, :updated_at, "updatedAt", format: "datetime")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8 ++ e9 ++ e10 ++ e11 ++ e12 ++ e13

    if errors == [] do
      {:ok,
       %__MODULE__{
         account_indicators: f_account_indicators,
         created_at: f_created_at,
         description: f_description,
         images: f_images,
         langs: f_langs,
         lexicons: f_lexicons,
         links: f_links,
         name: f_name,
         platforms: f_platforms,
         profile_did: f_profile_did,
         status: f_status,
         tags: f_tags,
         updated_at: f_updated_at,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field(
      "accountIndicators",
      struct.account_indicators,
      &encode_account_indicators/1
    )
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field("images", struct.images, &encode_images/1)
    |> Runtime.put_field("langs", struct.langs)
    |> Runtime.put_field("lexicons", struct.lexicons, &encode_lexicons/1)
    |> Runtime.put_field("links", struct.links, &encode_links/1)
    |> Runtime.put_field("name", struct.name)
    |> Runtime.put_field("platforms", struct.platforms)
    |> Runtime.put_field("profileDid", struct.profile_did)
    |> Runtime.put_field("status", struct.status)
    |> Runtime.put_field("tags", struct.tags)
    |> Runtime.put_field("updatedAt", struct.updated_at)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_account_indicators(values), do: Enum.map(values, &encode_account_indicators_item/1)

  defp encode_account_indicators_item(v),
    do: encode_ref(v, Exosphere.Community.App.Defs.AccountIndicator)

  defp encode_images(values), do: Enum.map(values, &encode_images_item/1)

  defp encode_images_item(v), do: encode_ref(v, Exosphere.Community.App.Defs.Image)

  defp encode_lexicons(v), do: encode_ref(v, Exosphere.Community.App.Defs.LexiconInterop)

  defp encode_links(values), do: Enum.map(values, &encode_links_item/1)

  defp encode_links_item(v), do: encode_ref(v, Exosphere.Community.App.Defs.Link)
end