# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.App.ProfileLocalization do
  @moduledoc """
  Localized metadata for a community.lexicon.app.profile record.

  Record schema `community.lexicon.app.profileLocalization`.


  ## Fields

  - `created_at`: Client-declared timestamp when this localization was created.
  - `description`: Localized description of what the app does.
  - `images`: Localized visual assets for directories and stores, such as icons, hero images, screenshots, banners, and social cards.
  - `links`: Localized destinations for the app. The first link should be the primary destination for this locale.
  - `locale`: BCP 47 language tag for this localized metadata.
  - `name`: Localized display name of the app.
  - `tags`: Localized discovery tags for filtering and search.
  - `updated_at`: Client-declared timestamp when this localization was last updated.
  """

  alias Exosphere.Bsky.Runtime

  alias Exosphere.Community.App.Defs.Image
  alias Exosphere.Community.App.Defs.Link
  @type_id "community.lexicon.app.profileLocalization"

  @enforce_keys [:created_at, :locale]
  defstruct created_at: nil,
            description: nil,
            images: nil,
            links: nil,
            locale: nil,
            name: nil,
            tags: nil,
            updated_at: nil,
            extra: %{}

  @type t :: %__MODULE__{
          created_at: String.t(),
          description: String.t() | nil,
          images: [Image.t()] | nil,
          links: [Link.t()] | nil,
          locale: String.t(),
          name: String.t() | nil,
          tags: [String.t()] | nil,
          updated_at: String.t() | nil
        }

  @fields %{
    created_at: "createdAt",
    description: "description",
    images: "images",
    links: "links",
    locale: "locale",
    name: "name",
    tags: "tags",
    updated_at: "updatedAt"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_description, e2} =
      Runtime.get_string(attrs, :description, "description", max_length: 3000, max_graphemes: 300)

    {f_images, e3} =
      Runtime.get_array(attrs, :images, "images", [max_length: 24], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Community.App.Defs.Image)
      end)

    {f_links, e4} =
      Runtime.get_array(attrs, :links, "links", [min_length: 1, max_length: 12], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Community.App.Defs.Link)
      end)

    {f_locale, e5} =
      Runtime.get_string(attrs, :locale, "locale", required: true, format: "language")

    {f_name, e6} = Runtime.get_string(attrs, :name, "name", max_length: 200, max_graphemes: 100)

    {f_tags, e7} =
      Runtime.get_array(attrs, :tags, "tags", [max_length: 10], fn v, path ->
        Runtime.item_string(v, path, max_length: 64, max_graphemes: 32)
      end)

    {f_updated_at, e8} = Runtime.get_string(attrs, :updated_at, "updatedAt", format: "datetime")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8

    if errors == [] do
      {:ok,
       %__MODULE__{
         created_at: f_created_at,
         description: f_description,
         images: f_images,
         links: f_links,
         locale: f_locale,
         name: f_name,
         tags: f_tags,
         updated_at: f_updated_at,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field("images", struct.images, &encode_images/1)
    |> Runtime.put_field("links", struct.links, &encode_links/1)
    |> Runtime.put_field("locale", struct.locale)
    |> Runtime.put_field("name", struct.name)
    |> Runtime.put_field("tags", struct.tags)
    |> Runtime.put_field("updatedAt", struct.updated_at)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_images(values), do: Enum.map(values, &encode_images_item/1)

  defp encode_images_item(v), do: encode_ref(v, Exosphere.Community.App.Defs.Image)

  defp encode_links(values), do: Enum.map(values, &encode_links_item/1)

  defp encode_links_item(v), do: encode_ref(v, Exosphere.Community.App.Defs.Link)
end
