# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Payments.WebMonetization do
  @moduledoc """
  Web Monetization integration: https://webmonetization.org/

  Record schema `community.lexicon.payments.webMonetization`.


  ## Fields

  - `address`: Wallet address.
  - `note`: Short, human-readable description of how this wallet is related to this account.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.payments.webMonetization"

  @enforce_keys [:address]
  defstruct address: nil, note: nil, extra: %{}

  @type t :: %__MODULE__{address: String.t(), note: String.t() | nil}

  @fields %{address: "address", note: "note"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_address, e1} =
      Runtime.get_string(attrs, :address, "address", required: true, format: "uri")

    {f_note, e2} = Runtime.get_string(attrs, :note, "note", [])

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{address: f_address, note: f_note, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("address", struct.address)
    |> Runtime.put_field("note", struct.note)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end