# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Bookmarks do
  @moduledoc """
  XRPC client functions for the `community.lexicon.bookmarks` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `get_actor_bookmarks` — query: community.lexicon.bookmarks.getActorBookmarks
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @fields_get_actor_bookmarks %{cursor: "cursor", limit: "limit", tags: "tags"}

  @doc """
    Get a list of bookmarks by actor. Optionally add a list of tags to include, default will be all bookmarks. Requires auth, actor must be the requesting account.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `tags` (array, optional)

  """
  @spec get_actor_bookmarks(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_actor_bookmarks(client, params \\ []) do
    with {:ok, validated} <- validate_get_actor_bookmarks(params) do
      client
      |> Client.query(
        "community.lexicon.bookmarks.getActorBookmarks",
        Runtime.encode_query_params(validated, @fields_get_actor_bookmarks)
      )
    end
  end

  defp validate_get_actor_bookmarks(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_actor_bookmarks)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_tags, e3} =
      Runtime.get_array(attrs, :tags, "tags", [], fn v, path ->
        Runtime.item_string(v, path, [])
      end)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, tags: f_tags}}
    else
      {:error, errors}
    end
  end
end
