# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Preference.Ai do
  @moduledoc """
  Declares a user's preferences regarding AI usage of their public data. A record at key 'self' with globalScope establishes default preferences. Additional records keyed by TID establish scoped overrides for specific entities or content collections.

  Record schema `community.lexicon.preference.ai`.


  ## Fields

  - `preferences`: ref `#preferenceSet`
  - `scope`: What this record's preferences apply to.
  - `updated_at`: Timestamp of the most recent change to this record.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.preference.ai"
  @variants_scope [
    {"community.lexicon.preference.ai#globalScope",
     Exosphere.Community.Preference.Ai.GlobalScope},
    {"community.lexicon.preference.ai#entityScope",
     Exosphere.Community.Preference.Ai.EntityScope},
    {"community.lexicon.preference.ai#collectionScope",
     Exosphere.Community.Preference.Ai.CollectionScope}
  ]

  @enforce_keys [:preferences, :scope, :updated_at]
  defstruct preferences: nil, scope: nil, updated_at: nil, extra: %{}

  @type t :: %__MODULE__{
          preferences: Exosphere.Community.Preference.Ai.PreferenceSet.t(),
          scope:
            Exosphere.Community.Preference.Ai.GlobalScope.t()
            | Exosphere.Community.Preference.Ai.EntityScope.t()
            | Exosphere.Community.Preference.Ai.CollectionScope.t()
            | map(),
          updated_at: String.t()
        }

  @fields %{preferences: "preferences", scope: "scope", updated_at: "updatedAt"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_preferences, e1} =
      Runtime.get_ref(
        attrs,
        :preferences,
        "preferences",
        [required: true],
        Exosphere.Community.Preference.Ai.PreferenceSet
      )

    {f_scope, e2} = Runtime.get_union(attrs, :scope, "scope", [required: true], @variants_scope)

    {f_updated_at, e3} =
      Runtime.get_string(attrs, :updated_at, "updatedAt", required: true, format: "datetime")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok,
       %__MODULE__{
         preferences: f_preferences,
         scope: f_scope,
         updated_at: f_updated_at,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("preferences", struct.preferences, &encode_preferences/1)
    |> Runtime.put_field("scope", struct.scope, &encode_scope/1)
    |> Runtime.put_field("updatedAt", struct.updated_at)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_preferences(v), do: encode_ref(v, Exosphere.Community.Preference.Ai.PreferenceSet)

  defp encode_scope(v) when is_struct(v, Exosphere.Community.Preference.Ai.GlobalScope),
    do:
      Map.put(
        Exosphere.Community.Preference.Ai.GlobalScope.to_map(v),
        "$type",
        "community.lexicon.preference.ai#globalScope"
      )

  defp encode_scope(v) when is_struct(v, Exosphere.Community.Preference.Ai.EntityScope),
    do:
      Map.put(
        Exosphere.Community.Preference.Ai.EntityScope.to_map(v),
        "$type",
        "community.lexicon.preference.ai#entityScope"
      )

  defp encode_scope(v) when is_struct(v, Exosphere.Community.Preference.Ai.CollectionScope),
    do:
      Map.put(
        Exosphere.Community.Preference.Ai.CollectionScope.to_map(v),
        "$type",
        "community.lexicon.preference.ai#collectionScope"
      )

  defp encode_scope(v) when is_map(v), do: v
end