# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.ATProto.Repo.StrongRef do
  @moduledoc """
  A URI with a content-hash fingerprint.

  Object schema `com.atproto.repo.strongRef`.


  ## Fields

  - `cid`: string, format `cid`
  - `uri`: string, format `at-uri`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "com.atproto.repo.strongRef"

  @enforce_keys [:cid, :uri]
  defstruct cid: nil, uri: nil, extra: %{}

  @type t :: %__MODULE__{cid: String.t(), uri: String.t()}

  @fields %{cid: "cid", uri: "uri"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_cid, e1} = Runtime.get_string(attrs, :cid, "cid", required: true, format: "cid")
    {f_uri, e2} = Runtime.get_string(attrs, :uri, "uri", required: true, format: "at-uri")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{cid: f_cid, uri: f_uri, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("cid", struct.cid)
    |> Runtime.put_field("uri", struct.uri)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end