# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Embed.External do
  @moduledoc """
  A representation of some externally linked content (eg, a URL and 'card'), embedded in a Bluesky record (eg, a post).

  Object schema `app.bsky.embed.external`.


  ## Fields

  - `external`: ref `#external`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.embed.external"

  @enforce_keys [:external]
  defstruct external: nil, extra: %{}

  @type t :: %__MODULE__{external: Exosphere.Bsky.Embed.External.External.t()}

  @fields %{external: "external"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_external, e1} =
      Runtime.get_ref(
        attrs,
        :external,
        "external",
        [required: true],
        Exosphere.Bsky.Embed.External.External
      )

    errors = e1

    if errors == [] do
      {:ok, %__MODULE__{external: f_external, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("external", struct.external, &encode_external/1)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_external(v), do: encode_ref(v, Exosphere.Bsky.Embed.External.External)
end
