# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Embed.Gallery do
  @moduledoc """
  An assortment of media embedded in a Bluesky record (eg, a post).

  Object schema `app.bsky.embed.gallery`.


  ## Fields

  - `items`: The schema-level maxLength of 20 is a future-proof ceiling. Clients should currently enforce a soft limit of 10 items in authoring UIs.
  """

  alias Exosphere.Bsky.Runtime

  alias Exosphere.Bsky.Embed.Gallery.Image
  @type_id "app.bsky.embed.gallery"
  @variants_items [{"app.bsky.embed.gallery#image", Exosphere.Bsky.Embed.Gallery.Image}]

  @enforce_keys [:items]
  defstruct items: nil, extra: %{}

  @type t :: %__MODULE__{items: [Image.t() | map()]}

  @fields %{items: "items"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_items, e1} =
      Runtime.get_array(attrs, :items, "items", [required: true, max_length: 20], fn v, path ->
        Runtime.item_union(v, path, @variants_items)
      end)

    errors = e1

    if errors == [] do
      {:ok, %__MODULE__{items: f_items, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("items", struct.items, &encode_items/1)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_items(values), do: Enum.map(values, &encode_items_item/1)

  defp encode_items_item(v) when is_struct(v, Exosphere.Bsky.Embed.Gallery.Image),
    do: Map.put(Image.to_map(v), "$type", "app.bsky.embed.gallery#image")

  defp encode_items_item(v) when is_map(v), do: v
end
