# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Embed.Images do
  @moduledoc """
  A set of images embedded in a Bluesky record (eg, a post).

  Object schema `app.bsky.embed.images`.


  ## Fields

  - `images`: array
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.embed.images"

  @enforce_keys [:images]
  defstruct images: nil, extra: %{}

  @type t :: %__MODULE__{images: [Exosphere.Bsky.Embed.Images.Image.t()]}

  @fields %{images: "images"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_images, e1} =
      Runtime.get_array(attrs, :images, "images", [required: true, max_length: 4], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Embed.Images.Image)
      end)

    errors = e1

    if errors == [] do
      {:ok, %__MODULE__{images: f_images, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("images", struct.images, &encode_images/1)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_images(values), do: Enum.map(values, &encode_images_item/1)

  defp encode_images_item(v), do: encode_ref(v, Exosphere.Bsky.Embed.Images.Image)
end