# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Embed.Video do
  @moduledoc """
  A video embedded in a Bluesky record (eg, a post).

  Object schema `app.bsky.embed.video`.


  ## Fields

  - `alt`: Alt text description of the video, for accessibility.
  - `aspect_ratio`: ref `app.bsky.embed.defs#aspectRatio`
  - `captions`: array
  - `presentation`: A hint to the client about how to present the video.
  - `video`: The mp4 video file. May be up to 300mb, formerly limited to 100mb.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.embed.video"

  @enforce_keys [:video]
  defstruct alt: nil, aspect_ratio: nil, captions: nil, presentation: nil, video: nil, extra: %{}

  @type t :: %__MODULE__{
          alt: String.t() | nil,
          aspect_ratio: Exosphere.Bsky.Embed.Defs.AspectRatio.t() | nil,
          captions: [Exosphere.Bsky.Embed.Video.Caption.t()] | nil,
          presentation: String.t() | nil,
          video: term()
        }

  @fields %{
    alt: "alt",
    aspect_ratio: "aspectRatio",
    captions: "captions",
    presentation: "presentation",
    video: "video"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_alt, e1} = Runtime.get_string(attrs, :alt, "alt", [])

    {f_aspect_ratio, e2} =
      Runtime.get_ref(
        attrs,
        :aspect_ratio,
        "aspectRatio",
        [],
        Exosphere.Bsky.Embed.Defs.AspectRatio
      )

    {f_captions, e3} =
      Runtime.get_array(attrs, :captions, "captions", [max_length: 20], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Embed.Video.Caption)
      end)

    {f_presentation, e4} = Runtime.get_string(attrs, :presentation, "presentation", [])
    {f_video, e5} = Runtime.get_any(attrs, :video, "video", required: true)

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5

    if errors == [] do
      {:ok,
       %__MODULE__{
         alt: f_alt,
         aspect_ratio: f_aspect_ratio,
         captions: f_captions,
         presentation: f_presentation,
         video: f_video,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("alt", struct.alt)
    |> Runtime.put_field("aspectRatio", struct.aspect_ratio, &encode_aspect_ratio/1)
    |> Runtime.put_field("captions", struct.captions, &encode_captions/1)
    |> Runtime.put_field("presentation", struct.presentation)
    |> Runtime.put_field("video", struct.video)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_aspect_ratio(v), do: encode_ref(v, Exosphere.Bsky.Embed.Defs.AspectRatio)

  defp encode_captions(values), do: Enum.map(values, &encode_captions_item/1)

  defp encode_captions_item(v), do: encode_ref(v, Exosphere.Bsky.Embed.Video.Caption)
end