# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Feed.Generator do
  @moduledoc """
  Record schema `app.bsky.feed.generator`.


  ## Fields

  - `accepts_interactions`: Declaration that a feed accepts feedback interactions from a client through app.bsky.feed.sendInteractions
  - `avatar`: blob
  - `content_mode`: string
  - `created_at`: string, format `datetime`
  - `description`: string
  - `description_facets`: array
  - `did`: string, format `did`
  - `display_name`: string
  - `labels`: Self-label values
  """

  alias Exosphere.Bsky.Runtime

  alias Exosphere.ATProto.Label.Defs.SelfLabels
  alias Exosphere.Bsky.Richtext.Facet
  @type_id "app.bsky.feed.generator"
  @variants_labels [
    {"com.atproto.label.defs#selfLabels", Exosphere.ATProto.Label.Defs.SelfLabels}
  ]

  @enforce_keys [:created_at, :did, :display_name]
  defstruct accepts_interactions: nil,
            avatar: nil,
            content_mode: nil,
            created_at: nil,
            description: nil,
            description_facets: nil,
            did: nil,
            display_name: nil,
            labels: nil,
            extra: %{}

  @type t :: %__MODULE__{
          accepts_interactions: boolean() | nil,
          avatar: term() | nil,
          content_mode: String.t() | nil,
          created_at: String.t(),
          description: String.t() | nil,
          description_facets: [Facet.t()] | nil,
          did: String.t(),
          display_name: String.t(),
          labels: SelfLabels.t() | map() | nil
        }

  @fields %{
    accepts_interactions: "acceptsInteractions",
    avatar: "avatar",
    content_mode: "contentMode",
    created_at: "createdAt",
    description: "description",
    description_facets: "descriptionFacets",
    did: "did",
    display_name: "displayName",
    labels: "labels"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_accepts_interactions, e1} =
      Runtime.get_boolean(attrs, :accepts_interactions, "acceptsInteractions", [])

    {f_avatar, e2} = Runtime.get_any(attrs, :avatar, "avatar", [])
    {f_content_mode, e3} = Runtime.get_string(attrs, :content_mode, "contentMode", [])

    {f_created_at, e4} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_description, e5} =
      Runtime.get_string(attrs, :description, "description", max_length: 3000, max_graphemes: 300)

    {f_description_facets, e6} =
      Runtime.get_array(attrs, :description_facets, "descriptionFacets", [], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Richtext.Facet)
      end)

    {f_did, e7} = Runtime.get_string(attrs, :did, "did", required: true, format: "did")

    {f_display_name, e8} =
      Runtime.get_string(attrs, :display_name, "displayName",
        required: true,
        max_length: 240,
        max_graphemes: 24
      )

    {f_labels, e9} = Runtime.get_union(attrs, :labels, "labels", [], @variants_labels)

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8 ++ e9

    if errors == [] do
      {:ok,
       %__MODULE__{
         accepts_interactions: f_accepts_interactions,
         avatar: f_avatar,
         content_mode: f_content_mode,
         created_at: f_created_at,
         description: f_description,
         description_facets: f_description_facets,
         did: f_did,
         display_name: f_display_name,
         labels: f_labels,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("acceptsInteractions", struct.accepts_interactions)
    |> Runtime.put_field("avatar", struct.avatar)
    |> Runtime.put_field("contentMode", struct.content_mode)
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field(
      "descriptionFacets",
      struct.description_facets,
      &encode_description_facets/1
    )
    |> Runtime.put_field("did", struct.did)
    |> Runtime.put_field("displayName", struct.display_name)
    |> Runtime.put_field("labels", struct.labels, &encode_labels/1)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_description_facets(values), do: Enum.map(values, &encode_description_facets_item/1)

  defp encode_description_facets_item(v), do: encode_ref(v, Exosphere.Bsky.Richtext.Facet)

  defp encode_labels(v) when is_struct(v, Exosphere.ATProto.Label.Defs.SelfLabels),
    do: Map.put(SelfLabels.to_map(v), "$type", "com.atproto.label.defs#selfLabels")

  defp encode_labels(v) when is_map(v), do: v
end
