# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Feed.Postgate do
  @moduledoc """
  Record schema `app.bsky.feed.postgate`.


  ## Fields

  - `created_at`: string, format `datetime`
  - `detached_embedding_uris`: List of AT-URIs embedding this post that the author has detached from.
  - `embedding_rules`: List of rules defining who can embed this post. If value is an empty array or is undefined, no particular rules apply and anyone can embed.
  - `post`: Reference (AT-URI) to the post record.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.feed.postgate"
  @variants_embedding_rules [
    {"app.bsky.feed.postgate#disableRule", Exosphere.Bsky.Feed.Postgate.DisableRule}
  ]

  @enforce_keys [:created_at, :post]
  defstruct created_at: nil,
            detached_embedding_uris: nil,
            embedding_rules: nil,
            post: nil,
            extra: %{}

  @type t :: %__MODULE__{
          created_at: String.t(),
          detached_embedding_uris: [String.t()] | nil,
          embedding_rules: [Exosphere.Bsky.Feed.Postgate.DisableRule.t() | map()] | nil,
          post: String.t()
        }

  @fields %{
    created_at: "createdAt",
    detached_embedding_uris: "detachedEmbeddingUris",
    embedding_rules: "embeddingRules",
    post: "post"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_detached_embedding_uris, e2} =
      Runtime.get_array(
        attrs,
        :detached_embedding_uris,
        "detachedEmbeddingUris",
        [max_length: 50],
        fn v, path -> Runtime.item_string(v, path, format: "at-uri") end
      )

    {f_embedding_rules, e3} =
      Runtime.get_array(attrs, :embedding_rules, "embeddingRules", [max_length: 5], fn v, path ->
        Runtime.item_union(v, path, @variants_embedding_rules)
      end)

    {f_post, e4} = Runtime.get_string(attrs, :post, "post", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok,
       %__MODULE__{
         created_at: f_created_at,
         detached_embedding_uris: f_detached_embedding_uris,
         embedding_rules: f_embedding_rules,
         post: f_post,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("detachedEmbeddingUris", struct.detached_embedding_uris)
    |> Runtime.put_field("embeddingRules", struct.embedding_rules, &encode_embedding_rules/1)
    |> Runtime.put_field("post", struct.post)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_embedding_rules(values), do: Enum.map(values, &encode_embedding_rules_item/1)

  defp encode_embedding_rules_item(v) when is_struct(v, Exosphere.Bsky.Feed.Postgate.DisableRule),
    do:
      Map.put(
        Exosphere.Bsky.Feed.Postgate.DisableRule.to_map(v),
        "$type",
        "app.bsky.feed.postgate#disableRule"
      )

  defp encode_embedding_rules_item(v) when is_map(v), do: v
end