# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Feed.Post do
  @moduledoc """
  Record schema `app.bsky.feed.post`.


  ## Fields

  - `created_at`: Client-declared timestamp when this post was originally created.
  - `embed`: union
  - `entities`: DEPRECATED: replaced by app.bsky.richtext.facet.
  - `facets`: Annotations of text (mentions, URLs, hashtags, etc)
  - `labels`: Self-label values for this post. Effectively content warnings.
  - `langs`: Indicates human language of post primary text content.
  - `reply`: ref `#replyRef`
  - `tags`: Additional hashtags, in addition to any included in post text and facets.
  - `text`: The primary post content. May be an empty string, if there are embeds.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.feed.post"
  @variants_embed [
    {"app.bsky.embed.images", Exosphere.Bsky.Embed.Images},
    {"app.bsky.embed.video", Exosphere.Bsky.Embed.Video},
    {"app.bsky.embed.gallery", Exosphere.Bsky.Embed.Gallery},
    {"app.bsky.embed.external", Exosphere.Bsky.Embed.External},
    {"app.bsky.embed.record", Exosphere.Bsky.Embed.Record},
    {"app.bsky.embed.recordWithMedia", Exosphere.Bsky.Embed.RecordWithMedia}
  ]
  @variants_labels [
    {"com.atproto.label.defs#selfLabels", Exosphere.ATProto.Label.Defs.SelfLabels}
  ]

  @enforce_keys [:created_at, :text]
  defstruct created_at: nil,
            embed: nil,
            entities: nil,
            facets: nil,
            labels: nil,
            langs: nil,
            reply: nil,
            tags: nil,
            text: nil,
            extra: %{}

  @type t :: %__MODULE__{
          created_at: String.t(),
          embed:
            Exosphere.Bsky.Embed.Images.t()
            | Exosphere.Bsky.Embed.Video.t()
            | Exosphere.Bsky.Embed.Gallery.t()
            | Exosphere.Bsky.Embed.External.t()
            | Exosphere.Bsky.Embed.Record.t()
            | Exosphere.Bsky.Embed.RecordWithMedia.t()
            | map()
            | nil,
          entities: [Exosphere.Bsky.Feed.Post.Entity.t()] | nil,
          facets: [Exosphere.Bsky.Richtext.Facet.t()] | nil,
          labels: Exosphere.ATProto.Label.Defs.SelfLabels.t() | map() | nil,
          langs: [String.t()] | nil,
          reply: Exosphere.Bsky.Feed.Post.ReplyRef.t() | nil,
          tags: [String.t()] | nil,
          text: String.t()
        }

  @fields %{
    created_at: "createdAt",
    embed: "embed",
    entities: "entities",
    facets: "facets",
    labels: "labels",
    langs: "langs",
    reply: "reply",
    tags: "tags",
    text: "text"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_embed, e2} = Runtime.get_union(attrs, :embed, "embed", [], @variants_embed)

    {f_entities, e3} =
      Runtime.get_array(attrs, :entities, "entities", [], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Feed.Post.Entity)
      end)

    {f_facets, e4} =
      Runtime.get_array(attrs, :facets, "facets", [], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Richtext.Facet)
      end)

    {f_labels, e5} = Runtime.get_union(attrs, :labels, "labels", [], @variants_labels)

    {f_langs, e6} =
      Runtime.get_array(attrs, :langs, "langs", [max_length: 3], fn v, path ->
        Runtime.item_string(v, path, format: "language")
      end)

    {f_reply, e7} = Runtime.get_ref(attrs, :reply, "reply", [], Exosphere.Bsky.Feed.Post.ReplyRef)

    {f_tags, e8} =
      Runtime.get_array(attrs, :tags, "tags", [max_length: 8], fn v, path ->
        Runtime.item_string(v, path, max_length: 640, max_graphemes: 64)
      end)

    {f_text, e9} =
      Runtime.get_string(attrs, :text, "text",
        required: true,
        max_length: 3000,
        max_graphemes: 300
      )

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8 ++ e9

    if errors == [] do
      {:ok,
       %__MODULE__{
         created_at: f_created_at,
         embed: f_embed,
         entities: f_entities,
         facets: f_facets,
         labels: f_labels,
         langs: f_langs,
         reply: f_reply,
         tags: f_tags,
         text: f_text,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("embed", struct.embed, &encode_embed/1)
    |> Runtime.put_field("entities", struct.entities, &encode_entities/1)
    |> Runtime.put_field("facets", struct.facets, &encode_facets/1)
    |> Runtime.put_field("labels", struct.labels, &encode_labels/1)
    |> Runtime.put_field("langs", struct.langs)
    |> Runtime.put_field("reply", struct.reply, &encode_reply/1)
    |> Runtime.put_field("tags", struct.tags)
    |> Runtime.put_field("text", struct.text)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_embed(v) when is_struct(v, Exosphere.Bsky.Embed.Images),
    do: Map.put(Exosphere.Bsky.Embed.Images.to_map(v), "$type", "app.bsky.embed.images")

  defp encode_embed(v) when is_struct(v, Exosphere.Bsky.Embed.Video),
    do: Map.put(Exosphere.Bsky.Embed.Video.to_map(v), "$type", "app.bsky.embed.video")

  defp encode_embed(v) when is_struct(v, Exosphere.Bsky.Embed.Gallery),
    do: Map.put(Exosphere.Bsky.Embed.Gallery.to_map(v), "$type", "app.bsky.embed.gallery")

  defp encode_embed(v) when is_struct(v, Exosphere.Bsky.Embed.External),
    do: Map.put(Exosphere.Bsky.Embed.External.to_map(v), "$type", "app.bsky.embed.external")

  defp encode_embed(v) when is_struct(v, Exosphere.Bsky.Embed.Record),
    do: Map.put(Exosphere.Bsky.Embed.Record.to_map(v), "$type", "app.bsky.embed.record")

  defp encode_embed(v) when is_struct(v, Exosphere.Bsky.Embed.RecordWithMedia),
    do:
      Map.put(
        Exosphere.Bsky.Embed.RecordWithMedia.to_map(v),
        "$type",
        "app.bsky.embed.recordWithMedia"
      )

  defp encode_embed(v) when is_map(v), do: v

  defp encode_entities(values), do: Enum.map(values, &encode_entities_item/1)

  defp encode_entities_item(v), do: encode_ref(v, Exosphere.Bsky.Feed.Post.Entity)

  defp encode_facets(values), do: Enum.map(values, &encode_facets_item/1)

  defp encode_facets_item(v), do: encode_ref(v, Exosphere.Bsky.Richtext.Facet)

  defp encode_labels(v) when is_struct(v, Exosphere.ATProto.Label.Defs.SelfLabels),
    do:
      Map.put(
        Exosphere.ATProto.Label.Defs.SelfLabels.to_map(v),
        "$type",
        "com.atproto.label.defs#selfLabels"
      )

  defp encode_labels(v) when is_map(v), do: v

  defp encode_reply(v), do: encode_ref(v, Exosphere.Bsky.Feed.Post.ReplyRef)
end