# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Feed.Threadgate do
  @moduledoc """
  Record schema `app.bsky.feed.threadgate`.


  ## Fields

  - `allow`: List of rules defining who can reply to this post. If value is an empty array, no one can reply. If value is undefined, anyone can reply.
  - `created_at`: string, format `datetime`
  - `hidden_replies`: List of hidden reply URIs.
  - `post`: Reference (AT-URI) to the post record.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.feed.threadgate"
  @variants_allow [
    {"app.bsky.feed.threadgate#mentionRule", Exosphere.Bsky.Feed.Threadgate.MentionRule},
    {"app.bsky.feed.threadgate#followerRule", Exosphere.Bsky.Feed.Threadgate.FollowerRule},
    {"app.bsky.feed.threadgate#followingRule", Exosphere.Bsky.Feed.Threadgate.FollowingRule},
    {"app.bsky.feed.threadgate#listRule", Exosphere.Bsky.Feed.Threadgate.ListRule}
  ]

  @enforce_keys [:created_at, :post]
  defstruct allow: nil, created_at: nil, hidden_replies: nil, post: nil, extra: %{}

  @type t :: %__MODULE__{
          allow:
            [
              Exosphere.Bsky.Feed.Threadgate.MentionRule.t()
              | Exosphere.Bsky.Feed.Threadgate.FollowerRule.t()
              | Exosphere.Bsky.Feed.Threadgate.FollowingRule.t()
              | Exosphere.Bsky.Feed.Threadgate.ListRule.t()
              | map()
            ]
            | nil,
          created_at: String.t(),
          hidden_replies: [String.t()] | nil,
          post: String.t()
        }

  @fields %{
    allow: "allow",
    created_at: "createdAt",
    hidden_replies: "hiddenReplies",
    post: "post"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_allow, e1} =
      Runtime.get_array(attrs, :allow, "allow", [max_length: 5], fn v, path ->
        Runtime.item_union(v, path, @variants_allow)
      end)

    {f_created_at, e2} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_hidden_replies, e3} =
      Runtime.get_array(attrs, :hidden_replies, "hiddenReplies", [max_length: 300], fn v, path ->
        Runtime.item_string(v, path, format: "at-uri")
      end)

    {f_post, e4} = Runtime.get_string(attrs, :post, "post", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok,
       %__MODULE__{
         allow: f_allow,
         created_at: f_created_at,
         hidden_replies: f_hidden_replies,
         post: f_post,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("allow", struct.allow, &encode_allow/1)
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("hiddenReplies", struct.hidden_replies)
    |> Runtime.put_field("post", struct.post)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_allow(values), do: Enum.map(values, &encode_allow_item/1)

  defp encode_allow_item(v) when is_struct(v, Exosphere.Bsky.Feed.Threadgate.MentionRule),
    do:
      Map.put(
        Exosphere.Bsky.Feed.Threadgate.MentionRule.to_map(v),
        "$type",
        "app.bsky.feed.threadgate#mentionRule"
      )

  defp encode_allow_item(v) when is_struct(v, Exosphere.Bsky.Feed.Threadgate.FollowerRule),
    do:
      Map.put(
        Exosphere.Bsky.Feed.Threadgate.FollowerRule.to_map(v),
        "$type",
        "app.bsky.feed.threadgate#followerRule"
      )

  defp encode_allow_item(v) when is_struct(v, Exosphere.Bsky.Feed.Threadgate.FollowingRule),
    do:
      Map.put(
        Exosphere.Bsky.Feed.Threadgate.FollowingRule.to_map(v),
        "$type",
        "app.bsky.feed.threadgate#followingRule"
      )

  defp encode_allow_item(v) when is_struct(v, Exosphere.Bsky.Feed.Threadgate.ListRule),
    do:
      Map.put(
        Exosphere.Bsky.Feed.Threadgate.ListRule.to_map(v),
        "$type",
        "app.bsky.feed.threadgate#listRule"
      )

  defp encode_allow_item(v) when is_map(v), do: v
end