# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Embed.Video.Caption do
  @moduledoc """
  A video embedded in a Bluesky record (eg, a post).

  Object schema `app.bsky.embed.video##caption`.


  ## Fields

  - `file`: blob
  - `lang`: string, format `language`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.embed.video#caption"

  @enforce_keys [:file, :lang]
  defstruct file: nil, lang: nil, extra: %{}

  @type t :: %__MODULE__{file: term(), lang: String.t()}

  @fields %{file: "file", lang: "lang"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_file, e1} = Runtime.get_any(attrs, :file, "file", required: true)
    {f_lang, e2} = Runtime.get_string(attrs, :lang, "lang", required: true, format: "language")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{file: f_file, lang: f_lang, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("file", struct.file)
    |> Runtime.put_field("lang", struct.lang)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end