defmodule Mix.Tasks.Exosphere.Gen.Lexicons do
  @shortdoc "Generate lexicon modules from vendored lexicons"

  @moduledoc """
  Generates Elixir modules from the lexicon JSON files vendored under
  `priv/lexicons`, for every supported source.

      mix exosphere.gen.lexicons

  Pass a source to scope generation to one namespace; each source writes to
  its own tree under `lib/exosphere`:

      mix exosphere.gen.lexicons app.bsky          # → lib/exosphere/bsky/**
      mix exosphere.gen.lexicons community.lexicon # → lib/exosphere/community/**
      mix exosphere.gen.lexicons com.atproto       # → lib/exosphere/atproto/** (curated)

  With `--check`, regenerates in memory and exits non-zero if any tracked
  generated file would change (used in CI to catch drift). The check only
  covers the selected source.

      mix exosphere.gen.lexicons --check
      mix exosphere.gen.lexicons --check community.lexicon

  Fetch lexicons published by a repository (as `com.atproto.lexicon.schema`
  records) before generating, vendoring them under `priv/lexicons` so the
  result is reproducible on later runs:

      mix exosphere.gen.lexicons --from did:plc:abc123 [--pds https://pds.example.com]

  The PDS is found via DID resolution unless `--pds` is given. Lexicons
  from authorities without a namespace rule generate under their full NSID
  segments (e.g. `com.example.post` → `Exosphere.Com.Example.Post`).

  Generation is deterministic: the same vendored lexicons always produce
  the same files, so output can be reviewed with `git diff`. Refs the
  corpus can not resolve (fields that degrade to `term()`) are reported
  as warnings.
  """

  use Mix.Task

  alias Exosphere.ATProto.Identity.DID
  alias Exosphere.Lexicon.{Generator, Parser, Resolver}

  @lexicon_dir "priv/lexicons"
  @output_dir "lib/exosphere"
  @generated_marker "# Generated by `mix exosphere.gen.lexicons`"

  # Vendored NSID prefixes and where their modules land under lib/exosphere
  @sources %{
    "app.bsky" => "bsky",
    "community.lexicon" => "community",
    "com.atproto" => "atproto"
  }

  @impl Mix.Task
  def run(args) do
    {opts, positional, invalid} =
      OptionParser.parse(args, strict: [check: :boolean, from: :string, pds: :string])

    unless invalid == [] do
      Mix.raise("invalid arguments: #{inspect(invalid)}")
    end

    source = validate_source!(positional)
    maybe_vendor_from!(opts)

    Mix.Task.run("app.start")

    case Parser.parse_dir(@lexicon_dir) do
      {:ok, lexicons} ->
        warn_unresolved_refs(lexicons, opts)

        specs =
          lexicons
          |> Generator.generate()
          |> scope(source)

        if opts[:check] do
          check(specs, source)
        else
          files = Generator.write!(specs, @output_dir)
          Mix.shell().info("Generated #{length(files)} modules into #{@output_dir}")
        end

      {:error, {path, reason}} ->
        Mix.shell().error("Failed to parse #{path}: #{inspect(reason)}")
        exit({:shutdown, 1})

      {:error, reason} ->
        Mix.shell().error("Failed to read lexicons: #{inspect(reason)}")
        exit({:shutdown, 1})
    end
  end

  defp validate_source!([]), do: nil

  defp validate_source!([source]) do
    unless Map.has_key?(@sources, source) do
      Mix.raise(
        "unknown source #{inspect(source)}; expected one of #{inspect(Map.keys(@sources))}"
      )
    end

    source
  end

  defp validate_source!(sources),
    do: Mix.raise("expected at most one source, got: #{inspect(sources)}")

  # --from: fetch a repo's published lexicons and vendor them, so the
  # generation below (and future runs) include them.
  defp maybe_vendor_from!(opts) do
    case Keyword.get(opts, :from) do
      nil ->
        :ok

      did when is_binary(did) ->
        if opts[:check] do
          Mix.raise("--from can not be combined with --check")
        end

        pds_url = pds_url!(did, opts)

        case Resolver.list(pds_url, did) do
          {:ok, schemas, %{invalid: invalid}} ->
            Enum.each(invalid, &Mix.shell().error("skipped invalid lexicon record: #{&1}"))
            paths = Enum.map(schemas, &vendor!/1)
            Mix.shell().info("Vendored #{length(paths)} lexicons from #{did}")

          {:error, reason} ->
            Mix.shell().error("failed to fetch lexicons from #{did}: #{inspect(reason)}")
            exit({:shutdown, 1})
        end
    end
  end

  defp pds_url!(did, opts) do
    case Keyword.get(opts, :pds) do
      pds when is_binary(pds) ->
        pds

      nil ->
        with {:ok, doc} <- DID.resolve(did),
             {:ok, pds_url} <- DID.get_pds_endpoint(doc) do
          pds_url
        else
          error ->
            Mix.shell().error("could not find PDS for #{did}: #{inspect(error)}")
            exit({:shutdown, 1})
        end
    end
  end

  # Write the raw document as priv/lexicons/<authority>/<name>.json,
  # matching the vendored corpus layout.
  defp vendor!(schema) do
    path = Path.join(@lexicon_dir, "#{lexicon_path(schema.id)}.json")
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, Jason.encode!(json_of(schema), pretty: true) <> "\n")
    path
  end

  defp json_of(schema) do
    %{"lexicon" => schema.lexicon, "id" => schema.id, "defs" => schema.defs}
    |> Map.merge(if(schema.description, do: %{"description" => schema.description}, else: %{}))
  end

  defp lexicon_path(nsid) do
    nsid
    |> String.split(".")
    |> Path.join()
  end

  defp warn_unresolved_refs(lexicons, _opts) do
    lexicons
    |> Generator.unresolved_refs()
    |> Enum.each(fn {nsid, ref, location} ->
      Mix.shell().error(
        "warning: #{nsid} ref #{inspect(ref)} at #{location} is not in the corpus; " <>
          "fields using it generate as term()"
      )
    end)
  end

  defp scope(specs, nil), do: specs

  defp scope(specs, source) do
    Enum.filter(specs, &String.starts_with?(&1.nsid, source))
  end

  defp check(specs, source) do
    drifted =
      Enum.filter(specs, fn %{path: rel, code: code} ->
        path = Path.join(@output_dir, rel)
        File.exists?(path) && File.read!(path) != code
      end)

    missing =
      Enum.filter(specs, fn %{path: rel} -> not File.exists?(Path.join(@output_dir, rel)) end)

    # Stale generated files (present on disk, no longer produced)
    produced = MapSet.new(specs, & &1.path)
    scope_glob = if source, do: "#{@sources[source]}/**/*.ex", else: "**/*.ex"

    stale =
      @output_dir
      |> Path.join(scope_glob)
      |> Path.wildcard()
      |> Enum.map(&Path.relative_to(&1, @output_dir))
      |> Enum.reject(&MapSet.member?(produced, &1))
      |> Enum.filter(fn rel ->
        # Only flag files we generated; runtime.ex and friends are hand-written
        case File.read(Path.join(@output_dir, rel)) do
          {:ok, content} -> String.starts_with?(content, @generated_marker)
          _ -> false
        end
      end)

    if drifted != [] or missing != [] or stale != [] do
      Enum.each(drifted, &Mix.shell().error("drifted: #{&1.path}"))
      Enum.each(missing, &Mix.shell().error("missing: #{Path.join(@output_dir, &1.path)}"))
      Enum.each(stale, &Mix.shell().error("stale: #{Path.join(@output_dir, &1)}"))
      exit({:shutdown, 1})
    else
      Mix.shell().info("Generated modules up to date (#{length(specs)} files)")
    end
  end
end
