defmodule Mix.Tasks.Exosphere.Gen.Lexicons do
  @shortdoc "Generate lexicon modules from vendored lexicons"

  @moduledoc """
  Generates Elixir modules from the lexicon JSON files vendored under
  `priv/lexicons`, for every supported source.

      mix exosphere.gen.lexicons

  Pass a source to scope generation to one namespace; each source writes to
  its own tree under `lib/exosphere`:

      mix exosphere.gen.lexicons app.bsky          # → lib/exosphere/bsky/**
      mix exosphere.gen.lexicons community.lexicon # → lib/exosphere/community/**
      mix exosphere.gen.lexicons com.atproto       # → lib/exosphere/atproto/** (curated)

  With `--check`, regenerates in memory and exits non-zero if any tracked
  generated file would change (used in CI to catch drift). The check only
  covers the selected source.

      mix exosphere.gen.lexicons --check
      mix exosphere.gen.lexicons --check community.lexicon

  Generation is deterministic: the same vendored lexicons always produce the
  same files, so output can be reviewed with `git diff`.
  """

  use Mix.Task

  alias Exosphere.Lexicon.{Generator, Parser}

  @lexicon_dir "priv/lexicons"
  @output_dir "lib/exosphere"
  @generated_marker "# Generated by `mix exosphere.gen.lexicons`"

  # Vendored NSID prefixes and where their modules land under lib/exosphere
  @sources %{
    "app.bsky" => "bsky",
    "community.lexicon" => "community",
    "com.atproto" => "atproto"
  }

  @impl Mix.Task
  def run(args) do
    {opts, positional, invalid} = OptionParser.parse(args, strict: [check: :boolean])

    unless invalid == [] do
      Mix.raise("invalid arguments: #{inspect(invalid)}")
    end

    source = validate_source!(positional)

    Mix.Task.run("app.start")

    case Parser.parse_dir(@lexicon_dir) do
      {:ok, lexicons} ->
        specs =
          lexicons
          |> Generator.generate()
          |> scope(source)

        if opts[:check] do
          check(specs, source)
        else
          files = Generator.write!(specs, @output_dir)
          Mix.shell().info("Generated #{length(files)} modules into #{@output_dir}")
        end

      {:error, {path, reason}} ->
        Mix.shell().error("Failed to parse #{path}: #{inspect(reason)}")
        exit({:shutdown, 1})

      {:error, reason} ->
        Mix.shell().error("Failed to read lexicons: #{inspect(reason)}")
        exit({:shutdown, 1})
    end
  end

  defp validate_source!([]), do: nil

  defp validate_source!([source]) do
    unless Map.has_key?(@sources, source) do
      Mix.raise(
        "unknown source #{inspect(source)}; expected one of #{inspect(Map.keys(@sources))}"
      )
    end

    source
  end

  defp validate_source!(sources),
    do: Mix.raise("expected at most one source, got: #{inspect(sources)}")

  defp scope(specs, nil), do: specs

  defp scope(specs, source) do
    Enum.filter(specs, &String.starts_with?(&1.nsid, source))
  end

  defp check(specs, source) do
    drifted =
      Enum.filter(specs, fn %{path: rel, code: code} ->
        path = Path.join(@output_dir, rel)
        File.exists?(path) && File.read!(path) != code
      end)

    missing =
      Enum.filter(specs, fn %{path: rel} -> not File.exists?(Path.join(@output_dir, rel)) end)

    # Stale generated files (present on disk, no longer produced)
    produced = MapSet.new(specs, & &1.path)
    scope_glob = if source, do: "#{@sources[source]}/**/*.ex", else: "**/*.ex"

    stale =
      @output_dir
      |> Path.join(scope_glob)
      |> Path.wildcard()
      |> Enum.map(&Path.relative_to(&1, @output_dir))
      |> Enum.reject(&MapSet.member?(produced, &1))
      |> Enum.filter(fn rel ->
        # Only flag files we generated; runtime.ex and friends are hand-written
        case File.read(Path.join(@output_dir, rel)) do
          {:ok, content} -> String.starts_with?(content, @generated_marker)
          _ -> false
        end
      end)

    if drifted != [] or missing != [] or stale != [] do
      Enum.each(drifted, &Mix.shell().error("drifted: #{&1.path}"))
      Enum.each(missing, &Mix.shell().error("missing: #{Path.join(@output_dir, &1.path)}"))
      Enum.each(stale, &Mix.shell().error("stale: #{Path.join(@output_dir, &1)}"))
      exit({:shutdown, 1})
    else
      Mix.shell().info("Generated modules up to date (#{length(specs)} files)")
    end
  end
end
