defmodule Mix.Tasks.Exosphere.Gen.Bsky do
  @shortdoc "Generate Exosphere.Bsky modules from vendored lexicons"

  @moduledoc """
  Generates `Exosphere.Bsky.*` record modules from the lexicon JSON files
  vendored under `priv/lexicons`.

  Regeneration is deterministic: the same vendored lexicons always produce
  the same files, so regenerated output can be reviewed with `git diff`.

      mix exosphere.gen.bsky

  With `--check`, regenerates in memory and exits non-zero if any tracked
  generated file would change (useful in CI to catch drift).

      mix exosphere.gen.bsky --check
  """

  use Mix.Task

  alias Exosphere.Lexicon.{Generator, Parser}

  @lexicon_dir "priv/lexicons"
  @output_dir "lib/exosphere"
  @generated_marker "# Generated by `mix exosphere.gen.bsky`"

  @impl Mix.Task
  def run(args) do
    {opts, _argv, _invalid} = OptionParser.parse(args, strict: [check: :boolean])

    Mix.Task.run("app.start")

    case Parser.parse_dir(@lexicon_dir) do
      {:ok, lexicons} ->
        specs = Generator.generate(lexicons)

        if opts[:check] do
          check(specs)
        else
          files = Generator.write!(specs, @output_dir)
          Mix.shell().info("Generated #{length(files)} modules into #{@output_dir}")
        end

      {:error, {path, reason}} ->
        Mix.shell().error("Failed to parse #{path}: #{inspect(reason)}")
        exit({:shutdown, 1})

      {:error, reason} ->
        Mix.shell().error("Failed to read lexicons: #{inspect(reason)}")
        exit({:shutdown, 1})
    end
  end

  defp check(specs) do
    drifted =
      Enum.filter(specs, fn %{path: rel, code: code} ->
        path = Path.join(@output_dir, rel)
        File.exists?(path) && File.read!(path) != code
      end)

    missing = Enum.filter(specs, fn %{path: rel} -> not File.exists?(Path.join(@output_dir, rel)) end)

    # Stale generated files (present on disk, no longer produced)
    produced = MapSet.new(specs, & &1.path)

    stale =
      @output_dir
      |> Path.join("**/*.ex")
      |> Path.wildcard()
      |> Enum.map(&Path.relative_to(&1, @output_dir))
      |> Enum.reject(&MapSet.member?(produced, &1))
      |> Enum.filter(fn rel ->
        # Only flag files we generated (runtime.ex is hand-written)
        case File.read(Path.join(@output_dir, rel)) do
          # Match only files whose first line is the banner; the marker
          # string also appears in the generator's own source.
          {:ok, content} -> String.starts_with?(content, @generated_marker)
          _ -> false
        end
      end)

    if drifted != [] or missing != [] or stale != [] do
      Enum.each(drifted, &Mix.shell().error("drifted: #{&1.path}"))
      Enum.each(missing, &Mix.shell().error("missing: #{Path.join(@output_dir, &1.path)}"))
      Enum.each(stale, &Mix.shell().error("stale: #{Path.join(@output_dir, &1)}"))
      exit({:shutdown, 1})
    else
      Mix.shell().info("Generated modules up to date (#{length(specs)} files)")
    end
  end
end
