# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Community.Location.Address do
  @moduledoc """
  A physical location in the form of a street address.

  Object schema `community.lexicon.location.address`.


  ## Fields

  - `country`: The ISO 3166 country code. Preferably the 2-letter code.
  - `locality`: The locality of the region. For example, a city in the USA.
  - `name`: The name of the location.
  - `postal_code`: The postal code of the location.
  - `region`: The administrative region of the country. For example, a state in the USA.
  - `street`: The street address.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.location.address"

  @enforce_keys [:country]
  defstruct country: nil,
            locality: nil,
            name: nil,
            postal_code: nil,
            region: nil,
            street: nil,
            extra: %{}

  @type t :: %__MODULE__{
          country: String.t(),
          locality: String.t() | nil,
          name: String.t() | nil,
          postal_code: String.t() | nil,
          region: String.t() | nil,
          street: String.t() | nil
        }

  @fields %{
    country: "country",
    locality: "locality",
    name: "name",
    postal_code: "postalCode",
    region: "region",
    street: "street"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_country, e1} =
      Runtime.get_string(attrs, :country, "country",
        required: true,
        min_length: 2,
        max_length: 10
      )

    {f_locality, e2} = Runtime.get_string(attrs, :locality, "locality", [])
    {f_name, e3} = Runtime.get_string(attrs, :name, "name", [])
    {f_postal_code, e4} = Runtime.get_string(attrs, :postal_code, "postalCode", [])
    {f_region, e5} = Runtime.get_string(attrs, :region, "region", [])
    {f_street, e6} = Runtime.get_string(attrs, :street, "street", [])

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6

    if errors == [] do
      {:ok,
       %__MODULE__{
         country: f_country,
         locality: f_locality,
         name: f_name,
         postal_code: f_postal_code,
         region: f_region,
         street: f_street,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("country", struct.country)
    |> Runtime.put_field("locality", struct.locality)
    |> Runtime.put_field("name", struct.name)
    |> Runtime.put_field("postalCode", struct.postal_code)
    |> Runtime.put_field("region", struct.region)
    |> Runtime.put_field("street", struct.street)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end