# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Location.Fsq do
  @moduledoc """
  A physical location contained in the Foursquare Open Source Places dataset.

  Object schema `community.lexicon.location.fsq`.


  ## Fields

  - `fsq_place_id`: The unique identifier of a Foursquare POI.
  - `latitude`: string
  - `longitude`: string
  - `name`: The name of the location.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.location.fsq"

  @enforce_keys [:fsq_place_id]
  defstruct fsq_place_id: nil, latitude: nil, longitude: nil, name: nil, extra: %{}

  @type t :: %__MODULE__{
          fsq_place_id: String.t(),
          latitude: String.t() | nil,
          longitude: String.t() | nil,
          name: String.t() | nil
        }

  @fields %{
    fsq_place_id: "fsq_place_id",
    latitude: "latitude",
    longitude: "longitude",
    name: "name"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_fsq_place_id, e1} =
      Runtime.get_string(attrs, :fsq_place_id, "fsq_place_id", required: true)

    {f_latitude, e2} = Runtime.get_string(attrs, :latitude, "latitude", [])
    {f_longitude, e3} = Runtime.get_string(attrs, :longitude, "longitude", [])
    {f_name, e4} = Runtime.get_string(attrs, :name, "name", [])

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok,
       %__MODULE__{
         fsq_place_id: f_fsq_place_id,
         latitude: f_latitude,
         longitude: f_longitude,
         name: f_name,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("fsq_place_id", struct.fsq_place_id)
    |> Runtime.put_field("latitude", struct.latitude)
    |> Runtime.put_field("longitude", struct.longitude)
    |> Runtime.put_field("name", struct.name)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end