# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Graph.List do
  @moduledoc """
  Record schema `app.bsky.graph.list`.


  ## Fields

  - `avatar`: blob
  - `created_at`: string, format `datetime`
  - `description`: string
  - `description_facets`: array
  - `labels`: union
  - `name`: Display name for list; can not be empty.
  - `purpose`: ref `app.bsky.graph.defs#listPurpose`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.graph.list"
  @variants_labels [
    {"com.atproto.label.defs#selfLabels", Exosphere.ATProto.Label.Defs.SelfLabels}
  ]

  @enforce_keys [:created_at, :name, :purpose]
  defstruct avatar: nil,
            created_at: nil,
            description: nil,
            description_facets: nil,
            labels: nil,
            name: nil,
            purpose: nil,
            extra: %{}

  @type t :: %__MODULE__{
          avatar: term() | nil,
          created_at: String.t(),
          description: String.t() | nil,
          description_facets: [Exosphere.Bsky.Richtext.Facet.t()] | nil,
          labels: Exosphere.ATProto.Label.Defs.SelfLabels.t() | map() | nil,
          name: String.t(),
          purpose: term()
        }

  @fields %{
    avatar: "avatar",
    created_at: "createdAt",
    description: "description",
    description_facets: "descriptionFacets",
    labels: "labels",
    name: "name",
    purpose: "purpose"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_avatar, e1} = Runtime.get_any(attrs, :avatar, "avatar", [])

    {f_created_at, e2} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_description, e3} =
      Runtime.get_string(attrs, :description, "description", max_length: 3000, max_graphemes: 300)

    {f_description_facets, e4} =
      Runtime.get_array(attrs, :description_facets, "descriptionFacets", [], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Richtext.Facet)
      end)

    {f_labels, e5} = Runtime.get_union(attrs, :labels, "labels", [], @variants_labels)

    {f_name, e6} =
      Runtime.get_string(attrs, :name, "name", required: true, min_length: 1, max_length: 64)

    {f_purpose, e7} = Runtime.get_any(attrs, :purpose, "purpose", required: true)

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7

    if errors == [] do
      {:ok,
       %__MODULE__{
         avatar: f_avatar,
         created_at: f_created_at,
         description: f_description,
         description_facets: f_description_facets,
         labels: f_labels,
         name: f_name,
         purpose: f_purpose,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("avatar", struct.avatar)
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field(
      "descriptionFacets",
      struct.description_facets,
      &encode_description_facets/1
    )
    |> Runtime.put_field("labels", struct.labels, &encode_labels/1)
    |> Runtime.put_field("name", struct.name)
    |> Runtime.put_field("purpose", struct.purpose)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_description_facets(values), do: Enum.map(values, &encode_description_facets_item/1)

  defp encode_description_facets_item(v), do: encode_ref(v, Exosphere.Bsky.Richtext.Facet)

  defp encode_labels(v) when is_struct(v, Exosphere.ATProto.Label.Defs.SelfLabels),
    do:
      Map.put(
        Exosphere.ATProto.Label.Defs.SelfLabels.to_map(v),
        "$type",
        "com.atproto.label.defs#selfLabels"
      )

  defp encode_labels(v) when is_map(v), do: v
end