# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Graph.Starterpack do
  @moduledoc """
  Record schema `app.bsky.graph.starterpack`.


  ## Fields

  - `created_at`: string, format `datetime`
  - `description`: string
  - `description_facets`: array
  - `feeds`: array
  - `list`: Reference (AT-URI) to the list record.
  - `name`: Display name for starter pack; can not be empty.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.graph.starterpack"

  @enforce_keys [:created_at, :list, :name]
  defstruct created_at: nil,
            description: nil,
            description_facets: nil,
            feeds: nil,
            list: nil,
            name: nil,
            extra: %{}

  @type t :: %__MODULE__{
          created_at: String.t(),
          description: String.t() | nil,
          description_facets: [Exosphere.Bsky.Richtext.Facet.t()] | nil,
          feeds: [Exosphere.Bsky.Graph.Starterpack.FeedItem.t()] | nil,
          list: String.t(),
          name: String.t()
        }

  @fields %{
    created_at: "createdAt",
    description: "description",
    description_facets: "descriptionFacets",
    feeds: "feeds",
    list: "list",
    name: "name"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_description, e2} =
      Runtime.get_string(attrs, :description, "description", max_length: 3000, max_graphemes: 300)

    {f_description_facets, e3} =
      Runtime.get_array(attrs, :description_facets, "descriptionFacets", [], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Richtext.Facet)
      end)

    {f_feeds, e4} =
      Runtime.get_array(attrs, :feeds, "feeds", [max_length: 3], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.Bsky.Graph.Starterpack.FeedItem)
      end)

    {f_list, e5} = Runtime.get_string(attrs, :list, "list", required: true, format: "at-uri")

    {f_name, e6} =
      Runtime.get_string(attrs, :name, "name",
        required: true,
        min_length: 1,
        max_length: 500,
        max_graphemes: 50
      )

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6

    if errors == [] do
      {:ok,
       %__MODULE__{
         created_at: f_created_at,
         description: f_description,
         description_facets: f_description_facets,
         feeds: f_feeds,
         list: f_list,
         name: f_name,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field(
      "descriptionFacets",
      struct.description_facets,
      &encode_description_facets/1
    )
    |> Runtime.put_field("feeds", struct.feeds, &encode_feeds/1)
    |> Runtime.put_field("list", struct.list)
    |> Runtime.put_field("name", struct.name)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_description_facets(values), do: Enum.map(values, &encode_description_facets_item/1)

  defp encode_description_facets_item(v), do: encode_ref(v, Exosphere.Bsky.Richtext.Facet)

  defp encode_feeds(values), do: Enum.map(values, &encode_feeds_item/1)

  defp encode_feeds_item(v), do: encode_ref(v, Exosphere.Bsky.Graph.Starterpack.FeedItem)
end