# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Interaction.Like do
  @moduledoc """
  Record schema `community.lexicon.interaction.like`.


  ## Fields

  - `created_at`: string, format `datetime`
  - `subject`: ref `com.atproto.repo.strongRef`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.interaction.like"

  @enforce_keys [:created_at, :subject]
  defstruct created_at: nil, subject: nil, extra: %{}

  @type t :: %__MODULE__{created_at: String.t(), subject: Exosphere.ATProto.Repo.StrongRef.t()}

  @fields %{created_at: "createdAt", subject: "subject"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_subject, e2} =
      Runtime.get_ref(
        attrs,
        :subject,
        "subject",
        [required: true],
        Exosphere.ATProto.Repo.StrongRef
      )

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{created_at: f_created_at, subject: f_subject, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("subject", struct.subject, &encode_subject/1)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_subject(v), do: encode_ref(v, Exosphere.ATProto.Repo.StrongRef)
end