defmodule Exosphere.Lexicon.Generator do
  @moduledoc """
  Generates Elixir record modules from parsed lexicon IR.

  For each `app.bsky.*` lexicon, generates one module for its `main` def
  plus nested modules for internal `#defs` reachable from it:

  - `app.bsky.feed.post` (record) → `Exosphere.Bsky.Feed.Post`
  - `app.bsky.richtext.facet#byteSlice` → `Exosphere.Bsky.Richtext.Facet.ByteSlice`

  Each generated module has:

  - a struct with snake_cased fields plus an `extra` map for unknown keys
  - `new/1` — build and validate from atom- or string-keyed attrs,
    returning `{:ok, struct} | {:error, [{path, message}]}`
  - `to_map/1` — encode to wire format (record mains inject `"$type"`;
    union encoders inject `"$type"` into their variants)
  - `from_map/1` — decode a wire map (delegates to `new/1`)
  - `type_id/0` — the def's NSID (`"app.bsky.feed.post"`, `"…#replyRef"`, or nil)

  Cross-lexicon refs resolve when the target def is itself being generated;
  unresolved refs degrade to pass-through `term()` values.
  """

  alias Exosphere.Lexicon.Parser

  @header """
  # Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
  # Regenerate with: mix exosphere.gen.lexicons
  """

  @type spec :: %{
          module: module(),
          path: String.t(),
          nsid: String.t(),
          def_name: String.t() | nil,
          node: Parser.schema_node(),
          lexicon: Parser.lexicon()
        }

  # NSID prefixes collapsed into a single module namespace segment.
  # Hand-written core modules living under these prefixes are reserved and
  # guarded against below.
  @namespace_rules [
    {"app.bsky.", [Exosphere, Bsky]},
    {"com.atproto.", [Exosphere, "ATProto"]},
    {"community.lexicon.", [Exosphere, Community]}
  ]

  # Hand-written modules that generated code must never overwrite.
  @reserved_modules [
    Exosphere,
    Exosphere.ATProto,
    Exosphere.ATProto.Bsky,
    Exosphere.ATProto.CAR,
    Exosphere.ATProto.CBOR,
    Exosphere.ATProto.CID,
    Exosphere.ATProto.Crypto,
    Exosphere.ATProto.HTTP,
    Exosphere.ATProto.NSID,
    Exosphere.ATProto.Repo,
    Exosphere.ATProto.TID,
    Exosphere.ATProto.AtUri,
    Exosphere.ATProto.Identity.DID,
    Exosphere.ATProto.Identity.Handle,
    Exosphere.ATProto.MST,
    Exosphere.Bsky.Runtime,
    Exosphere.Lexicon.Parser,
    Exosphere.Lexicon.Generator
  ]

  @doc """
  Generate all modules for `lexicons` (as from `Parser.parse_dir/1`).

  Namespace rules: `app.bsky.*` maps to `Exosphere.Bsky.*`,
  `com.atproto.*` to `Exosphere.ATProto.*`, `community.lexicon.*` to
  `Exosphere.Community.*`; any other authority maps by its full NSID
  segments.

  Generation starts from every lexicon whose `main` def is a record or
  object (XRPC query/procedure/subscription and permission-set defs are
  parsed but not yet generated), then walks refs transitively across
  lexicons — including into main-less `defs.json` lexicons — generating a
  nested module for each reachable object/record def. Refs to non-object
  defs (e.g. string enum defs) and to unvendored lexicons degrade to
  pass-through `term()` values.

  Returns specs (module, path relative to `lib/exosphere`, formatted code),
  ordered parents-first.
  """
  @spec generate(%{String.t() => Parser.lexicon()}) :: [
          %{module: module(), path: String.t(), code: String.t()}
        ]
  def generate(lexicons) do
    targets = reachable_targets(lexicons)

    specs =
      Enum.map(targets, fn {nsid, def_name} ->
        module_spec(lexicons[nsid], def_name)
      end)

    endpoint_specs = endpoint_specs(lexicons)

    check_collisions!(specs ++ endpoint_specs)

    modules = Map.new(specs, &{{&1.nsid, &1.def_name || "main"}, &1.module})

    ctx = %{modules: modules}

    (specs ++ endpoint_specs)
    |> Enum.sort_by(fn spec -> {spec.module |> Module.split() |> length(), spec.module} end)
    |> Enum.map(fn spec ->
      Map.merge(spec, %{code: format(render(spec, ctx))})
    end)
  end

  # Walk refs transitively from all record/object mains, collecting the set
  # of {nsid, def_name} targets that need generated modules.
  defp reachable_targets(lexicons) do
    seeds =
      lexicons
      |> Enum.filter(fn {_nsid, lexicon} ->
        main = lexicon.defs["main"]
        main && main.kind in [:record, :object]
      end)
      |> Enum.map(fn {nsid, _lexicon} -> {nsid, "main"} end)
      |> MapSet.new()

    walk(MapSet.to_list(seeds), MapSet.new(seeds), lexicons)
    |> MapSet.to_list()
    |> Enum.sort()
  end

  defp walk([], visited, _lexicons), do: visited

  defp walk([{nsid, def_name} | rest], visited, lexicons) do
    node = lexicons[nsid].defs[def_name]

    refs =
      node
      |> node_refs()
      |> Enum.map(&resolve_ref(&1, nsid))
      |> Enum.reject(&is_nil/1)
      |> Enum.filter(fn {t_nsid, t_def} ->
        # Only object/record defs become modules; other def kinds and
        # unvendored lexicons stay passthrough.
        case lexicons[t_nsid] do
          nil ->
            false

          t_lexicon ->
            target = t_lexicon.defs[t_def]
            target != nil and target.kind in [:record, :object]
        end
      end)
      |> Enum.reject(&MapSet.member?(visited, &1))

    walk(refs ++ rest, Enum.reduce(refs, visited, &MapSet.put(&2, &1)), lexicons)
  end

  # All ref strings reachable inside a schema node.
  defp node_refs(%{kind: :ref, ref: ref}), do: [ref]

  defp node_refs(%{kind: :union, refs: refs}), do: refs

  defp node_refs(%{kind: :array, items: items}), do: node_refs(items)

  defp node_refs(%{kind: :object, properties: props}),
    do: Enum.flat_map(props, fn {_name, prop} -> node_refs(prop) end)

  defp node_refs(%{kind: :record, record: record}), do: node_refs(record)

  defp node_refs(_), do: []

  defp check_collisions!(specs) do
    specs
    |> Enum.map(& &1.module)
    |> then(fn modules ->
      dups = modules -- Enum.uniq(modules)

      unless dups == [] do
        raise ArgumentError, "duplicate generated modules: #{inspect(Enum.uniq(dups))}"
      end

      reserved = Enum.filter(modules, &(&1 in @reserved_modules))

      unless reserved == [] do
        raise ArgumentError,
              "generated modules collide with hand-written core: #{inspect(reserved)}"
      end
    end)
  end

  @doc """
  Write generated specs under `lib_dir` (default `lib/exosphere`),
  creating directories as needed. Returns the paths written.
  """
  @spec write!([%{module: module(), path: String.t(), code: String.t()}], Path.t()) :: [Path.t()]
  def write!(specs, lib_dir \\ "lib/exosphere") do
    Enum.map(specs, fn %{path: rel, code: code} ->
      path = Path.join(lib_dir, rel)
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, code)
      path
    end)
  end

  defp format(code) do
    code |> Code.format_string!() |> IO.iodata_to_binary()
  rescue
    _error ->
      reraise ArgumentError,
              [message: "generator produced unparseable code:\n\n#{code}"],
              __STACKTRACE__
  end

  # --- Endpoint modules -----------------------------------------------------------

  # One module per generated namespace (e.g. Exosphere.Bsky.Actor,
  # Exosphere.Community.Bookmarks) holding a typed function for each XRPC
  # query/procedure lexicon in that namespace.
  @endpoint_namespaces ["app.bsky.", "community.lexicon."]

  defp endpoint_specs(lexicons) do
    lexicons
    |> Enum.filter(fn {nsid, lexicon} ->
      main = lexicon.defs["main"]

      String.starts_with?(nsid, @endpoint_namespaces) and main != nil and
        main.kind in [:query, :procedure]
    end)
    |> Enum.group_by(fn {nsid, _lexicon} -> namespace_of(nsid) end)
    |> Enum.map(fn {namespace, endpoints} ->
      module = namespace_module(namespace)
      check_endpoint_name_clashes!(module, endpoints)

      %{
        module: module,
        path: module_path(module),
        nsid: namespace,
        def_name: nil,
        node: %{kind: :endpoints},
        lexicon: nil,
        endpoints: Enum.sort(endpoints)
      }
    end)
  end

  defp namespace_of(nsid) do
    segments = String.split(nsid, ".")
    Enum.take(segments, length(segments) - 1) |> Enum.join(".")
  end

  # The namespace module for e.g. "app.bsky.actor" is Exosphere.Bsky.Actor;
  # the bare "app.bsky" namespace is Exosphere.Bsky itself.
  defp namespace_module(namespace) do
    case Enum.find(@namespace_rules, fn {prefix, _base} ->
           String.starts_with?(namespace, prefix)
         end) do
      {prefix, base} ->
        rest =
          namespace
          |> String.trim_leading(prefix)
          |> String.split(".")
          |> Enum.map(&Macro.camelize/1)
          |> Enum.reject(&(&1 == ""))

        Module.concat(base ++ rest)

      nil ->
        namespace
        |> String.split(".")
        |> Enum.map(&Macro.camelize/1)
        |> then(&Module.concat([Exosphere | &1]))
    end
  end

  defp check_endpoint_name_clashes!(module, endpoints) do
    names = Enum.map(endpoints, fn {nsid, _} -> endpoint_fn_name(nsid) end)
    dups = names -- Enum.uniq(names)

    unless dups == [] do
      raise ArgumentError,
            "endpoint name collisions in #{inspect(module)}: #{inspect(Enum.uniq(dups))}"
    end
  end

  defp endpoint_fn_name(nsid), do: nsid |> String.split(".") |> List.last() |> Macro.underscore()

  defp endpoint_moduledoc(spec) do
    items =
      Enum.map_join(spec.endpoints, "\n", fn {nsid, lexicon} ->
        main = lexicon.defs["main"]
        "- `#{endpoint_fn_name(nsid)}` — #{main.kind}: #{nsid}"
      end)

    """
      @moduledoc \"\"\"
      XRPC client functions for the `#{spec.nsid}` namespace.

      Generated from vendored lexicons — DO NOT EDIT.

      ## Endpoints

    #{indent(items, 2)}
      \"\"\"
    """
  end

  defp render_endpoint(nsid, lexicon, ctx) do
    main = lexicon.defs["main"]
    fn_name = endpoint_fn_name(nsid)
    {_raw, fields, required} = endpoint_params(main)
    req = %{required: required, nullable: []}
    output_mod = output_module(main, ctx)

    doc =
      [main.description, endpoint_params_doc(main.parameters)]
      |> Enum.reject(&is_nil/1)
      |> Enum.join("\n\n")

    bindings =
      fields
      |> Enum.with_index(1)
      |> Enum.map(fn {{name, node}, i} ->
        "      {#{field_var(name)}, e#{i}} = #{getter(name, node, req, ctx)}"
      end)

    validated_pairs =
      Enum.map_join(fields, ", ", fn {name, _} -> "#{field_atom(name)}: #{field_var(name)}" end)

    errors_list =
      case length(fields) do
        0 -> ""
        n -> Enum.map_join(1..n, " ++ ", &"e#{&1}")
      end

    # Endpoints with no params skip validation entirely
    skip_validation = fields == []

    {args, spec_args, call} =
      case {main.kind, fields == []} do
        {:query, false} ->
          {"client, params \\\\ []", "Client.t(), map() | keyword()",
           "Client.query(#{inspect(nsid)}, Runtime.encode_query_params(validated, @fields_#{fn_name}))"}

        {:query, true} ->
          {"client", "Client.t()", "Client.query(#{inspect(nsid)})"}

        {:procedure, true} ->
          {"client, body \\\\ %{}", "Client.t(), map()",
           "Client.procedure(#{inspect(nsid)}, body)"}

        {:procedure, false} ->
          {"client, params \\\\ [], body \\\\ %{}", "Client.t(), map() | keyword(), map()",
           "Client.procedure(#{inspect(nsid)}, body, Runtime.encode_query_params(validated, @fields_#{fn_name}))"}
      end

    validate =
      cond do
        skip_validation ->
          ""

        fields == [] ->
          "    defp validate_#{fn_name}(_params), do: {:ok, %{}}"

        true ->
          """
              defp validate_#{fn_name}(params) do
                {attrs, _extra} = Runtime.atomize(params, @fields_#{fn_name})

          #{Enum.join(bindings, "\n")}

                errors = #{errors_list}

                if errors == [] do
                  {:ok, %{#{validated_pairs}}}
                else
                  {:error, errors}
                end
              end
          """
      end

    decode_fn =
      if output_mod do
        """

            defp decode_#{fn_name}({:ok, %{} = response}), do: #{inspect(output_mod)}.from_map(response)
            defp decode_#{fn_name}(other), do: other
        """
      else
        ""
      end

    return_type =
      if output_mod,
        do: "{:ok, #{inspect(output_mod)}.t()} | {:error, term()}",
        else: "{:ok, map()} | {:error, term()}"

    fields_attr =
      if fields == [],
        do: "",
        else: "  @fields_#{fn_name} %{#{fields_map_literal(fields)}}\n\n"

    decode =
      if output_mod,
        do: "\n        |> decode_#{fn_name}()",
        else: ""

    body =
      if skip_validation do
        """
            def #{fn_name}(#{args}) do
              client
              |> #{call}#{decode}
            end
        """
      else
        """
            def #{fn_name}(#{args}) do
              with {:ok, validated} <- validate_#{fn_name}(params) do
                client
                |> #{call}#{decode}
              end
            end
        """
      end

    """
    #{fields_attr}  @doc \"\"\"
    #{indent(doc, 2)}
    \"\"\"
    @spec #{fn_name}(#{spec_args}) :: #{return_type}
    #{String.trim_leading(body, "    ")}

    #{String.trim_trailing(validate)}#{decode_fn}
    """
  end

  defp endpoint_params(main) do
    case main.parameters && Parser.parse_schema_node(main.parameters) do
      {:ok, %{kind: :params, properties: properties, required: required}} ->
        {main.parameters, Enum.sort(properties), required}

      _ ->
        {nil, [], []}
    end
  end

  defp endpoint_params_doc(nil), do: nil

  defp endpoint_params_doc(params) do
    required = MapSet.new(params["required"] || [])

    items =
      params["properties"]
      |> Enum.sort()
      |> Enum.map_join("\n", fn {name, prop} ->
        req = if name in required, do: "required", else: "optional"

        "- `#{name}` (#{prop["type"]}, #{req})#{prop["description"] && ": " <> prop["description"]}"
      end)

    """
    ## Parameters

    #{items}
    """
  end

  # The output schema ref, when it resolves to a generated module. Most list
  # endpoints return view schemas that are not generated; those responses
  # come back as raw maps.
  defp output_module(main, ctx) do
    case main.output do
      %{"schema" => %{"type" => "ref", "ref" => ref}} ->
        key = resolve_ref(ref, "")
        ctx.modules[key]

      _ ->
        nil
    end
  end

  # --- Naming --------------------------------------------------------------------

  # app.bsky.feed.post => Exosphere.Bsky.Feed.Post; com.atproto.repo.strongRef
  # => Exosphere.ATProto.Repo.StrongRef; community.lexicon.interaction.like =>
  # Exosphere.Community.Interaction.Like; other authorities keep all segments.
  defp main_module(nsid) do
    case Enum.find(@namespace_rules, fn {prefix, _base} -> String.starts_with?(nsid, prefix) end) do
      {prefix, base} ->
        rest =
          nsid
          |> String.trim_leading(prefix)
          |> String.split(".")
          |> Enum.map(&Macro.camelize/1)

        Module.concat(base ++ rest)

      nil ->
        nsid
        |> String.split(".")
        |> Enum.map(&Macro.camelize/1)
        |> then(&Module.concat([Exosphere | &1]))
    end
  end

  defp def_module(nsid, def_name),
    do: Module.concat(main_module(nsid), Macro.camelize(def_name))

  defp module_spec(lexicon, def_name) do
    node = lexicon.defs[def_name]

    module =
      if def_name == "main", do: main_module(lexicon.id), else: def_module(lexicon.id, def_name)

    %{
      module: module,
      path: module_path(module),
      nsid: lexicon.id,
      def_name: if(def_name == "main", do: nil, else: def_name),
      node: node,
      lexicon: lexicon
    }
  end

  # Exosphere.Bsky.Feed.Post => "bsky/feed/post.ex" (relative to lib/exosphere).
  # ATProto is written as "atproto" to match the hand-written directory.
  defp module_path(module) do
    parts =
      module
      |> Module.split()
      |> Enum.drop(1)
      |> Enum.map(&Macro.underscore/1)

    parts =
      case parts do
        ["at_proto" | rest] -> ["atproto" | rest]
        other -> other
      end

    parts
    |> Path.join()
    |> then(&"#{&1}.ex")
  end

  # Resolve a ref string ("#def", "nsid", "nsid#def") to `{nsid, def_name}`.
  defp resolve_ref("#" <> def_name, owner_nsid), do: {owner_nsid, def_name}

  defp resolve_ref(ref, _owner_nsid) do
    case String.split(ref, "#", parts: 2) do
      [nsid] -> {nsid, "main"}
      [nsid, def_name] -> {nsid, def_name}
    end
  end

  # --- Ref resolution helpers ------------------------------------------------------

  defp ref_module(%{kind: :ref} = node, ctx) do
    case resolve_ref(node.ref, ctx.nsid) do
      {nsid, def_name} -> Map.get(ctx.modules, {nsid, def_name})
    end
  end

  defp union_variants(%{kind: :union, refs: refs}, ctx) do
    Enum.flat_map(refs, fn ref ->
      {nsid, def_name} = resolve_ref(ref, ctx.nsid)

      case Map.fetch(ctx.modules, {nsid, def_name}) do
        {:ok, module} ->
          type_id = if def_name == "main", do: nsid, else: "#{nsid}##{def_name}"
          [{type_id, module}]

        :error ->
          []
      end
    end)
  end

  defp variants_attr(name), do: "variants_#{field_atom(name)}"

  # --- Rendering -------------------------------------------------------------------

  defp render(%{node: %{kind: :endpoints}} = spec, ctx) do
    functions =
      Enum.map_join(spec.endpoints, "\n\n", fn {nsid, lexicon} ->
        render_endpoint(nsid, lexicon, ctx)
      end)

    [
      @header,
      "defmodule #{inspect(spec.module)} do",
      endpoint_moduledoc(spec),
      "  alias Exosphere.ATProto.XRPC.Client",
      "  alias Exosphere.Bsky.Runtime",
      functions,
      "end"
    ]
    |> Enum.join("\n\n")
    |> then(&(&1 <> "\n"))
  end

  defp render(spec, ctx) do
    %{module: module, node: node} = spec
    ctx = Map.put(ctx, :nsid, spec.nsid)
    ctx = Map.put(ctx, :type_id, (spec.def_name && "#{spec.nsid}##{spec.def_name}") || spec.nsid)
    ctx = Map.put(ctx, :is_record, node.kind == :record)

    object = if node.kind == :record, do: node.record, else: node
    fields = Enum.sort(object.properties)
    req = %{required: object.required, nullable: object.nullable || []}

    sections = [
      @header,
      "defmodule #{inspect(module)} do",
      moduledoc(spec, object, fields),
      attrs(fields, ctx),
      struct_def(fields, req),
      "  @type t :: %__MODULE__{#{type_pairs(fields, req, ctx)}}",
      # Emitted with explicit key ordering: inspecting a map literal would
      # order atoms by term order, which varies with atom creation order
      # in the generating VM.
      "  @fields %{#{fields_map_literal(fields)}}",
      type_id_fn(),
      new(fields, req, ctx),
      new_bang(),
      to_map(fields, ctx),
      from_map(),
      helpers(fields, ctx),
      "end"
    ]

    sections
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
    |> then(&(&1 <> "\n"))
  end

  defp fields_map_literal(fields) do
    fields
    |> Enum.map(fn {n, _} -> {field_atom(n), n} end)
    |> Enum.sort_by(fn {_atom, wire} -> wire end)
    |> Enum.map_join(", ", fn {atom, wire} -> "#{atom}: #{inspect(wire)}" end)
  end

  defp moduledoc(spec, object, fields) do
    title =
      if spec.node.kind == :record,
        do: "Record schema `#{spec.lexicon.id}`.",
        else: "Object schema `#{spec.nsid}#{spec.def_name && "##" <> spec.def_name}`."

    doc =
      [spec.lexicon.description, object.description, title]
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join("\n\n")

    field_list =
      if fields == [] do
        ""
      else
        items =
          Enum.map_join(fields, "\n", fn {name, node} ->
            "- `#{field_atom(name)}`: #{node_description(node)}"
          end)

        "\n\n## Fields\n\n#{items}"
      end

    """
      @moduledoc \"\"\"
    #{indent(doc, 2)}
    #{String.trim_trailing(field_list)}
      \"\"\"
    """
  end

  defp node_description(%{description: description}) when is_binary(description), do: description
  defp node_description(node), do: kind_doc(node)

  defp kind_doc(%{kind: :string, format: format}) when not is_nil(format),
    do: "string, format `#{format}`"

  defp kind_doc(%{kind: :string}), do: "string"
  defp kind_doc(%{kind: :token}), do: "token"
  defp kind_doc(%{kind: :integer}), do: "integer"
  defp kind_doc(%{kind: :boolean}), do: "boolean"
  defp kind_doc(%{kind: :array}), do: "array"
  defp kind_doc(%{kind: :ref, ref: ref}), do: "ref `#{ref}`"
  defp kind_doc(%{kind: :union}), do: "union"
  defp kind_doc(%{kind: :blob}), do: "blob"
  defp kind_doc(%{kind: :cid_link}), do: "CID link"
  defp kind_doc(%{kind: :bytes}), do: "bytes"
  defp kind_doc(%{kind: :unknown}), do: "any"

  defp attrs(fields, ctx) do
    union_attrs =
      fields
      |> Enum.flat_map(fn {name, node} ->
        case node do
          %{kind: :union} ->
            [{variants_attr(name), union_variants(node, ctx)}]

          %{kind: :array, items: %{kind: :union}} ->
            [{variants_attr(name), union_variants(node.items, ctx)}]

          _ ->
            []
        end
      end)
      |> Enum.map(fn {attr, variants} -> "@#{attr} #{inspect(variants)}" end)

    Enum.join(
      ["alias Exosphere.Bsky.Runtime", "@type_id #{inspect(ctx.type_id)}" | union_attrs],
      "\n"
    )
  end

  defp struct_def(fields, %{required: required}) do
    enforce =
      fields
      |> Enum.filter(fn {name, _} -> name in required end)
      |> Enum.map(fn {name, _} -> field_atom(name) end)

    defaults = for {name, _} <- fields, do: {field_atom(name), nil}

    "@enforce_keys #{inspect(enforce)}\n  defstruct #{inspect(defaults ++ [extra: %{}])}"
  end

  defp type_pairs(fields, %{required: required, nullable: nullable}, ctx) do
    for {name, node} <- fields do
      # Nullable fields accept nil even when required
      optional =
        if name in required and name not in nullable,
          do: "",
          else: " | nil"

      "#{field_atom(name)}: #{field_type(node, ctx)}#{optional}"
    end
    |> Enum.join(", ")
  end

  defp field_type(%{kind: :string}, _ctx), do: "String.t()"
  defp field_type(%{kind: :token}, _ctx), do: "String.t()"
  defp field_type(%{kind: :integer}, _ctx), do: "integer()"
  defp field_type(%{kind: :boolean}, _ctx), do: "boolean()"
  defp field_type(%{kind: :blob}, _ctx), do: "term()"
  defp field_type(%{kind: :cid_link}, _ctx), do: "term()"
  defp field_type(%{kind: :bytes}, _ctx), do: "binary()"
  defp field_type(%{kind: :unknown}, _ctx), do: "term()"

  defp field_type(%{kind: :array, items: items}, ctx),
    do: "[#{field_type(items, ctx)}]"

  defp field_type(%{kind: :ref} = node, ctx) do
    case ref_module(node, ctx) do
      nil -> "term()"
      module -> "#{inspect(module)}.t()"
    end
  end

  defp field_type(%{kind: :union} = node, ctx) do
    # Unions are open-world: unknown $types stay as raw maps
    node
    |> union_variants(ctx)
    |> Enum.map(fn {_type_id, module} -> "#{inspect(module)}.t()" end)
    |> Kernel.++(["map()"])
    |> Enum.join(" | ")
  end

  defp type_id_fn do
    """
    @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
    @spec type_id() :: String.t()
    def type_id, do: @type_id
    """
  end

  defp new(fields, req, ctx) do
    bindings =
      fields
      |> Enum.with_index(1)
      |> Enum.map(fn {{name, node}, i} ->
        "      {#{field_var(name)}, e#{i}} = #{getter(name, node, req, ctx)}"
      end)

    n = length(fields)

    error_list =
      if n == 0, do: "[]", else: Enum.map_join(1..n, " ++ ", &"e#{&1}")

    assigns =
      case fields do
        [] ->
          ""

        fields ->
          Enum.map_join(fields, ", ", fn {name, _} ->
            "#{field_atom(name)}: #{field_var(name)}"
          end) <> ", "
      end

    """
    @doc \"\"\"
    Build and validate from a map of attrs (atom or wire string keys).

    Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
    \"\"\"
    @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
    def new(attrs) when is_map(attrs) do
      {#{if(fields == [], do: "_attrs", else: "attrs")}, extra} = Runtime.atomize(attrs, @fields)

    #{Enum.join(bindings, "\n")}

      errors = #{error_list}

      if errors == [] do
        {:ok, %__MODULE__{#{assigns}extra: extra}}
      else
        {:error, errors}
      end
    end

    def new(_), do: {:error, [{"", "expected a map"}]}
    """
  end

  @typep field_req :: %{required: [String.t()], nullable: [String.t()]}

  @spec getter(String.t(), Parser.schema_node(), field_req(), map()) :: String.t()
  defp getter(name, node, %{required: _, nullable: _} = req, ctx) do
    key = field_atom(name)
    path = inspect(name)
    opts = get_opts(node, req, name)

    case node.kind do
      :union ->
        "Runtime.get_union(attrs, :#{key}, #{path}, #{opts}, @#{variants_attr(name)}#{union_closed_arg(node)})"

      :array ->
        "Runtime.get_array(attrs, :#{key}, #{path}, #{opts}, #{array_item_fn(name, node, ctx)})"

      :ref ->
        case ref_module(node, ctx) do
          nil -> "Runtime.get_any(attrs, :#{key}, #{path}, #{opts})"
          module -> "Runtime.get_ref(attrs, :#{key}, #{path}, #{opts}, #{inspect(module)})"
        end

      :string ->
        "Runtime.get_string(attrs, :#{key}, #{path}, #{opts})"

      :token ->
        "Runtime.get_string(attrs, :#{key}, #{path}, #{opts})"

      :integer ->
        "Runtime.get_integer(attrs, :#{key}, #{path}, #{opts})"

      :boolean ->
        "Runtime.get_boolean(attrs, :#{key}, #{path}, #{opts})"

      _ ->
        "Runtime.get_any(attrs, :#{key}, #{path}, #{opts})"
    end
  end

  defp array_item_fn(name, %{kind: :array, items: items}, ctx) do
    case items do
      %{kind: :string} ->
        "fn v, path -> Runtime.item_string(v, path, #{item_string_opts(items)}) end"

      %{kind: :ref} = ref ->
        case ref_module(ref, ctx) do
          nil -> "fn v, _path -> {:ok, v} end"
          module -> "fn v, path -> Runtime.item_ref(v, path, #{inspect(module)}) end"
        end

      %{kind: :union} ->
        "fn v, path -> Runtime.item_union(v, path, @#{variants_attr(name)}#{union_closed_arg(items)}) end"

      _ ->
        "fn v, _path -> {:ok, v} end"
    end
  end

  defp item_string_opts(%{kind: :string} = node) do
    node |> string_opts() |> inspect()
  end

  @spec get_opts(Parser.schema_node(), field_req(), String.t()) :: String.t()

  defp get_opts(node, %{required: required, nullable: nullable}, name) do
    opts =
      case node.kind do
        :string -> string_opts(node)
        :token -> string_opts(node)
        :integer -> integer_opts(node)
        :boolean -> const_opts(node)
        :array -> array_opts(node)
        _ -> []
      end

    opts
    |> maybe_req(name in required)
    |> maybe_nullable(name in nullable)
    |> render_opts()
  end

  # Render keyword opts manually so large integers get underscores
  # (e.g. maxLength 10000 -> 10_000), keeping generated files lint-clean.
  defp render_opts([]), do: "[]"

  defp render_opts(opts) do
    "[" <>
      Enum.map_join(opts, ", ", fn
        {key, value} -> "#{key}: #{opt_value(value)}"
      end) <> "]"
  end

  defp opt_value(value) when is_integer(value) and abs(value) > 9999,
    do: value |> Integer.to_string() |> underscore()

  defp opt_value(value), do: inspect(value)

  defp underscore(string) do
    string
    |> String.graphemes()
    |> Enum.reverse()
    |> Enum.chunk_every(3)
    |> Enum.map(&Enum.reverse/1)
    |> Enum.reverse()
    |> Enum.map_join("_", &Enum.join/1)
  end

  defp maybe_req(opts, true), do: [{:required, true} | opts]
  defp maybe_req(opts, false), do: opts

  defp maybe_nullable(opts, true), do: [{:nullable, true} | opts]
  defp maybe_nullable(opts, false), do: opts

  # Closed unions pass an extra positional arg to the Runtime validators
  defp union_closed_arg(%{closed: true}), do: ", true"
  defp union_closed_arg(_), do: ""

  defp string_opts(%{kind: :token} = node) do
    []
    |> opt(node.min_length, :min_length)
    |> opt(node.max_length, :max_length)
    |> opt(node.max_graphemes, :max_graphemes)
  end

  defp string_opts(node) do
    []
    |> opt(node.min_length, :min_length)
    |> opt(node.max_length, :max_length)
    |> opt(node.max_graphemes, :max_graphemes)
    |> opt(node.format, :format)
    |> opt(node.enum, :enum)
    |> opt(node.const, :const)
    |> opt(node.default, :default)
  end

  defp integer_opts(node) do
    []
    |> opt(node.minimum, :minimum)
    |> opt(node.maximum, :maximum)
    |> opt(node.const, :const)
    |> opt(node.default, :default)
  end

  defp const_opts(node) do
    []
    |> opt(node.const, :const)
    |> opt(node.default, :default)
  end

  defp array_opts(node) do
    []
    |> opt(node.min_length, :min_length)
    |> opt(node.max_length, :max_length)
  end

  defp opt(acc, nil, _key), do: acc
  defp opt(acc, value, key), do: acc ++ [{key, value}]

  defp new_bang do
    """
    @doc "Build and validate, raising ArgumentError on error."
    @spec new!(map()) :: t()
    def new!(attrs) do
      case new(attrs) do
        {:ok, struct} -> struct
        {:error, errors} -> raise ArgumentError, "invalid \#{@type_id}: \#{inspect(errors)}"
      end
    end
    """
  end

  defp to_map(fields, ctx) do
    puts =
      for {name, node} <- fields do
        encoder = encoder_call(name, node, ctx)

        "      |> Runtime.put_field(#{inspect(name)}, struct.#{field_atom(name)}#{encoder})"
      end

    type_put =
      if ctx.is_record do
        "\n      |> Map.put(\"$type\", @type_id)"
      else
        ""
      end

    """
    @doc "Encode to the wire-format map.#{if ctx.is_record, do: " Record schemas include \\\"$type\\\".", else: ""}"
    @spec to_map(t()) :: map()
    def to_map(%__MODULE__{} = struct) do
      %{}
    #{Enum.join(puts, "\n")}
      |> Map.merge(struct.extra)#{type_put}
    end
    """
  end

  defp encoder_call(name, node, ctx) do
    case node.kind do
      :union ->
        ", &#{encoder_fn(name)}/1"

      :ref ->
        if ref_module(node, ctx), do: ", &#{encoder_fn(name)}/1", else: ""

      :array ->
        case node.items do
          %{kind: :ref} = ref -> if ref_module(ref, ctx), do: ", &#{encoder_fn(name)}/1", else: ""
          %{kind: :union} -> ", &#{encoder_fn(name)}/1"
          _ -> ""
        end

      _ ->
        ""
    end
  end

  defp from_map do
    """
    @doc "Decode a wire-format map. Delegates to new/1."
    @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
    def from_map(map) when is_map(map), do: new(map)
    def from_map(_), do: {:error, [{"", "expected a map"}]}
    """
  end

  defp helpers(fields, ctx) do
    extra =
      fields
      |> Enum.flat_map(fn {name, node} -> field_helpers(name, node, ctx) end)

    base =
      if Enum.any?(extra, &String.contains?(&1, "encode_ref(")) do
        [
          "defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)",
          "defp encode_ref(v, _module) when is_map(v), do: v"
        ]
      else
        []
      end

    Enum.join(base ++ extra, "\n\n")
  end

  defp field_helpers(name, node, ctx) do
    case node.kind do
      :union ->
        union_clauses(encoder_fn(name), union_variants(node, ctx))

      :ref ->
        case ref_module(node, ctx) do
          nil -> []
          module -> ["defp #{encoder_fn(name)}(v), do: encode_ref(v, #{inspect(module)})"]
        end

      :array ->
        case node.items do
          %{kind: :ref} = ref ->
            case ref_module(ref, ctx) do
              nil ->
                []

              module ->
                [
                  "defp #{encoder_fn(name)}(values), do: Enum.map(values, &#{item_fn(name)}/1)",
                  "defp #{item_fn(name)}(v), do: encode_ref(v, #{inspect(module)})"
                ]
            end

          %{kind: :union} ->
            [
              "defp #{encoder_fn(name)}(values), do: Enum.map(values, &#{item_fn(name)}/1)"
              | union_clauses(item_fn(name), union_variants(node.items, ctx))
            ]

          _ ->
            []
        end

      _ ->
        []
    end
  end

  defp union_clauses(fn_name, variants) do
    clauses =
      Enum.map(variants, fn {type_id, module} ->
        "defp #{fn_name}(v) when is_struct(v, #{inspect(module)}), do: Map.put(#{inspect(module)}.to_map(v), \"$type\", #{inspect(type_id)})"
      end)

    clauses ++ ["defp #{fn_name}(v) when is_map(v), do: v"]
  end

  defp encoder_fn(name), do: "encode_#{field_atom(name)}"
  defp item_fn(name), do: "encode_#{field_atom(name)}_item"

  # --- Utilities ---------------------------------------------------------------------

  defp field_atom(name), do: name |> Macro.underscore() |> String.to_atom()

  # Field binding vars get an f_ prefix so wire names like `end` don't
  # collide with Elixir keywords.
  defp field_var(name), do: "f_#{field_atom(name)}"

  defp indent(text, spaces) do
    prefix = String.duplicate(" ", spaces)

    text
    |> String.split("\n")
    |> Enum.map_join("\n", fn line -> if String.trim(line) == "", do: "", else: prefix <> line end)
  end
end
