defmodule Exosphere.Lexicon.Generator do
  @moduledoc """
  Generates Elixir record modules from parsed lexicon IR.

  For each `app.bsky.*` lexicon, generates one module for its `main` def
  plus nested modules for internal `#defs` reachable from it:

  - `app.bsky.feed.post` (record) → `Exosphere.Bsky.Feed.Post`
  - `app.bsky.richtext.facet#byteSlice` → `Exosphere.Bsky.Richtext.Facet.ByteSlice`

  Each generated module has:

  - a struct with snake_cased fields plus an `extra` map for unknown keys
  - `new/1` — build and validate from atom- or string-keyed attrs,
    returning `{:ok, struct} | {:error, [{path, message}]}`
  - `to_map/1` — encode to wire format (record mains inject `"$type"`;
    union encoders inject `"$type"` into their variants)
  - `from_map/1` — decode a wire map (delegates to `new/1`)
  - `type_id/0` — the def's NSID (`"app.bsky.feed.post"`, `"…#replyRef"`, or nil)

  Cross-lexicon refs resolve when the target def is itself being generated;
  unresolved refs degrade to pass-through `term()` values.
  """

  alias Exosphere.Lexicon.Parser

  @header """
  # Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
  # Regenerate with: mix exosphere.gen.bsky
  """

  @type spec :: %{
          module: module(),
          path: String.t(),
          nsid: String.t(),
          def_name: String.t() | nil,
          node: Parser.schema_node(),
          lexicon: Parser.lexicon()
        }

  @doc """
  Generate all modules for `lexicons` (as from `Parser.parse_dir/1`).

  Returns specs (module, path relative to `lib/exosphere/bsky`, formatted
  code), ordered parents-first.
  """
  @spec generate(%{String.t() => Parser.lexicon()}) :: [
          %{module: module(), path: String.t(), code: String.t()}
        ]
  def generate(lexicons) do
    specs =
      lexicons
      |> Enum.filter(fn {nsid, _} -> String.starts_with?(nsid, "app.bsky.") end)
      |> Enum.sort()
      |> Enum.flat_map(fn {_nsid, lexicon} ->
        main = lexicon.defs["main"]

        [{"main", main} | reachable_defs(lexicon, main)]
        |> Enum.map(&module_spec(lexicon, &1))
      end)

    modules = Map.new(specs, &{{&1.nsid, &1.def_name || "main"}, &1.module})

    ctx = %{modules: modules}

    specs
    |> Enum.sort_by(fn spec -> {spec.module |> Module.split() |> length(), spec.module} end)
    |> Enum.map(fn spec ->
      %{module: spec.module, path: spec.path, code: format(render(spec, ctx))}
    end)
  end

  @doc """
  Write generated specs under `lib_dir` (default `lib/exosphere/bsky`),
  creating directories as needed. Returns the paths written.
  """
  @spec write!([%{module: module(), path: String.t(), code: String.t()}], Path.t()) :: [Path.t()]
  def write!(specs, lib_dir \\ "lib/exosphere/bsky") do
    Enum.map(specs, fn %{path: rel, code: code} ->
      path = Path.join(lib_dir, rel)
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, code)
      path
    end)
  end

  defp format(code) do
    code |> Code.format_string!() |> IO.iodata_to_binary()
  rescue
    _error ->
      reraise ArgumentError,
              [message: "generator produced unparseable code:\n\n#{code}"],
              __STACKTRACE__
  end

  # --- Reachability -------------------------------------------------------------

  # Collect internal defs of `lexicon` reachable from `node`, depth-first,
  # not revisiting (guards against ref cycles).
  defp reachable_defs(lexicon, node), do: reachable_defs(lexicon, node, [])

  defp reachable_defs(lexicon, node, seen) do
    case node do
      %{kind: :ref, ref: "#" <> def_name} ->
        if def_name in seen or not Map.has_key?(lexicon.defs, def_name) do
          []
        else
          child = lexicon.defs[def_name]
          [{def_name, child} | reachable_defs(lexicon, child, [def_name | seen])]
        end

      %{kind: :array, items: items} ->
        reachable_defs(lexicon, items, seen)

      %{kind: :union, refs: refs} ->
        Enum.flat_map(refs, fn
          "#" <> _ = ref -> reachable_defs(lexicon, %{kind: :ref, ref: ref}, seen)
          _ -> []
        end)

      %{kind: :object, properties: props} ->
        Enum.flat_map(props, fn {_name, prop} -> reachable_defs(lexicon, prop, seen) end)

      %{kind: :record, record: record} ->
        reachable_defs(lexicon, record, seen)

      _ ->
        []
    end
  end

  # --- Naming --------------------------------------------------------------------

  # app.bsky.feed.post => Exosphere.Bsky.Feed.Post (the app.bsky prefix is
  # dropped; only app.bsky.* lexicons are generated)
  defp main_module(nsid) do
    nsid
    |> String.split(".")
    |> Enum.drop(2)
    |> Enum.map(&Macro.camelize/1)
    |> then(&Module.concat([Exosphere, Bsky | &1]))
  end

  defp def_module(nsid, def_name),
    do: Module.concat(main_module(nsid), Macro.camelize(def_name))

  defp module_spec(lexicon, {def_name, node}) do
    module =
      if def_name == "main", do: main_module(lexicon.id), else: def_module(lexicon.id, def_name)

    %{
      module: module,
      path: module_path(module),
      nsid: lexicon.id,
      def_name: if(def_name == "main", do: nil, else: def_name),
      node: node,
      lexicon: lexicon
    }
  end

  # Exosphere.Bsky.Feed.Post => "feed/post.ex" (relative to lib/exosphere/bsky)
  defp module_path(module) do
    module
    |> Module.split()
    |> Enum.drop(2)
    |> Enum.map(&Macro.underscore/1)
    |> Path.join()
    |> then(&"#{&1}.ex")
  end

  # Resolve a ref string ("#def", "nsid", "nsid#def") to `{nsid, def_name}`.
  defp resolve_ref("#" <> def_name, owner_nsid), do: {owner_nsid, def_name}

  defp resolve_ref(ref, _owner_nsid) do
    case String.split(ref, "#", parts: 2) do
      [nsid] -> {nsid, "main"}
      [nsid, def_name] -> {nsid, def_name}
    end
  end

  # --- Ref resolution helpers ------------------------------------------------------

  defp ref_module(%{kind: :ref} = node, ctx) do
    case resolve_ref(node.ref, ctx.nsid) do
      {nsid, def_name} -> Map.get(ctx.modules, {nsid, def_name})
    end
  end

  defp union_variants(%{kind: :union, refs: refs}, ctx) do
    Enum.flat_map(refs, fn ref ->
      {nsid, def_name} = resolve_ref(ref, ctx.nsid)

      case Map.fetch(ctx.modules, {nsid, def_name}) do
        {:ok, module} ->
          type_id = if def_name == "main", do: nsid, else: "#{nsid}##{def_name}"
          [{type_id, module}]

        :error ->
          []
      end
    end)
  end

  defp variants_attr(name), do: "variants_#{field_atom(name)}"

  # --- Rendering -------------------------------------------------------------------

  defp render(spec, ctx) do
    %{module: module, node: node} = spec
    ctx = Map.put(ctx, :nsid, spec.nsid)
    ctx = Map.put(ctx, :type_id, spec.def_name && "#{spec.nsid}##{spec.def_name}" || spec.nsid)
    ctx = Map.put(ctx, :is_record, node.kind == :record)

    object = if node.kind == :record, do: node.record, else: node
    fields = Enum.sort(object.properties)
    required = MapSet.new(object.required)

    sections = [
      @header,
      "defmodule #{inspect(module)} do",
      moduledoc(spec, object, fields),
      attrs(fields, ctx),
      struct_def(fields, required),
      "  @type t :: %__MODULE__{#{type_pairs(fields, required, ctx)}}",
      # Emitted with explicit key ordering: inspecting a map literal would
      # order atoms by term order, which varies with atom creation order
      # in the generating VM.
      "  @fields %{#{fields_map_literal(fields)}}",
      type_id_fn(),
      new(fields, required, ctx),
      new_bang(),
      to_map(fields, ctx),
      from_map(),
      helpers(fields, ctx),
      "end"
    ]

    sections
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
    |> then(&(&1 <> "\n"))
  end

  defp fields_map_literal(fields) do
    fields
    |> Enum.map(fn {n, _} -> {field_atom(n), n} end)
    |> Enum.sort_by(fn {_atom, wire} -> wire end)
    |> Enum.map_join(", ", fn {atom, wire} -> "#{atom}: #{inspect(wire)}" end)
  end

  defp moduledoc(spec, object, fields) do
    title =
      if spec.node.kind == :record,
        do: "Record schema `#{spec.lexicon.id}`.",
        else: "Object schema `#{spec.nsid}#{spec.def_name && "##" <> spec.def_name}`."

    doc =
      [spec.lexicon.description, object.description, title]
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join("\n\n")

    field_list =
      if fields == [] do
        ""
      else
        items =
          Enum.map_join(fields, "\n", fn {name, node} ->
            "- `#{field_atom(name)}`: #{node_description(node)}"
          end)

        "\n\n## Fields\n\n#{items}"
      end

    """
      @moduledoc \"\"\"
    #{indent(doc, 2)}
    #{String.trim_trailing(field_list)}
      \"\"\"
    """
  end

  defp node_description(%{description: description}) when is_binary(description), do: description
  defp node_description(node), do: kind_doc(node)

  defp kind_doc(%{kind: :string, format: format}) when not is_nil(format), do: "string, format `#{format}`"
  defp kind_doc(%{kind: :string}), do: "string"
  defp kind_doc(%{kind: :integer}), do: "integer"
  defp kind_doc(%{kind: :boolean}), do: "boolean"
  defp kind_doc(%{kind: :array}), do: "array"
  defp kind_doc(%{kind: :ref, ref: ref}), do: "ref `#{ref}`"
  defp kind_doc(%{kind: :union}), do: "union"
  defp kind_doc(%{kind: :blob}), do: "blob"
  defp kind_doc(%{kind: :cid_link}), do: "CID link"
  defp kind_doc(%{kind: :bytes}), do: "bytes"
  defp kind_doc(%{kind: :unknown}), do: "any"

  defp attrs(fields, ctx) do
    union_attrs =
      fields
      |> Enum.flat_map(fn {name, node} ->
        case node do
          %{kind: :union} -> [{variants_attr(name), union_variants(node, ctx)}]
          %{kind: :array, items: %{kind: :union}} -> [{variants_attr(name), union_variants(node.items, ctx)}]
          _ -> []
        end
      end)
      |> Enum.map(fn {attr, variants} -> "@#{attr} #{inspect(variants)}" end)

    Enum.join(["alias Exosphere.Bsky.Runtime", "@type_id #{inspect(ctx.type_id)}" | union_attrs], "\n")
  end

  defp struct_def(fields, required) do
    enforce =
      fields
      |> Enum.filter(fn {name, _} -> MapSet.member?(required, name) end)
      |> Enum.map(fn {name, _} -> field_atom(name) end)

    defaults = for {name, _} <- fields, do: {field_atom(name), nil}

    "@enforce_keys #{inspect(enforce)}\n  defstruct #{inspect(defaults ++ [extra: %{}])}"
  end

  defp type_pairs(fields, required, ctx) do
    for {name, node} <- fields do
      optional = if MapSet.member?(required, name), do: "", else: " | nil"
      "#{field_atom(name)}: #{field_type(node, ctx)}#{optional}"
    end
    |> Enum.join(", ")
  end

  defp field_type(%{kind: :string}, _ctx), do: "String.t()"
  defp field_type(%{kind: :integer}, _ctx), do: "integer()"
  defp field_type(%{kind: :boolean}, _ctx), do: "boolean()"
  defp field_type(%{kind: :blob}, _ctx), do: "term()"
  defp field_type(%{kind: :cid_link}, _ctx), do: "term()"
  defp field_type(%{kind: :bytes}, _ctx), do: "binary()"
  defp field_type(%{kind: :unknown}, _ctx), do: "term()"

  defp field_type(%{kind: :array, items: items}, ctx),
    do: "[#{field_type(items, ctx)}]"

  defp field_type(%{kind: :ref} = node, ctx) do
    case ref_module(node, ctx) do
      nil -> "term()"
      module -> "#{inspect(module)}.t()"
    end
  end

  defp field_type(%{kind: :union} = node, ctx) do
    # Unions are open-world: unknown $types stay as raw maps
    node
    |> union_variants(ctx)
    |> Enum.map(fn {_type_id, module} -> "#{inspect(module)}.t()" end)
    |> Kernel.++(["map()"])
    |> Enum.join(" | ")
  end

  defp type_id_fn do
    """
    @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
    @spec type_id() :: String.t()
    def type_id, do: @type_id
    """
  end

  defp new(fields, required, ctx) do
    bindings =
      fields
      |> Enum.with_index(1)
      |> Enum.map(fn {{name, node}, i} ->
        "      {#{field_var(name)}, e#{i}} = #{getter(name, node, required, ctx)}"
      end)

    n = length(fields)

    error_list =
      if n == 0, do: "[]", else: Enum.map_join(1..n, " ++ ", &"e#{&1}")

    assigns =
      Enum.map_join(fields, ", ", fn {name, _} -> "#{field_atom(name)}: #{field_var(name)}" end)

    """
    @doc \"\"\"
    Build and validate from a map of attrs (atom or wire string keys).

    Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
    \"\"\"
    @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
    def new(attrs) when is_map(attrs) do
      {attrs, extra} = Runtime.atomize(attrs, @fields)

    #{Enum.join(bindings, "\n")}

      errors = #{error_list}

      if errors == [] do
        {:ok, %__MODULE__{#{assigns}, extra: extra}}
      else
        {:error, errors}
      end
    end

    def new(_), do: {:error, [{"", "expected a map"}]}
    """
  end

  defp getter(name, node, required, ctx) do
    key = field_atom(name)
    path = inspect(name)
    opts = get_opts(node, required, name)

    case node.kind do
      :union ->
        "Runtime.get_union(attrs, :#{key}, #{path}, #{opts}, @#{variants_attr(name)})"

      :array ->
        "Runtime.get_array(attrs, :#{key}, #{path}, #{opts}, #{array_item_fn(name, node, ctx)})"

      :ref ->
        case ref_module(node, ctx) do
          nil -> "Runtime.get_any(attrs, :#{key}, #{path}, #{opts})"
          module -> "Runtime.get_ref(attrs, :#{key}, #{path}, #{opts}, #{inspect(module)})"
        end

      :string ->
        "Runtime.get_string(attrs, :#{key}, #{path}, #{opts})"

      :integer ->
        "Runtime.get_integer(attrs, :#{key}, #{path}, #{opts})"

      :boolean ->
        "Runtime.get_boolean(attrs, :#{key}, #{path}, #{opts})"

      _ ->
        "Runtime.get_any(attrs, :#{key}, #{path}, #{opts})"
    end
  end

  defp array_item_fn(name, %{kind: :array, items: items}, ctx) do
    case items do
      %{kind: :string} ->
        "fn v, path -> Runtime.item_string(v, path, #{item_string_opts(items)}) end"

      %{kind: :ref} = ref ->
        case ref_module(ref, ctx) do
          nil -> "fn v, _path -> {:ok, v} end"
          module -> "fn v, path -> Runtime.item_ref(v, path, #{inspect(module)}) end"
        end

      %{kind: :union} ->
        "fn v, path -> Runtime.item_union(v, path, @#{variants_attr(name)}) end"

      _ ->
        "fn v, _path -> {:ok, v} end"
    end
  end

  defp item_string_opts(%{kind: :string} = node) do
    node |> string_opts() |> inspect()
  end

  defp get_opts(node, required, name) do
    opts =
      case node.kind do
        :string -> string_opts(node)
        :integer -> integer_opts(node)
        :boolean -> const_opts(node)
        :array -> array_opts(node)
        _ -> []
      end

    if MapSet.member?(required, name), do: inspect([{:required, true} | opts]), else: inspect(opts)
  end

  defp string_opts(node) do
    []
    |> opt(node.min_length, :min_length)
    |> opt(node.max_length, :max_length)
    |> opt(node.max_graphemes, :max_graphemes)
    |> opt(node.format, :format)
    |> opt(node.enum, :enum)
    |> opt(node.const, :const)
    |> opt(node.default, :default)
  end

  defp integer_opts(node) do
    []
    |> opt(node.minimum, :minimum)
    |> opt(node.maximum, :maximum)
    |> opt(node.const, :const)
    |> opt(node.default, :default)
  end

  defp const_opts(node) do
    []
    |> opt(node.const, :const)
    |> opt(node.default, :default)
  end

  defp array_opts(node) do
    []
    |> opt(node.min_length, :min_length)
    |> opt(node.max_length, :max_length)
  end

  defp opt(acc, nil, _key), do: acc
  defp opt(acc, value, key), do: acc ++ [{key, value}]

  defp new_bang do
    """
    @doc "Build and validate, raising ArgumentError on error."
    @spec new!(map()) :: t()
    def new!(attrs) do
      case new(attrs) do
        {:ok, struct} -> struct
        {:error, errors} -> raise ArgumentError, "invalid \#{@type_id}: \#{inspect(errors)}"
      end
    end
    """
  end

  defp to_map(fields, ctx) do
    puts =
      for {name, node} <- fields do
        encoder = encoder_call(name, node, ctx)

        "      |> Runtime.put_field(#{inspect(name)}, struct.#{field_atom(name)}#{encoder})"
      end

    type_put =
      if ctx.is_record do
        "\n      |> Map.put(\"$type\", @type_id)"
      else
        ""
      end

    """
    @doc "Encode to the wire-format map.#{if ctx.is_record, do: " Record schemas include \\\"$type\\\".", else: ""}"
    @spec to_map(t()) :: map()
    def to_map(%__MODULE__{} = struct) do
      %{}
    #{Enum.join(puts, "\n")}
      |> Map.merge(struct.extra)#{type_put}
    end
    """
  end

  defp encoder_call(name, node, ctx) do
    case node.kind do
      :union ->
        ", &#{encoder_fn(name)}/1"

      :ref ->
        if ref_module(node, ctx), do: ", &#{encoder_fn(name)}/1", else: ""

      :array ->
        case node.items do
          %{kind: :ref} = ref -> if ref_module(ref, ctx), do: ", &#{encoder_fn(name)}/1", else: ""
          %{kind: :union} -> ", &#{encoder_fn(name)}/1"
          _ -> ""
        end

      _ ->
        ""
    end
  end

  defp from_map do
    """
    @doc "Decode a wire-format map. Delegates to new/1."
    @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
    def from_map(map) when is_map(map), do: new(map)
    def from_map(_), do: {:error, [{"", "expected a map"}]}
    """
  end

  defp helpers(fields, ctx) do
    extra =
      fields
      |> Enum.flat_map(fn {name, node} -> field_helpers(name, node, ctx) end)

    base =
      if extra == [] do
        []
      else
        [
          "defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)",
          "defp encode_ref(v, _module) when is_map(v), do: v"
        ]
      end

    Enum.join(base ++ extra, "\n\n")
  end

  defp field_helpers(name, node, ctx) do
    case node.kind do
      :union ->
        union_clauses(encoder_fn(name), union_variants(node, ctx))

      :ref ->
        case ref_module(node, ctx) do
          nil -> []
          module -> ["defp #{encoder_fn(name)}(v), do: encode_ref(v, #{inspect(module)})"]
        end

      :array ->
        case node.items do
          %{kind: :ref} = ref ->
            case ref_module(ref, ctx) do
              nil ->
                []

              module ->
                [
                  "defp #{encoder_fn(name)}(values), do: Enum.map(values, &#{item_fn(name)}/1)",
                  "defp #{item_fn(name)}(v), do: encode_ref(v, #{inspect(module)})"
                ]
            end

          %{kind: :union} ->
            [
              "defp #{encoder_fn(name)}(values), do: Enum.map(values, &#{item_fn(name)}/1)"
              | union_clauses(item_fn(name), union_variants(node.items, ctx))
            ]

          _ ->
            []
        end

      _ ->
        []
    end
  end

  defp union_clauses(fn_name, variants) do
    clauses =
      Enum.map(variants, fn {type_id, module} ->
        "defp #{fn_name}(v) when is_struct(v, #{inspect(module)}), do: Map.put(#{inspect(module)}.to_map(v), \"$type\", #{inspect(type_id)})"
      end)

    clauses ++ ["defp #{fn_name}(v) when is_map(v), do: v"]
  end

  defp encoder_fn(name), do: "encode_#{field_atom(name)}"
  defp item_fn(name), do: "encode_#{field_atom(name)}_item"

  # --- Utilities ---------------------------------------------------------------------

  defp field_atom(name), do: name |> Macro.underscore() |> String.to_atom()

  # Field binding vars get an f_ prefix so wire names like `end` don't
  # collide with Elixir keywords.
  defp field_var(name), do: "f_#{field_atom(name)}"

  defp indent(text, spaces) do
    prefix = String.duplicate(" ", spaces)

    text
    |> String.split("\n")
    |> Enum.map_join("\n", fn line -> if String.trim(line) == "", do: "", else: prefix <> line end)
  end
end
