# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Community.Preference.Ai.Preference do
  @moduledoc """
  Declares a user's preferences regarding AI usage of their public data. A record at key 'self' with globalScope establishes default preferences. Additional records keyed by TID establish scoped overrides for specific entities or content collections.

  Object schema `community.lexicon.preference.ai##preference`.


  ## Fields

  - `allow`: Whether this usage is permitted (true) or denied (false).
  - `updated_at`: When this specific preference was last changed.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.preference.ai#preference"

  @enforce_keys [:allow, :updated_at]
  defstruct allow: nil, updated_at: nil, extra: %{}

  @type t :: %__MODULE__{allow: boolean(), updated_at: String.t()}

  @fields %{allow: "allow", updated_at: "updatedAt"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_allow, e1} = Runtime.get_boolean(attrs, :allow, "allow", required: true)

    {f_updated_at, e2} =
      Runtime.get_string(attrs, :updated_at, "updatedAt", required: true, format: "datetime")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{allow: f_allow, updated_at: f_updated_at, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("allow", struct.allow)
    |> Runtime.put_field("updatedAt", struct.updated_at)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end