# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Community.Preference.Ai.PreferenceSet do
  @moduledoc """
  Declares a user's preferences regarding AI usage of their public data. A record at key 'self' with globalScope establishes default preferences. Additional records keyed by TID establish scoped overrides for specific entities or content collections.

  A set of AI usage preferences. Omitted fields mean undefined (no declared preference).

  Object schema `community.lexicon.preference.ai##preferenceSet`.


  ## Fields

  - `embedding`: ref `#preference`
  - `inference`: ref `#preference`
  - `synthetic_content`: ref `#preference`
  - `training`: ref `#preference`
  """

  alias Exosphere.Bsky.Runtime

  alias Exosphere.Community.Preference.Ai.Preference
  @type_id "community.lexicon.preference.ai#preferenceSet"

  @enforce_keys []
  defstruct embedding: nil, inference: nil, synthetic_content: nil, training: nil, extra: %{}

  @type t :: %__MODULE__{
          embedding: Preference.t() | nil,
          inference: Preference.t() | nil,
          synthetic_content: Preference.t() | nil,
          training: Preference.t() | nil
        }

  @fields %{
    embedding: "embedding",
    inference: "inference",
    synthetic_content: "syntheticContent",
    training: "training"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_embedding, e1} =
      Runtime.get_ref(
        attrs,
        :embedding,
        "embedding",
        [],
        Exosphere.Community.Preference.Ai.Preference
      )

    {f_inference, e2} =
      Runtime.get_ref(
        attrs,
        :inference,
        "inference",
        [],
        Exosphere.Community.Preference.Ai.Preference
      )

    {f_synthetic_content, e3} =
      Runtime.get_ref(
        attrs,
        :synthetic_content,
        "syntheticContent",
        [],
        Exosphere.Community.Preference.Ai.Preference
      )

    {f_training, e4} =
      Runtime.get_ref(
        attrs,
        :training,
        "training",
        [],
        Exosphere.Community.Preference.Ai.Preference
      )

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok,
       %__MODULE__{
         embedding: f_embedding,
         inference: f_inference,
         synthetic_content: f_synthetic_content,
         training: f_training,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("embedding", struct.embedding, &encode_embedding/1)
    |> Runtime.put_field("inference", struct.inference, &encode_inference/1)
    |> Runtime.put_field(
      "syntheticContent",
      struct.synthetic_content,
      &encode_synthetic_content/1
    )
    |> Runtime.put_field("training", struct.training, &encode_training/1)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_embedding(v), do: encode_ref(v, Exosphere.Community.Preference.Ai.Preference)

  defp encode_inference(v), do: encode_ref(v, Exosphere.Community.Preference.Ai.Preference)

  defp encode_synthetic_content(v),
    do: encode_ref(v, Exosphere.Community.Preference.Ai.Preference)

  defp encode_training(v), do: encode_ref(v, Exosphere.Community.Preference.Ai.Preference)
end
