# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Actor.ContentVisibilityDeclaration do
  @moduledoc """
  Record schema `app.bsky.actor.contentVisibilityDeclaration`.


  ## Fields

  - `hide_from_algorithmic_recommendations`: Whether the account requests that its posts be hidden from algorithmic recommendations. Consumers must treat a missing record as false.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.actor.contentVisibilityDeclaration"

  @enforce_keys [:hide_from_algorithmic_recommendations]
  defstruct hide_from_algorithmic_recommendations: nil, extra: %{}

  @type t :: %__MODULE__{hide_from_algorithmic_recommendations: boolean()}

  @fields %{hide_from_algorithmic_recommendations: "hideFromAlgorithmicRecommendations"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_hide_from_algorithmic_recommendations, e1} =
      Runtime.get_boolean(
        attrs,
        :hide_from_algorithmic_recommendations,
        "hideFromAlgorithmicRecommendations", required: true)

    errors = e1

    if errors == [] do
      {:ok,
       %__MODULE__{
         hide_from_algorithmic_recommendations: f_hide_from_algorithmic_recommendations,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field(
      "hideFromAlgorithmicRecommendations",
      struct.hide_from_algorithmic_recommendations
    )
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end