# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Actor.Profile do
  @moduledoc """
  Record schema `app.bsky.actor.profile`.


  ## Fields

  - `avatar`: Small image to be displayed next to posts from account. AKA, 'profile picture'
  - `banner`: Larger horizontal image to display behind profile view.
  - `created_at`: string, format `datetime`
  - `description`: Free-form profile description text.
  - `display_name`: string
  - `joined_via_starter_pack`: ref `com.atproto.repo.strongRef`
  - `labels`: Self-label values, specific to the Bluesky application, on the overall account.
  - `pinned_post`: ref `com.atproto.repo.strongRef`
  - `pronouns`: Free-form pronouns text.
  - `website`: string, format `uri`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.actor.profile"
  @variants_labels [
    {"com.atproto.label.defs#selfLabels", Exosphere.ATProto.Label.Defs.SelfLabels}
  ]

  @enforce_keys []
  defstruct avatar: nil,
            banner: nil,
            created_at: nil,
            description: nil,
            display_name: nil,
            joined_via_starter_pack: nil,
            labels: nil,
            pinned_post: nil,
            pronouns: nil,
            website: nil,
            extra: %{}

  @type t :: %__MODULE__{
          avatar: term() | nil,
          banner: term() | nil,
          created_at: String.t() | nil,
          description: String.t() | nil,
          display_name: String.t() | nil,
          joined_via_starter_pack: Exosphere.ATProto.Repo.StrongRef.t() | nil,
          labels: Exosphere.ATProto.Label.Defs.SelfLabels.t() | map() | nil,
          pinned_post: Exosphere.ATProto.Repo.StrongRef.t() | nil,
          pronouns: String.t() | nil,
          website: String.t() | nil
        }

  @fields %{
    avatar: "avatar",
    banner: "banner",
    created_at: "createdAt",
    description: "description",
    display_name: "displayName",
    joined_via_starter_pack: "joinedViaStarterPack",
    labels: "labels",
    pinned_post: "pinnedPost",
    pronouns: "pronouns",
    website: "website"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_avatar, e1} = Runtime.get_any(attrs, :avatar, "avatar", [])
    {f_banner, e2} = Runtime.get_any(attrs, :banner, "banner", [])
    {f_created_at, e3} = Runtime.get_string(attrs, :created_at, "createdAt", format: "datetime")

    {f_description, e4} =
      Runtime.get_string(attrs, :description, "description", max_length: 2560, max_graphemes: 256)

    {f_display_name, e5} =
      Runtime.get_string(attrs, :display_name, "displayName", max_length: 640, max_graphemes: 64)

    {f_joined_via_starter_pack, e6} =
      Runtime.get_ref(
        attrs,
        :joined_via_starter_pack,
        "joinedViaStarterPack",
        [],
        Exosphere.ATProto.Repo.StrongRef
      )

    {f_labels, e7} = Runtime.get_union(attrs, :labels, "labels", [], @variants_labels)

    {f_pinned_post, e8} =
      Runtime.get_ref(attrs, :pinned_post, "pinnedPost", [], Exosphere.ATProto.Repo.StrongRef)

    {f_pronouns, e9} =
      Runtime.get_string(attrs, :pronouns, "pronouns", max_length: 200, max_graphemes: 20)

    {f_website, e10} = Runtime.get_string(attrs, :website, "website", format: "uri")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8 ++ e9 ++ e10

    if errors == [] do
      {:ok,
       %__MODULE__{
         avatar: f_avatar,
         banner: f_banner,
         created_at: f_created_at,
         description: f_description,
         display_name: f_display_name,
         joined_via_starter_pack: f_joined_via_starter_pack,
         labels: f_labels,
         pinned_post: f_pinned_post,
         pronouns: f_pronouns,
         website: f_website,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("avatar", struct.avatar)
    |> Runtime.put_field("banner", struct.banner)
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field("displayName", struct.display_name)
    |> Runtime.put_field(
      "joinedViaStarterPack",
      struct.joined_via_starter_pack,
      &encode_joined_via_starter_pack/1
    )
    |> Runtime.put_field("labels", struct.labels, &encode_labels/1)
    |> Runtime.put_field("pinnedPost", struct.pinned_post, &encode_pinned_post/1)
    |> Runtime.put_field("pronouns", struct.pronouns)
    |> Runtime.put_field("website", struct.website)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_joined_via_starter_pack(v), do: encode_ref(v, Exosphere.ATProto.Repo.StrongRef)

  defp encode_labels(v) when is_struct(v, Exosphere.ATProto.Label.Defs.SelfLabels),
    do:
      Map.put(
        Exosphere.ATProto.Label.Defs.SelfLabels.to_map(v),
        "$type",
        "com.atproto.label.defs#selfLabels"
      )

  defp encode_labels(v) when is_map(v), do: v

  defp encode_pinned_post(v), do: encode_ref(v, Exosphere.ATProto.Repo.StrongRef)
end