# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Actor.Status do
  @moduledoc """
  Record schema `app.bsky.actor.status`.


  ## Fields

  - `created_at`: string, format `datetime`
  - `duration_minutes`: The duration of the status in minutes. Applications can choose to impose minimum and maximum limits.
  - `embed`: An optional embed associated with the status.
  - `status`: The status for the account.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.actor.status"
  @variants_embed [{"app.bsky.embed.external", Exosphere.Bsky.Embed.External}]

  @enforce_keys [:created_at, :status]
  defstruct created_at: nil, duration_minutes: nil, embed: nil, status: nil, extra: %{}

  @type t :: %__MODULE__{
          created_at: String.t(),
          duration_minutes: integer() | nil,
          embed: Exosphere.Bsky.Embed.External.t() | map() | nil,
          status: String.t()
        }

  @fields %{
    created_at: "createdAt",
    duration_minutes: "durationMinutes",
    embed: "embed",
    status: "status"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_created_at, e1} =
      Runtime.get_string(attrs, :created_at, "createdAt", required: true, format: "datetime")

    {f_duration_minutes, e2} =
      Runtime.get_integer(attrs, :duration_minutes, "durationMinutes", minimum: 1)

    {f_embed, e3} = Runtime.get_union(attrs, :embed, "embed", [], @variants_embed)
    {f_status, e4} = Runtime.get_string(attrs, :status, "status", required: true)

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok,
       %__MODULE__{
         created_at: f_created_at,
         duration_minutes: f_duration_minutes,
         embed: f_embed,
         status: f_status,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map. Record schemas include \"$type\"."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("createdAt", struct.created_at)
    |> Runtime.put_field("durationMinutes", struct.duration_minutes)
    |> Runtime.put_field("embed", struct.embed, &encode_embed/1)
    |> Runtime.put_field("status", struct.status)
    |> Map.merge(struct.extra)
    |> Map.put("$type", @type_id)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_embed(v) when is_struct(v, Exosphere.Bsky.Embed.External),
    do: Map.put(Exosphere.Bsky.Embed.External.to_map(v), "$type", "app.bsky.embed.external")

  defp encode_embed(v) when is_map(v), do: v
end