# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Richtext.Facet do
  @moduledoc """
  Annotation of a sub-string within rich text.

  Object schema `app.bsky.richtext.facet`.


  ## Fields

  - `features`: array
  - `index`: ref `#byteSlice`
  """

  alias Exosphere.Bsky.Runtime

  alias Exosphere.Bsky.Richtext.Facet.ByteSlice
  alias Exosphere.Bsky.Richtext.Facet.Link
  alias Exosphere.Bsky.Richtext.Facet.Mention
  alias Exosphere.Bsky.Richtext.Facet.Tag
  @type_id "app.bsky.richtext.facet"
  @variants_features [
    {"app.bsky.richtext.facet#mention", Exosphere.Bsky.Richtext.Facet.Mention},
    {"app.bsky.richtext.facet#link", Exosphere.Bsky.Richtext.Facet.Link},
    {"app.bsky.richtext.facet#tag", Exosphere.Bsky.Richtext.Facet.Tag}
  ]

  @enforce_keys [:features, :index]
  defstruct features: nil, index: nil, extra: %{}

  @type t :: %__MODULE__{
          features: [Mention.t() | Link.t() | Tag.t() | map()],
          index: ByteSlice.t()
        }

  @fields %{features: "features", index: "index"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_features, e1} =
      Runtime.get_array(attrs, :features, "features", [required: true], fn v, path ->
        Runtime.item_union(v, path, @variants_features)
      end)

    {f_index, e2} =
      Runtime.get_ref(
        attrs,
        :index,
        "index",
        [required: true],
        Exosphere.Bsky.Richtext.Facet.ByteSlice
      )

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{features: f_features, index: f_index, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("features", struct.features, &encode_features/1)
    |> Runtime.put_field("index", struct.index, &encode_index/1)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_features(values), do: Enum.map(values, &encode_features_item/1)

  defp encode_features_item(v) when is_struct(v, Exosphere.Bsky.Richtext.Facet.Mention),
    do: Map.put(Mention.to_map(v), "$type", "app.bsky.richtext.facet#mention")

  defp encode_features_item(v) when is_struct(v, Exosphere.Bsky.Richtext.Facet.Link),
    do: Map.put(Link.to_map(v), "$type", "app.bsky.richtext.facet#link")

  defp encode_features_item(v) when is_struct(v, Exosphere.Bsky.Richtext.Facet.Tag),
    do: Map.put(Tag.to_map(v), "$type", "app.bsky.richtext.facet#tag")

  defp encode_features_item(v) when is_map(v), do: v

  defp encode_index(v), do: encode_ref(v, Exosphere.Bsky.Richtext.Facet.ByteSlice)
end
