# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Embed.Images.Image do
  @moduledoc """
  A set of images embedded in a Bluesky record (eg, a post).

  Object schema `app.bsky.embed.images##image`.


  ## Fields

  - `alt`: Alt text description of the image, for accessibility.
  - `aspect_ratio`: ref `app.bsky.embed.defs#aspectRatio`
  - `image`: The raw image file. May be up to 2 MB, formerly limited to 1 MB.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.embed.images#image"

  @enforce_keys [:alt, :image]
  defstruct alt: nil, aspect_ratio: nil, image: nil, extra: %{}

  @type t :: %__MODULE__{alt: String.t(), aspect_ratio: term() | nil, image: term()}

  @fields %{alt: "alt", aspect_ratio: "aspectRatio", image: "image"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_alt, e1} = Runtime.get_string(attrs, :alt, "alt", required: true)
    {f_aspect_ratio, e2} = Runtime.get_any(attrs, :aspect_ratio, "aspectRatio", [])
    {f_image, e3} = Runtime.get_any(attrs, :image, "image", required: true)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %__MODULE__{alt: f_alt, aspect_ratio: f_aspect_ratio, image: f_image, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("alt", struct.alt)
    |> Runtime.put_field("aspectRatio", struct.aspect_ratio)
    |> Runtime.put_field("image", struct.image)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end