# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Community.Calendar.Event.Uri do
  @moduledoc """
  A URI associated with the event.

  Object schema `community.lexicon.calendar.event##uri`.


  ## Fields

  - `name`: The display name of the URI.
  - `uri`: string, format `uri`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "community.lexicon.calendar.event#uri"

  @enforce_keys [:uri]
  defstruct name: nil, uri: nil, extra: %{}

  @type t :: %__MODULE__{name: String.t() | nil, uri: String.t()}

  @fields %{name: "name", uri: "uri"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_name, e1} = Runtime.get_string(attrs, :name, "name", [])
    {f_uri, e2} = Runtime.get_string(attrs, :uri, "uri", required: true, format: "uri")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{name: f_name, uri: f_uri, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("name", struct.name)
    |> Runtime.put_field("uri", struct.uri)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end