# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Labeler.Defs.LabelerPolicies do
  @moduledoc """
  Object schema `app.bsky.labeler.defs##labelerPolicies`.


  ## Fields

  - `label_value_definitions`: Label values created by this labeler and scoped exclusively to it. Labels defined here will override global label definitions for this labeler.
  - `label_values`: The label values which this labeler publishes. May include global or custom labels.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.labeler.defs#labelerPolicies"

  @enforce_keys [:label_values]
  defstruct label_value_definitions: nil, label_values: nil, extra: %{}

  @type t :: %__MODULE__{
          label_value_definitions: [Exosphere.ATProto.Label.Defs.LabelValueDefinition.t()] | nil,
          label_values: [term()]
        }

  @fields %{label_value_definitions: "labelValueDefinitions", label_values: "labelValues"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_label_value_definitions, e1} =
      Runtime.get_array(attrs, :label_value_definitions, "labelValueDefinitions", [], fn v,
                                                                                         path ->
        Runtime.item_ref(v, path, Exosphere.ATProto.Label.Defs.LabelValueDefinition)
      end)

    {f_label_values, e2} =
      Runtime.get_array(attrs, :label_values, "labelValues", [required: true], fn v, _path ->
        {:ok, v}
      end)

    errors = e1 ++ e2

    if errors == [] do
      {:ok,
       %__MODULE__{
         label_value_definitions: f_label_value_definitions,
         label_values: f_label_values,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field(
      "labelValueDefinitions",
      struct.label_value_definitions,
      &encode_label_value_definitions/1
    )
    |> Runtime.put_field("labelValues", struct.label_values)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_label_value_definitions(values),
    do: Enum.map(values, &encode_label_value_definitions_item/1)

  defp encode_label_value_definitions_item(v),
    do: encode_ref(v, Exosphere.ATProto.Label.Defs.LabelValueDefinition)
end