# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Feed.Post.Entity do
  @moduledoc """
  Deprecated: use facets instead.

  Object schema `app.bsky.feed.post##entity`.


  ## Fields

  - `index`: ref `#textSlice`
  - `type`: Expected values are 'mention' and 'link'.
  - `value`: string
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.feed.post#entity"

  @enforce_keys [:index, :type, :value]
  defstruct index: nil, type: nil, value: nil, extra: %{}

  @type t :: %__MODULE__{
          index: Exosphere.Bsky.Feed.Post.TextSlice.t(),
          type: String.t(),
          value: String.t()
        }

  @fields %{index: "index", type: "type", value: "value"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_index, e1} =
      Runtime.get_ref(
        attrs,
        :index,
        "index",
        [required: true],
        Exosphere.Bsky.Feed.Post.TextSlice
      )

    {f_type, e2} = Runtime.get_string(attrs, :type, "type", required: true)
    {f_value, e3} = Runtime.get_string(attrs, :value, "value", required: true)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %__MODULE__{index: f_index, type: f_type, value: f_value, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("index", struct.index, &encode_index/1)
    |> Runtime.put_field("type", struct.type)
    |> Runtime.put_field("value", struct.value)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_index(v), do: encode_ref(v, Exosphere.Bsky.Feed.Post.TextSlice)
end