# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Feed.Post.ReplyRef do
  @moduledoc """
  Object schema `app.bsky.feed.post##replyRef`.


  ## Fields

  - `parent`: ref `com.atproto.repo.strongRef`
  - `root`: ref `com.atproto.repo.strongRef`
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.feed.post#replyRef"

  @enforce_keys [:parent, :root]
  defstruct parent: nil, root: nil, extra: %{}

  @type t :: %__MODULE__{
          parent: Exosphere.ATProto.Repo.StrongRef.t(),
          root: Exosphere.ATProto.Repo.StrongRef.t()
        }

  @fields %{parent: "parent", root: "root"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_parent, e1} =
      Runtime.get_ref(
        attrs,
        :parent,
        "parent",
        [required: true],
        Exosphere.ATProto.Repo.StrongRef
      )

    {f_root, e2} =
      Runtime.get_ref(attrs, :root, "root", [required: true], Exosphere.ATProto.Repo.StrongRef)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{parent: f_parent, root: f_root, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("parent", struct.parent, &encode_parent/1)
    |> Runtime.put_field("root", struct.root, &encode_root/1)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_parent(v), do: encode_ref(v, Exosphere.ATProto.Repo.StrongRef)

  defp encode_root(v), do: encode_ref(v, Exosphere.ATProto.Repo.StrongRef)
end