# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Feed.Post.TextSlice do
  @moduledoc """
  Deprecated. Use app.bsky.richtext instead -- A text segment. Start is inclusive, end is exclusive. Indices are for utf16-encoded strings.

  Object schema `app.bsky.feed.post##textSlice`.


  ## Fields

  - `end`: integer
  - `start`: integer
  """

  alias Exosphere.Bsky.Runtime
  @type_id "app.bsky.feed.post#textSlice"

  @enforce_keys [:end, :start]
  defstruct end: nil, start: nil, extra: %{}

  @type t :: %__MODULE__{end: integer(), start: integer()}

  @fields %{end: "end", start: "start"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_end, e1} = Runtime.get_integer(attrs, :end, "end", required: true, minimum: 0)
    {f_start, e2} = Runtime.get_integer(attrs, :start, "start", required: true, minimum: 0)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %__MODULE__{end: f_end, start: f_start, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("end", struct.end)
    |> Runtime.put_field("start", struct.start)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end
