# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.ATProto.Label.Defs.LabelValueDefinitionStrings do
  @moduledoc """
  Strings which describe the label in the UI, localized into a specific language.

  Object schema `com.atproto.label.defs##labelValueDefinitionStrings`.


  ## Fields

  - `description`: A longer description of what the label means and why it might be applied.
  - `lang`: The code of the language these strings are written in.
  - `name`: A short human-readable name for the label.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "com.atproto.label.defs#labelValueDefinitionStrings"

  @enforce_keys [:description, :lang, :name]
  defstruct description: nil, lang: nil, name: nil, extra: %{}

  @type t :: %__MODULE__{description: String.t(), lang: String.t(), name: String.t()}

  @fields %{description: "description", lang: "lang", name: "name"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_description, e1} =
      Runtime.get_string(attrs, :description, "description",
        required: true,
        max_length: 100_000,
        max_graphemes: 10_000
      )

    {f_lang, e2} = Runtime.get_string(attrs, :lang, "lang", required: true, format: "language")

    {f_name, e3} =
      Runtime.get_string(attrs, :name, "name", required: true, max_length: 640, max_graphemes: 64)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %__MODULE__{description: f_description, lang: f_lang, name: f_name, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("description", struct.description)
    |> Runtime.put_field("lang", struct.lang)
    |> Runtime.put_field("name", struct.name)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}
end
