# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.ATProto.Label.Defs.LabelValueDefinition do
  @moduledoc """
  Declares a label value and its expected interpretations and behaviors.

  Object schema `com.atproto.label.defs##labelValueDefinition`.


  ## Fields

  - `adult_only`: Does the user need to have adult content enabled in order to configure this label?
  - `blurs`: What should this label hide in the UI, if applied? 'content' hides all of the target; 'media' hides the images/video/audio; 'none' hides nothing.
  - `default_setting`: The default setting for this label.
  - `identifier`: The value of the label being defined. Must only include lowercase ascii and the '-' character ([a-z-]+).
  - `locales`: array
  - `severity`: How should a client visually convey this label? 'inform' means neutral and informational; 'alert' means negative and warning; 'none' means show nothing.
  """

  alias Exosphere.Bsky.Runtime
  @type_id "com.atproto.label.defs#labelValueDefinition"

  @enforce_keys [:blurs, :identifier, :locales, :severity]
  defstruct adult_only: nil,
            blurs: nil,
            default_setting: nil,
            identifier: nil,
            locales: nil,
            severity: nil,
            extra: %{}

  @type t :: %__MODULE__{
          adult_only: boolean() | nil,
          blurs: String.t(),
          default_setting: String.t() | nil,
          identifier: String.t(),
          locales: [Exosphere.ATProto.Label.Defs.LabelValueDefinitionStrings.t()],
          severity: String.t()
        }

  @fields %{
    adult_only: "adultOnly",
    blurs: "blurs",
    default_setting: "defaultSetting",
    identifier: "identifier",
    locales: "locales",
    severity: "severity"
  }

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_adult_only, e1} = Runtime.get_boolean(attrs, :adult_only, "adultOnly", [])
    {f_blurs, e2} = Runtime.get_string(attrs, :blurs, "blurs", required: true)

    {f_default_setting, e3} =
      Runtime.get_string(attrs, :default_setting, "defaultSetting", default: "warn")

    {f_identifier, e4} =
      Runtime.get_string(attrs, :identifier, "identifier",
        required: true,
        max_length: 100,
        max_graphemes: 100
      )

    {f_locales, e5} =
      Runtime.get_array(attrs, :locales, "locales", [required: true], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.ATProto.Label.Defs.LabelValueDefinitionStrings)
      end)

    {f_severity, e6} = Runtime.get_string(attrs, :severity, "severity", required: true)

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6

    if errors == [] do
      {:ok,
       %__MODULE__{
         adult_only: f_adult_only,
         blurs: f_blurs,
         default_setting: f_default_setting,
         identifier: f_identifier,
         locales: f_locales,
         severity: f_severity,
         extra: extra
       }}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("adultOnly", struct.adult_only)
    |> Runtime.put_field("blurs", struct.blurs)
    |> Runtime.put_field("defaultSetting", struct.default_setting)
    |> Runtime.put_field("identifier", struct.identifier)
    |> Runtime.put_field("locales", struct.locales, &encode_locales/1)
    |> Runtime.put_field("severity", struct.severity)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_locales(values), do: Enum.map(values, &encode_locales_item/1)

  defp encode_locales_item(v),
    do: encode_ref(v, Exosphere.ATProto.Label.Defs.LabelValueDefinitionStrings)
end