# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.ATProto.Label.Defs.SelfLabels do
  @moduledoc """
  Metadata tags on an atproto record, published by the author within the record.

  Object schema `com.atproto.label.defs##selfLabels`.


  ## Fields

  - `values`: array
  """

  alias Exosphere.Bsky.Runtime
  @type_id "com.atproto.label.defs#selfLabels"

  @enforce_keys [:values]
  defstruct values: nil, extra: %{}

  @type t :: %__MODULE__{values: [Exosphere.ATProto.Label.Defs.SelfLabel.t()]}

  @fields %{values: "values"}

  @doc "The lexicon type ID (nsid or nsid#def) this module was generated from."
  @spec type_id() :: String.t()
  def type_id, do: @type_id

  @doc """
  Build and validate from a map of attrs (atom or wire string keys).

  Unknown keys are kept in `extra` and re-emitted by `to_map/1`.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def new(attrs) when is_map(attrs) do
    {attrs, extra} = Runtime.atomize(attrs, @fields)

    {f_values, e1} =
      Runtime.get_array(attrs, :values, "values", [required: true, max_length: 10], fn v, path ->
        Runtime.item_ref(v, path, Exosphere.ATProto.Label.Defs.SelfLabel)
      end)

    errors = e1

    if errors == [] do
      {:ok, %__MODULE__{values: f_values, extra: extra}}
    else
      {:error, errors}
    end
  end

  def new(_), do: {:error, [{"", "expected a map"}]}

  @doc "Build and validate, raising ArgumentError on error."
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, struct} -> struct
      {:error, errors} -> raise ArgumentError, "invalid #{@type_id}: #{inspect(errors)}"
    end
  end

  @doc "Encode to the wire-format map."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    %{}
    |> Runtime.put_field("values", struct.values, &encode_values/1)
    |> Map.merge(struct.extra)
  end

  @doc "Decode a wire-format map. Delegates to new/1."
  @spec from_map(map()) :: {:ok, t()} | {:error, [{path :: String.t(), message :: String.t()}]}
  def from_map(map) when is_map(map), do: new(map)
  def from_map(_), do: {:error, [{"", "expected a map"}]}

  defp encode_ref(v, module) when is_struct(v, module), do: module.to_map(v)

  defp encode_ref(v, _module) when is_map(v), do: v

  defp encode_values(values), do: Enum.map(values, &encode_values_item/1)

  defp encode_values_item(v), do: encode_ref(v, Exosphere.ATProto.Label.Defs.SelfLabel)
end