# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Actor do
  @moduledoc """
  XRPC client functions for the `app.bsky.actor` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `get_preferences` — query: app.bsky.actor.getPreferences
  - `get_profile` — query: app.bsky.actor.getProfile
  - `get_profiles` — query: app.bsky.actor.getProfiles
  - `get_suggestions` — query: app.bsky.actor.getSuggestions
  - `put_preferences` — procedure: app.bsky.actor.putPreferences
  - `search_actors` — query: app.bsky.actor.searchActors
  - `search_actors_typeahead` — query: app.bsky.actor.searchActorsTypeahead
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @doc """
    Get private preferences attached to the current account. Expected use is synchronization between multiple devices, and import/export during account migration. Requires auth.

    ## Parameters



  """
  @spec get_preferences(Client.t()) :: {:ok, map()} | {:error, term()}
  def get_preferences(client) do
    client
    |> Client.query("app.bsky.actor.getPreferences")
  end

  @fields_get_profile %{actor: "actor"}

  @doc """
    Get detailed profile view of an actor. Does not require auth, but contains relevant metadata with auth.

    ## Parameters

    - `actor` (string, required): Handle or DID of account to fetch profile of.

  """
  @spec get_profile(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_profile(client, params \\ []) do
    with {:ok, validated} <- validate_get_profile(params) do
      client
      |> Client.query(
        "app.bsky.actor.getProfile",
        Runtime.encode_query_params(validated, @fields_get_profile)
      )
    end
  end

  defp validate_get_profile(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_profile)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    errors = e1

    if errors == [] do
      {:ok, %{actor: f_actor}}
    else
      {:error, errors}
    end
  end

  @fields_get_profiles %{actors: "actors"}

  @doc """
    Get detailed profile views of multiple actors.

    ## Parameters

    - `actors` (array, required)

  """
  @spec get_profiles(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_profiles(client, params \\ []) do
    with {:ok, validated} <- validate_get_profiles(params) do
      client
      |> Client.query(
        "app.bsky.actor.getProfiles",
        Runtime.encode_query_params(validated, @fields_get_profiles)
      )
    end
  end

  defp validate_get_profiles(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_profiles)

    {f_actors, e1} =
      Runtime.get_array(attrs, :actors, "actors", [required: true, max_length: 25], fn v, path ->
        Runtime.item_string(v, path, format: "at-identifier")
      end)

    errors = e1

    if errors == [] do
      {:ok, %{actors: f_actors}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggestions %{cursor: "cursor", limit: "limit"}

  @doc """
    Get a list of suggested actors. Expected use is discovery of accounts to follow during new account onboarding.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_suggestions(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_suggestions(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggestions(params) do
      client
      |> Client.query(
        "app.bsky.actor.getSuggestions",
        Runtime.encode_query_params(validated, @fields_get_suggestions)
      )
    end
  end

  defp validate_get_suggestions(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggestions)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @doc """
    Set the private preferences attached to the account.
  """
  @spec put_preferences(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def put_preferences(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.actor.putPreferences", body)
  end

  @fields_search_actors %{cursor: "cursor", limit: "limit", q: "q", term: "term"}

  @doc """
    Find actors (profiles) matching search criteria. Does not require auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `q` (string, optional): Search query string. Syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
    - `term` (string, optional): DEPRECATED: use 'q' instead.

  """
  @spec search_actors(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_actors(client, params \\ []) do
    with {:ok, validated} <- validate_search_actors(params) do
      client
      |> Client.query(
        "app.bsky.actor.searchActors",
        Runtime.encode_query_params(validated, @fields_search_actors)
      )
    end
  end

  defp validate_search_actors(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_actors)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_q, e3} = Runtime.get_string(attrs, :q, "q", [])
    {f_term, e4} = Runtime.get_string(attrs, :term, "term", [])

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, q: f_q, term: f_term}}
    else
      {:error, errors}
    end
  end

  @fields_search_actors_typeahead %{limit: "limit", q: "q", term: "term"}

  @doc """
    Find actor suggestions for a prefix search term. Expected use is for auto-completion during text field entry. Does not require auth.

    ## Parameters

    - `limit` (integer, optional)
    - `q` (string, optional): Search query prefix; not a full query string.
    - `term` (string, optional): DEPRECATED: use 'q' instead.

  """
  @spec search_actors_typeahead(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_actors_typeahead(client, params \\ []) do
    with {:ok, validated} <- validate_search_actors_typeahead(params) do
      client
      |> Client.query(
        "app.bsky.actor.searchActorsTypeahead",
        Runtime.encode_query_params(validated, @fields_search_actors_typeahead)
      )
    end
  end

  defp validate_search_actors_typeahead(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_actors_typeahead)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 10)

    {f_q, e2} = Runtime.get_string(attrs, :q, "q", [])
    {f_term, e3} = Runtime.get_string(attrs, :term, "term", [])

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{limit: f_limit, q: f_q, term: f_term}}
    else
      {:error, errors}
    end
  end
end
