# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Bookmark do
  @moduledoc """
  XRPC client functions for the `app.bsky.bookmark` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `create_bookmark` — procedure: app.bsky.bookmark.createBookmark
  - `delete_bookmark` — procedure: app.bsky.bookmark.deleteBookmark
  - `get_bookmarks` — query: app.bsky.bookmark.getBookmarks
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @doc """
    Creates a private bookmark for the specified record. Currently, only `app.bsky.feed.post` records are supported. Requires authentication.
  """
  @spec create_bookmark(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def create_bookmark(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.bookmark.createBookmark", body)
  end

  @doc """
    Deletes a private bookmark for the specified record. Currently, only `app.bsky.feed.post` records are supported. Requires authentication.
  """
  @spec delete_bookmark(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def delete_bookmark(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.bookmark.deleteBookmark", body)
  end

  @fields_get_bookmarks %{cursor: "cursor", limit: "limit"}

  @doc """
    Gets views of records bookmarked by the authenticated user. Requires authentication.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_bookmarks(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_bookmarks(client, params \\ []) do
    with {:ok, validated} <- validate_get_bookmarks(params) do
      client
      |> Client.query(
        "app.bsky.bookmark.getBookmarks",
        Runtime.encode_query_params(validated, @fields_get_bookmarks)
      )
    end
  end

  defp validate_get_bookmarks(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_bookmarks)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end
end
