# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Contact do
  @moduledoc """
  XRPC client functions for the `app.bsky.contact` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `dismiss_match` — procedure: app.bsky.contact.dismissMatch
  - `get_matches` — query: app.bsky.contact.getMatches
  - `get_sync_status` — query: app.bsky.contact.getSyncStatus
  - `import_contacts` — procedure: app.bsky.contact.importContacts
  - `remove_data` — procedure: app.bsky.contact.removeData
  - `send_notification` — procedure: app.bsky.contact.sendNotification
  - `start_phone_verification` — procedure: app.bsky.contact.startPhoneVerification
  - `verify_phone` — procedure: app.bsky.contact.verifyPhone
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @doc """
    Removes a match that was found via contact import. It shouldn't appear again if the same contact is re-imported. Requires authentication.
  """
  @spec dismiss_match(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def dismiss_match(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.contact.dismissMatch", body)
  end

  @fields_get_matches %{cursor: "cursor", limit: "limit"}

  @doc """
    Returns the matched contacts (contacts that were mutually imported). Excludes dismissed matches. Requires authentication.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_matches(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_matches(client, params \\ []) do
    with {:ok, validated} <- validate_get_matches(params) do
      client
      |> Client.query(
        "app.bsky.contact.getMatches",
        Runtime.encode_query_params(validated, @fields_get_matches)
      )
    end
  end

  defp validate_get_matches(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_matches)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @doc """
    Gets the user's current contact import status. Requires authentication.

    ## Parameters



  """
  @spec get_sync_status(Client.t()) :: {:ok, map()} | {:error, term()}
  def get_sync_status(client) do
    client
    |> Client.query("app.bsky.contact.getSyncStatus")
  end

  @doc """
    Import contacts for securely matching with other users. This follows the protocol explained in https://docs.bsky.app/blog/contact-import-rfc. Requires authentication.
  """
  @spec import_contacts(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def import_contacts(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.contact.importContacts", body)
  end

  @doc """
    Removes all stored hashes used for contact matching, existing matches, and sync status. Requires authentication.
  """
  @spec remove_data(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def remove_data(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.contact.removeData", body)
  end

  @doc """
    System endpoint to send notifications related to contact imports. Requires role authentication.
  """
  @spec send_notification(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def send_notification(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.contact.sendNotification", body)
  end

  @doc """
    Starts a phone verification flow. The phone passed will receive a code via SMS that should be passed to `app.bsky.contact.verifyPhone`. Requires authentication.
  """
  @spec start_phone_verification(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def start_phone_verification(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.contact.startPhoneVerification", body)
  end

  @doc """
    Verifies control over a phone number with a code received via SMS and starts a contact import session. Requires authentication.
  """
  @spec verify_phone(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def verify_phone(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.contact.verifyPhone", body)
  end
end