# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Draft do
  @moduledoc """
  XRPC client functions for the `app.bsky.draft` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `create_draft` — procedure: app.bsky.draft.createDraft
  - `delete_draft` — procedure: app.bsky.draft.deleteDraft
  - `get_drafts` — query: app.bsky.draft.getDrafts
  - `update_draft` — procedure: app.bsky.draft.updateDraft
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @doc """
    Inserts a draft using private storage (stash). An upper limit of drafts might be enforced. Requires authentication.
  """
  @spec create_draft(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def create_draft(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.draft.createDraft", body)
  end

  @doc """
    Deletes a draft by ID. Requires authentication.
  """
  @spec delete_draft(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def delete_draft(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.draft.deleteDraft", body)
  end

  @fields_get_drafts %{cursor: "cursor", limit: "limit"}

  @doc """
    Gets views of user drafts. Requires authentication.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_drafts(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_drafts(client, params \\ []) do
    with {:ok, validated} <- validate_get_drafts(params) do
      client
      |> Client.query(
        "app.bsky.draft.getDrafts",
        Runtime.encode_query_params(validated, @fields_get_drafts)
      )
    end
  end

  defp validate_get_drafts(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_drafts)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @doc """
    Updates a draft using private storage (stash). If the draft ID points to a non-existing ID, the update will be silently ignored. This is done because updates don't enforce draft limit, so it accepts all writes, but will ignore invalid ones. Requires authentication.
  """
  @spec update_draft(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def update_draft(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.draft.updateDraft", body)
  end
end