# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Embed do
  @moduledoc """
  XRPC client functions for the `app.bsky.embed` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `get_embed_external_view` — query: app.bsky.embed.getEmbedExternalView
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @fields_get_embed_external_view %{uris: "uris", url: "url"}

  @doc """
    Resolve one or more AT-URIs into the data needed to render an enhanced external embed. Returns `associatedRefs` (strongRefs to embed into a post's external.associatedRefs), the raw `associatedRecords`, and a hydrated `view`. The response is empty (`{}`) when no records were resolvable, or when validation determined the resolved records don't actually back the requested URL; clients should fall back to their own link-card rendering in that case and skip writing strongRefs to the post.

    ## Parameters

    - `uris` (array, required): AT-URIs of any Atmosphere records that can be resolved and used to construct #externalView views. Example: a site.standard.document and optionally its associated site.standard.publication.
    - `url` (string, required): The canonical web URL the embed represents (typically the URL the user pasted into the composer). Used as the returned view's `uri`. May be used for validation in the future.

  """
  @spec get_embed_external_view(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_embed_external_view(client, params \\ []) do
    with {:ok, validated} <- validate_get_embed_external_view(params) do
      client
      |> Client.query(
        "app.bsky.embed.getEmbedExternalView",
        Runtime.encode_query_params(validated, @fields_get_embed_external_view)
      )
    end
  end

  defp validate_get_embed_external_view(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_embed_external_view)

    {f_uris, e1} =
      Runtime.get_array(attrs, :uris, "uris", [required: true, max_length: 4], fn v, path ->
        Runtime.item_string(v, path, format: "at-uri")
      end)

    {f_url, e2} = Runtime.get_string(attrs, :url, "url", required: true, format: "uri")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{uris: f_uris, url: f_url}}
    else
      {:error, errors}
    end
  end
end
