# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Feed do
  @moduledoc """
  XRPC client functions for the `app.bsky.feed` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `describe_feed_generator` — query: app.bsky.feed.describeFeedGenerator
  - `get_actor_feeds` — query: app.bsky.feed.getActorFeeds
  - `get_actor_likes` — query: app.bsky.feed.getActorLikes
  - `get_author_feed` — query: app.bsky.feed.getAuthorFeed
  - `get_feed` — query: app.bsky.feed.getFeed
  - `get_feed_generator` — query: app.bsky.feed.getFeedGenerator
  - `get_feed_generators` — query: app.bsky.feed.getFeedGenerators
  - `get_feed_skeleton` — query: app.bsky.feed.getFeedSkeleton
  - `get_likes` — query: app.bsky.feed.getLikes
  - `get_list_feed` — query: app.bsky.feed.getListFeed
  - `get_post_thread` — query: app.bsky.feed.getPostThread
  - `get_posts` — query: app.bsky.feed.getPosts
  - `get_quotes` — query: app.bsky.feed.getQuotes
  - `get_reposted_by` — query: app.bsky.feed.getRepostedBy
  - `get_suggested_feeds` — query: app.bsky.feed.getSuggestedFeeds
  - `get_timeline` — query: app.bsky.feed.getTimeline
  - `search_posts` — query: app.bsky.feed.searchPosts
  - `search_posts_v2` — query: app.bsky.feed.searchPostsV2
  - `send_interactions` — procedure: app.bsky.feed.sendInteractions
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @doc """
    Get information about a feed generator, including policies and offered feed URIs. Does not require auth; implemented by Feed Generator services (not App View).
  """
  @spec describe_feed_generator(Client.t()) :: {:ok, map()} | {:error, term()}
  def describe_feed_generator(client) do
    client
    |> Client.query("app.bsky.feed.describeFeedGenerator")
  end

  @fields_get_actor_feeds %{actor: "actor", cursor: "cursor", limit: "limit"}

  @doc """
    Get a list of feeds (feed generator records) created by the actor (in the actor's repo).

    ## Parameters

    - `actor` (string, required)
    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_actor_feeds(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_actor_feeds(client, params \\ []) do
    with {:ok, validated} <- validate_get_actor_feeds(params) do
      client
      |> Client.query(
        "app.bsky.feed.getActorFeeds",
        Runtime.encode_query_params(validated, @fields_get_actor_feeds)
      )
    end
  end

  defp validate_get_actor_feeds(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_actor_feeds)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_actor_likes %{actor: "actor", cursor: "cursor", limit: "limit"}

  @doc """
    Get a list of posts liked by an actor. Requires auth, actor must be the requesting account.

    ## Parameters

    - `actor` (string, required)
    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_actor_likes(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_actor_likes(client, params \\ []) do
    with {:ok, validated} <- validate_get_actor_likes(params) do
      client
      |> Client.query(
        "app.bsky.feed.getActorLikes",
        Runtime.encode_query_params(validated, @fields_get_actor_likes)
      )
    end
  end

  defp validate_get_actor_likes(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_actor_likes)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_author_feed %{
    actor: "actor",
    cursor: "cursor",
    filter: "filter",
    include_pins: "includePins",
    limit: "limit"
  }

  @doc """
    Get a view of an actor's 'author feed' (post and reposts by the author). Does not require auth.

    ## Parameters

    - `actor` (string, required)
    - `cursor` (string, optional)
    - `filter` (string, optional): Combinations of post/repost types to include in response.
    - `includePins` (boolean, optional)
    - `limit` (integer, optional)

  """
  @spec get_author_feed(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_author_feed(client, params \\ []) do
    with {:ok, validated} <- validate_get_author_feed(params) do
      client
      |> Client.query(
        "app.bsky.feed.getAuthorFeed",
        Runtime.encode_query_params(validated, @fields_get_author_feed)
      )
    end
  end

  defp validate_get_author_feed(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_author_feed)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])
    {f_filter, e3} = Runtime.get_string(attrs, :filter, "filter", default: "posts_with_replies")

    {f_include_pins, e4} =
      Runtime.get_boolean(attrs, :include_pins, "includePins", default: false)

    {f_limit, e5} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5

    if errors == [] do
      {:ok,
       %{
         actor: f_actor,
         cursor: f_cursor,
         filter: f_filter,
         include_pins: f_include_pins,
         limit: f_limit
       }}
    else
      {:error, errors}
    end
  end

  @fields_get_feed %{cursor: "cursor", feed: "feed", limit: "limit"}

  @doc """
    Get a hydrated feed from an actor's selected feed generator. Implemented by App View.

    ## Parameters

    - `cursor` (string, optional)
    - `feed` (string, required)
    - `limit` (integer, optional)

  """
  @spec get_feed(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_feed(client, params \\ []) do
    with {:ok, validated} <- validate_get_feed(params) do
      client
      |> Client.query(
        "app.bsky.feed.getFeed",
        Runtime.encode_query_params(validated, @fields_get_feed)
      )
    end
  end

  defp validate_get_feed(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_feed)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])
    {f_feed, e2} = Runtime.get_string(attrs, :feed, "feed", required: true, format: "at-uri")

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, feed: f_feed, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_feed_generator %{feed: "feed"}

  @doc """
    Get information about a feed generator. Implemented by AppView.

    ## Parameters

    - `feed` (string, required): AT-URI of the feed generator record.

  """
  @spec get_feed_generator(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_feed_generator(client, params \\ []) do
    with {:ok, validated} <- validate_get_feed_generator(params) do
      client
      |> Client.query(
        "app.bsky.feed.getFeedGenerator",
        Runtime.encode_query_params(validated, @fields_get_feed_generator)
      )
    end
  end

  defp validate_get_feed_generator(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_feed_generator)

    {f_feed, e1} = Runtime.get_string(attrs, :feed, "feed", required: true, format: "at-uri")

    errors = e1

    if errors == [] do
      {:ok, %{feed: f_feed}}
    else
      {:error, errors}
    end
  end

  @fields_get_feed_generators %{feeds: "feeds"}

  @doc """
    Get information about a list of feed generators.

    ## Parameters

    - `feeds` (array, required)

  """
  @spec get_feed_generators(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_feed_generators(client, params \\ []) do
    with {:ok, validated} <- validate_get_feed_generators(params) do
      client
      |> Client.query(
        "app.bsky.feed.getFeedGenerators",
        Runtime.encode_query_params(validated, @fields_get_feed_generators)
      )
    end
  end

  defp validate_get_feed_generators(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_feed_generators)

    {f_feeds, e1} =
      Runtime.get_array(attrs, :feeds, "feeds", [required: true], fn v, path ->
        Runtime.item_string(v, path, format: "at-uri")
      end)

    errors = e1

    if errors == [] do
      {:ok, %{feeds: f_feeds}}
    else
      {:error, errors}
    end
  end

  @fields_get_feed_skeleton %{cursor: "cursor", feed: "feed", limit: "limit"}

  @doc """
    Get a skeleton of a feed provided by a feed generator. Auth is optional, depending on provider requirements, and provides the DID of the requester. Implemented by Feed Generator Service.

    ## Parameters

    - `cursor` (string, optional)
    - `feed` (string, required): Reference to feed generator record describing the specific feed being requested.
    - `limit` (integer, optional)

  """
  @spec get_feed_skeleton(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_feed_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_feed_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.feed.getFeedSkeleton",
        Runtime.encode_query_params(validated, @fields_get_feed_skeleton)
      )
    end
  end

  defp validate_get_feed_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_feed_skeleton)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])
    {f_feed, e2} = Runtime.get_string(attrs, :feed, "feed", required: true, format: "at-uri")

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, feed: f_feed, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_likes %{cid: "cid", cursor: "cursor", limit: "limit", uri: "uri"}

  @doc """
    Get like records which reference a subject (by AT-URI and CID).

    ## Parameters

    - `cid` (string, optional): CID of the subject record (aka, specific version of record), to filter likes.
    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `uri` (string, required): AT-URI of the subject (eg, a post record).

  """
  @spec get_likes(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_likes(client, params \\ []) do
    with {:ok, validated} <- validate_get_likes(params) do
      client
      |> Client.query(
        "app.bsky.feed.getLikes",
        Runtime.encode_query_params(validated, @fields_get_likes)
      )
    end
  end

  defp validate_get_likes(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_likes)

    {f_cid, e1} = Runtime.get_string(attrs, :cid, "cid", format: "cid")
    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_uri, e4} = Runtime.get_string(attrs, :uri, "uri", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{cid: f_cid, cursor: f_cursor, limit: f_limit, uri: f_uri}}
    else
      {:error, errors}
    end
  end

  @fields_get_list_feed %{cursor: "cursor", limit: "limit", list: "list"}

  @doc """
    Get a feed of recent posts from a list (posts and reposts from any actors on the list). Does not require auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `list` (string, required): Reference (AT-URI) to the list record.

  """
  @spec get_list_feed(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_list_feed(client, params \\ []) do
    with {:ok, validated} <- validate_get_list_feed(params) do
      client
      |> Client.query(
        "app.bsky.feed.getListFeed",
        Runtime.encode_query_params(validated, @fields_get_list_feed)
      )
    end
  end

  defp validate_get_list_feed(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_list_feed)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_list, e3} = Runtime.get_string(attrs, :list, "list", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, list: f_list}}
    else
      {:error, errors}
    end
  end

  @fields_get_post_thread %{depth: "depth", parent_height: "parentHeight", uri: "uri"}

  @doc """
    Get posts in a thread. Does not require auth, but additional metadata and filtering will be applied for authed requests.

    ## Parameters

    - `depth` (integer, optional): How many levels of reply depth should be included in response.
    - `parentHeight` (integer, optional): How many levels of parent (and grandparent, etc) post to include.
    - `uri` (string, required): Reference (AT-URI) to post record.

  """
  @spec get_post_thread(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_post_thread(client, params \\ []) do
    with {:ok, validated} <- validate_get_post_thread(params) do
      client
      |> Client.query(
        "app.bsky.feed.getPostThread",
        Runtime.encode_query_params(validated, @fields_get_post_thread)
      )
    end
  end

  defp validate_get_post_thread(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_post_thread)

    {f_depth, e1} =
      Runtime.get_integer(attrs, :depth, "depth", minimum: 0, maximum: 1000, default: 6)

    {f_parent_height, e2} =
      Runtime.get_integer(attrs, :parent_height, "parentHeight",
        minimum: 0,
        maximum: 1000,
        default: 80
      )

    {f_uri, e3} = Runtime.get_string(attrs, :uri, "uri", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{depth: f_depth, parent_height: f_parent_height, uri: f_uri}}
    else
      {:error, errors}
    end
  end

  @fields_get_posts %{uris: "uris"}

  @doc """
    Gets post views for a specified list of posts (by AT-URI). This is sometimes referred to as 'hydrating' a 'feed skeleton'.

    ## Parameters

    - `uris` (array, required): List of post AT-URIs to return hydrated views for.

  """
  @spec get_posts(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_posts(client, params \\ []) do
    with {:ok, validated} <- validate_get_posts(params) do
      client
      |> Client.query(
        "app.bsky.feed.getPosts",
        Runtime.encode_query_params(validated, @fields_get_posts)
      )
    end
  end

  defp validate_get_posts(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_posts)

    {f_uris, e1} =
      Runtime.get_array(attrs, :uris, "uris", [required: true, max_length: 25], fn v, path ->
        Runtime.item_string(v, path, format: "at-uri")
      end)

    errors = e1

    if errors == [] do
      {:ok, %{uris: f_uris}}
    else
      {:error, errors}
    end
  end

  @fields_get_quotes %{cid: "cid", cursor: "cursor", limit: "limit", uri: "uri"}

  @doc """
    Get a list of quotes for a given post.

    ## Parameters

    - `cid` (string, optional): If supplied, filters to quotes of specific version (by CID) of the post record.
    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `uri` (string, required): Reference (AT-URI) of post record

  """
  @spec get_quotes(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_quotes(client, params \\ []) do
    with {:ok, validated} <- validate_get_quotes(params) do
      client
      |> Client.query(
        "app.bsky.feed.getQuotes",
        Runtime.encode_query_params(validated, @fields_get_quotes)
      )
    end
  end

  defp validate_get_quotes(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_quotes)

    {f_cid, e1} = Runtime.get_string(attrs, :cid, "cid", format: "cid")
    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_uri, e4} = Runtime.get_string(attrs, :uri, "uri", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{cid: f_cid, cursor: f_cursor, limit: f_limit, uri: f_uri}}
    else
      {:error, errors}
    end
  end

  @fields_get_reposted_by %{cid: "cid", cursor: "cursor", limit: "limit", uri: "uri"}

  @doc """
    Get a list of reposts for a given post.

    ## Parameters

    - `cid` (string, optional): If supplied, filters to reposts of specific version (by CID) of the post record.
    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `uri` (string, required): Reference (AT-URI) of post record

  """
  @spec get_reposted_by(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_reposted_by(client, params \\ []) do
    with {:ok, validated} <- validate_get_reposted_by(params) do
      client
      |> Client.query(
        "app.bsky.feed.getRepostedBy",
        Runtime.encode_query_params(validated, @fields_get_reposted_by)
      )
    end
  end

  defp validate_get_reposted_by(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_reposted_by)

    {f_cid, e1} = Runtime.get_string(attrs, :cid, "cid", format: "cid")
    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_uri, e4} = Runtime.get_string(attrs, :uri, "uri", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{cid: f_cid, cursor: f_cursor, limit: f_limit, uri: f_uri}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_feeds %{cursor: "cursor", limit: "limit"}

  @doc """
    Get a list of suggested feeds (feed generators) for the requesting account.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_suggested_feeds(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_suggested_feeds(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_feeds(params) do
      client
      |> Client.query(
        "app.bsky.feed.getSuggestedFeeds",
        Runtime.encode_query_params(validated, @fields_get_suggested_feeds)
      )
    end
  end

  defp validate_get_suggested_feeds(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_feeds)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_timeline %{algorithm: "algorithm", cursor: "cursor", limit: "limit"}

  @doc """
    Get a view of the requesting account's home timeline. This is expected to be some form of reverse-chronological feed.

    ## Parameters

    - `algorithm` (string, optional): Variant 'algorithm' for timeline. Implementation-specific. NOTE: most feed flexibility has been moved to feed generator mechanism.
    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_timeline(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_timeline(client, params \\ []) do
    with {:ok, validated} <- validate_get_timeline(params) do
      client
      |> Client.query(
        "app.bsky.feed.getTimeline",
        Runtime.encode_query_params(validated, @fields_get_timeline)
      )
    end
  end

  defp validate_get_timeline(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_timeline)

    {f_algorithm, e1} = Runtime.get_string(attrs, :algorithm, "algorithm", [])
    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{algorithm: f_algorithm, cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_search_posts %{
    author: "author",
    cursor: "cursor",
    domain: "domain",
    lang: "lang",
    limit: "limit",
    mentions: "mentions",
    q: "q",
    since: "since",
    sort: "sort",
    tag: "tag",
    until: "until",
    url: "url"
  }

  @doc """
    Find posts matching search criteria, returning views of those posts. Note that this API endpoint may require authentication (eg, not public) for some service providers and implementations.

    ## Parameters

    - `author` (string, optional): Filter to posts by the given account. Handles are resolved to DID before query-time.
    - `cursor` (string, optional): Optional pagination mechanism; may not necessarily allow scrolling through entire result set.
    - `domain` (string, optional): Filter to posts with URLs (facet links or embeds) linking to the given domain (hostname). Server may apply hostname normalization.
    - `lang` (string, optional): Filter to posts in the given language. Expected to be based on post language field, though server may override language detection.
    - `limit` (integer, optional)
    - `mentions` (string, optional): Filter to posts which mention the given account. Handles are resolved to DID before query-time. Only matches rich-text facet mentions.
    - `q` (string, required): Search query string; syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
    - `since` (string, optional): Filter results for posts after the indicated datetime (inclusive). Expected to use 'sortAt' timestamp, which may not match 'createdAt'. Can be a datetime, or just an ISO date (YYYY-MM-DD).
    - `sort` (string, optional): Specifies the ranking order of results.
    - `tag` (array, optional): Filter to posts with the given tag (hashtag), based on rich-text facet or tag field. Do not include the hash (#) prefix. Multiple tags can be specified, with 'AND' matching.
    - `until` (string, optional): Filter results for posts before the indicated datetime (not inclusive). Expected to use 'sortAt' timestamp, which may not match 'createdAt'. Can be a datetime, or just an ISO date (YYY-MM-DD).
    - `url` (string, optional): Filter to posts with links (facet links or embeds) pointing to this URL. Server may apply URL normalization or fuzzy matching.

  """
  @spec search_posts(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_posts(client, params \\ []) do
    with {:ok, validated} <- validate_search_posts(params) do
      client
      |> Client.query(
        "app.bsky.feed.searchPosts",
        Runtime.encode_query_params(validated, @fields_search_posts)
      )
    end
  end

  defp validate_search_posts(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_posts)

    {f_author, e1} = Runtime.get_string(attrs, :author, "author", format: "at-identifier")
    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])
    {f_domain, e3} = Runtime.get_string(attrs, :domain, "domain", [])
    {f_lang, e4} = Runtime.get_string(attrs, :lang, "lang", format: "language")

    {f_limit, e5} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_mentions, e6} = Runtime.get_string(attrs, :mentions, "mentions", format: "at-identifier")
    {f_q, e7} = Runtime.get_string(attrs, :q, "q", required: true)
    {f_since, e8} = Runtime.get_string(attrs, :since, "since", [])
    {f_sort, e9} = Runtime.get_string(attrs, :sort, "sort", default: "latest")

    {f_tag, e10} =
      Runtime.get_array(attrs, :tag, "tag", [], fn v, path ->
        Runtime.item_string(v, path, max_length: 640, max_graphemes: 64)
      end)

    {f_until, e11} = Runtime.get_string(attrs, :until, "until", [])
    {f_url, e12} = Runtime.get_string(attrs, :url, "url", format: "uri")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8 ++ e9 ++ e10 ++ e11 ++ e12

    if errors == [] do
      {:ok,
       %{
         author: f_author,
         cursor: f_cursor,
         domain: f_domain,
         lang: f_lang,
         limit: f_limit,
         mentions: f_mentions,
         q: f_q,
         since: f_since,
         sort: f_sort,
         tag: f_tag,
         until: f_until,
         url: f_url
       }}
    else
      {:error, errors}
    end
  end

  @fields_search_posts_v2 %{
    all_time: "allTime",
    authors: "authors",
    cursor: "cursor",
    domains: "domains",
    embedded_at_uris: "embeddedAtUris",
    exclude_authors: "excludeAuthors",
    exclude_domains: "excludeDomains",
    exclude_embedded_at_uris: "excludeEmbeddedAtUris",
    exclude_hashtags: "excludeHashtags",
    exclude_languages: "excludeLanguages",
    exclude_mentions: "excludeMentions",
    exclude_replies: "excludeReplies",
    exclude_urls: "excludeUrls",
    following: "following",
    has_media: "hasMedia",
    has_video: "hasVideo",
    hashtags: "hashtags",
    languages: "languages",
    limit: "limit",
    mentions: "mentions",
    query: "query",
    query_language: "queryLanguage",
    replies_only: "repliesOnly",
    reply_parent_uri: "replyParentUri",
    since: "since",
    sort: "sort",
    thread_root_uri: "threadRootUri",
    until: "until",
    urls: "urls"
  }

  @doc """
    Find posts matching a search query or filters, returning search hits for matching post records.

    ## Parameters

    - `allTime` (boolean, optional): Search the full index instead of the recent-post window.
    - `authors` (array, optional): Include posts by any of these authors. Handles are resolved to DIDs before searching.
    - `cursor` (string, optional): Optional pagination cursor.
    - `domains` (array, optional): Include posts that link to any of these domains.
    - `embeddedAtUris` (array, optional): Include posts that embed any of these AT URIs.
    - `excludeAuthors` (array, optional): Exclude posts by any of these authors. Handles are resolved to DIDs before searching.
    - `excludeDomains` (array, optional): Exclude posts that link to any of these domains.
    - `excludeEmbeddedAtUris` (array, optional): Exclude posts that embed any of these AT URIs.
    - `excludeHashtags` (array, optional): Exclude posts tagged with any of these hashtags. Do not include the hash (#) prefix.
    - `excludeLanguages` (array, optional): Exclude posts whose language matches any of these language codes.
    - `excludeMentions` (array, optional): Exclude posts that mention any of these accounts. Handles are resolved to DIDs before searching.
    - `excludeReplies` (boolean, optional): Exclude replies from results. Mutually exclusive with repliesOnly.
    - `excludeUrls` (array, optional): Exclude posts that link to any of these URLs.
    - `following` (boolean, optional): Include only posts from accounts followed by the viewer.
    - `hasMedia` (boolean, optional): Include only posts with media.
    - `hasVideo` (boolean, optional): Include only posts with video.
    - `hashtags` (array, optional): Include posts tagged with any of these hashtags. Do not include the hash (#) prefix.
    - `languages` (array, optional): Include posts whose language matches any of these language codes.
    - `limit` (integer, optional): Maximum number of results to return.
    - `mentions` (array, optional): Include posts that mention any of these accounts. Handles are resolved to DIDs before searching.
    - `query` (string, optional): Search query string. A query or at least one filter is required.
    - `queryLanguage` (string, optional): Language analyzer hint for the query text. If unset, the server auto-detects when possible.
    - `repliesOnly` (boolean, optional): Include only replies. Mutually exclusive with excludeReplies.
    - `replyParentUri` (string, optional): Include only direct replies to this parent post URI.
    - `since` (string, optional): Include posts indexed at or after this timestamp. Can be a datetime, or just an ISO date (YYYY-MM-DD).
    - `sort` (string, optional): Ranking order for results. 'recent' sorts by recency; 'top' uses search ranking.
    - `threadRootUri` (string, optional): Include only posts in the thread rooted at this post URI.
    - `until` (string, optional): Include posts indexed before this timestamp. Defaults to the current time. Can be a datetime, or just an ISO date (YYYY-MM-DD).
    - `urls` (array, optional): Include posts that link to any of these URLs.

  """
  @spec search_posts_v2(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_posts_v2(client, params \\ []) do
    with {:ok, validated} <- validate_search_posts_v2(params) do
      client
      |> Client.query(
        "app.bsky.feed.searchPostsV2",
        Runtime.encode_query_params(validated, @fields_search_posts_v2)
      )
    end
  end

  defp validate_search_posts_v2(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_posts_v2)

    {f_all_time, e1} = Runtime.get_boolean(attrs, :all_time, "allTime", [])

    {f_authors, e2} =
      Runtime.get_array(attrs, :authors, "authors", [], fn v, path ->
        Runtime.item_string(v, path, format: "at-identifier")
      end)

    {f_cursor, e3} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_domains, e4} =
      Runtime.get_array(attrs, :domains, "domains", [], fn v, path ->
        Runtime.item_string(v, path, [])
      end)

    {f_embedded_at_uris, e5} =
      Runtime.get_array(attrs, :embedded_at_uris, "embeddedAtUris", [], fn v, path ->
        Runtime.item_string(v, path, format: "at-uri")
      end)

    {f_exclude_authors, e6} =
      Runtime.get_array(attrs, :exclude_authors, "excludeAuthors", [], fn v, path ->
        Runtime.item_string(v, path, format: "at-identifier")
      end)

    {f_exclude_domains, e7} =
      Runtime.get_array(attrs, :exclude_domains, "excludeDomains", [], fn v, path ->
        Runtime.item_string(v, path, [])
      end)

    {f_exclude_embedded_at_uris, e8} =
      Runtime.get_array(attrs, :exclude_embedded_at_uris, "excludeEmbeddedAtUris", [], fn v,
                                                                                          path ->
        Runtime.item_string(v, path, format: "at-uri")
      end)

    {f_exclude_hashtags, e9} =
      Runtime.get_array(attrs, :exclude_hashtags, "excludeHashtags", [], fn v, path ->
        Runtime.item_string(v, path, max_length: 640, max_graphemes: 64)
      end)

    {f_exclude_languages, e10} =
      Runtime.get_array(attrs, :exclude_languages, "excludeLanguages", [], fn v, path ->
        Runtime.item_string(v, path, format: "language")
      end)

    {f_exclude_mentions, e11} =
      Runtime.get_array(attrs, :exclude_mentions, "excludeMentions", [], fn v, path ->
        Runtime.item_string(v, path, format: "at-identifier")
      end)

    {f_exclude_replies, e12} = Runtime.get_boolean(attrs, :exclude_replies, "excludeReplies", [])

    {f_exclude_urls, e13} =
      Runtime.get_array(attrs, :exclude_urls, "excludeUrls", [], fn v, path ->
        Runtime.item_string(v, path, format: "uri")
      end)

    {f_following, e14} = Runtime.get_boolean(attrs, :following, "following", [])
    {f_has_media, e15} = Runtime.get_boolean(attrs, :has_media, "hasMedia", [])
    {f_has_video, e16} = Runtime.get_boolean(attrs, :has_video, "hasVideo", [])

    {f_hashtags, e17} =
      Runtime.get_array(attrs, :hashtags, "hashtags", [], fn v, path ->
        Runtime.item_string(v, path, max_length: 640, max_graphemes: 64)
      end)

    {f_languages, e18} =
      Runtime.get_array(attrs, :languages, "languages", [], fn v, path ->
        Runtime.item_string(v, path, format: "language")
      end)

    {f_limit, e19} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_mentions, e20} =
      Runtime.get_array(attrs, :mentions, "mentions", [], fn v, path ->
        Runtime.item_string(v, path, format: "at-identifier")
      end)

    {f_query, e21} = Runtime.get_string(attrs, :query, "query", [])
    {f_query_language, e22} = Runtime.get_string(attrs, :query_language, "queryLanguage", [])
    {f_replies_only, e23} = Runtime.get_boolean(attrs, :replies_only, "repliesOnly", [])

    {f_reply_parent_uri, e24} =
      Runtime.get_string(attrs, :reply_parent_uri, "replyParentUri", format: "at-uri")

    {f_since, e25} = Runtime.get_string(attrs, :since, "since", [])
    {f_sort, e26} = Runtime.get_string(attrs, :sort, "sort", [])

    {f_thread_root_uri, e27} =
      Runtime.get_string(attrs, :thread_root_uri, "threadRootUri", format: "at-uri")

    {f_until, e28} = Runtime.get_string(attrs, :until, "until", [])

    {f_urls, e29} =
      Runtime.get_array(attrs, :urls, "urls", [], fn v, path ->
        Runtime.item_string(v, path, format: "uri")
      end)

    errors =
      e1 ++
        e2 ++
        e3 ++
        e4 ++
        e5 ++
        e6 ++
        e7 ++
        e8 ++
        e9 ++
        e10 ++
        e11 ++
        e12 ++
        e13 ++
        e14 ++
        e15 ++
        e16 ++
        e17 ++ e18 ++ e19 ++ e20 ++ e21 ++ e22 ++ e23 ++ e24 ++ e25 ++ e26 ++ e27 ++ e28 ++ e29

    if errors == [] do
      {:ok,
       %{
         all_time: f_all_time,
         authors: f_authors,
         cursor: f_cursor,
         domains: f_domains,
         embedded_at_uris: f_embedded_at_uris,
         exclude_authors: f_exclude_authors,
         exclude_domains: f_exclude_domains,
         exclude_embedded_at_uris: f_exclude_embedded_at_uris,
         exclude_hashtags: f_exclude_hashtags,
         exclude_languages: f_exclude_languages,
         exclude_mentions: f_exclude_mentions,
         exclude_replies: f_exclude_replies,
         exclude_urls: f_exclude_urls,
         following: f_following,
         has_media: f_has_media,
         has_video: f_has_video,
         hashtags: f_hashtags,
         languages: f_languages,
         limit: f_limit,
         mentions: f_mentions,
         query: f_query,
         query_language: f_query_language,
         replies_only: f_replies_only,
         reply_parent_uri: f_reply_parent_uri,
         since: f_since,
         sort: f_sort,
         thread_root_uri: f_thread_root_uri,
         until: f_until,
         urls: f_urls
       }}
    else
      {:error, errors}
    end
  end

  @doc """
    Send information about interactions with feed items back to the feed generator that served them.
  """
  @spec send_interactions(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def send_interactions(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.feed.sendInteractions", body)
  end
end