# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Graph do
  @moduledoc """
  XRPC client functions for the `app.bsky.graph` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `get_actor_starter_packs` — query: app.bsky.graph.getActorStarterPacks
  - `get_blocks` — query: app.bsky.graph.getBlocks
  - `get_followers` — query: app.bsky.graph.getFollowers
  - `get_follows` — query: app.bsky.graph.getFollows
  - `get_known_followers` — query: app.bsky.graph.getKnownFollowers
  - `get_list` — query: app.bsky.graph.getList
  - `get_list_blocks` — query: app.bsky.graph.getListBlocks
  - `get_list_mutes` — query: app.bsky.graph.getListMutes
  - `get_lists` — query: app.bsky.graph.getLists
  - `get_lists_with_membership` — query: app.bsky.graph.getListsWithMembership
  - `get_mutes` — query: app.bsky.graph.getMutes
  - `get_relationships` — query: app.bsky.graph.getRelationships
  - `get_starter_pack` — query: app.bsky.graph.getStarterPack
  - `get_starter_packs` — query: app.bsky.graph.getStarterPacks
  - `get_starter_packs_with_membership` — query: app.bsky.graph.getStarterPacksWithMembership
  - `get_suggested_follows_by_actor` — query: app.bsky.graph.getSuggestedFollowsByActor
  - `mute_actor` — procedure: app.bsky.graph.muteActor
  - `mute_actor_list` — procedure: app.bsky.graph.muteActorList
  - `mute_thread` — procedure: app.bsky.graph.muteThread
  - `search_starter_packs` — query: app.bsky.graph.searchStarterPacks
  - `search_starter_packs_v2` — query: app.bsky.graph.searchStarterPacksV2
  - `unmute_actor` — procedure: app.bsky.graph.unmuteActor
  - `unmute_actor_list` — procedure: app.bsky.graph.unmuteActorList
  - `unmute_thread` — procedure: app.bsky.graph.unmuteThread
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @fields_get_actor_starter_packs %{actor: "actor", cursor: "cursor", limit: "limit"}

  @doc """
    Get a list of starter packs created by the actor.

    ## Parameters

    - `actor` (string, required)
    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_actor_starter_packs(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_actor_starter_packs(client, params \\ []) do
    with {:ok, validated} <- validate_get_actor_starter_packs(params) do
      client
      |> Client.query(
        "app.bsky.graph.getActorStarterPacks",
        Runtime.encode_query_params(validated, @fields_get_actor_starter_packs)
      )
    end
  end

  defp validate_get_actor_starter_packs(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_actor_starter_packs)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_blocks %{cursor: "cursor", limit: "limit"}

  @doc """
    Enumerates which accounts the requesting account is currently blocking. Requires auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_blocks(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_blocks(client, params \\ []) do
    with {:ok, validated} <- validate_get_blocks(params) do
      client
      |> Client.query(
        "app.bsky.graph.getBlocks",
        Runtime.encode_query_params(validated, @fields_get_blocks)
      )
    end
  end

  defp validate_get_blocks(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_blocks)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_followers %{actor: "actor", cursor: "cursor", limit: "limit", sort: "sort"}

  @doc """
    Enumerates accounts which follow a specified account (actor).

    ## Parameters

    - `actor` (string, required)
    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `sort` (string, optional)

  """
  @spec get_followers(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_followers(client, params \\ []) do
    with {:ok, validated} <- validate_get_followers(params) do
      client
      |> Client.query(
        "app.bsky.graph.getFollowers",
        Runtime.encode_query_params(validated, @fields_get_followers)
      )
    end
  end

  defp validate_get_followers(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_followers)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_sort, e4} = Runtime.get_string(attrs, :sort, "sort", [])

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit, sort: f_sort}}
    else
      {:error, errors}
    end
  end

  @fields_get_follows %{actor: "actor", cursor: "cursor", limit: "limit", sort: "sort"}

  @doc """
    Enumerates accounts which a specified account (actor) follows.

    ## Parameters

    - `actor` (string, required)
    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `sort` (string, optional)

  """
  @spec get_follows(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_follows(client, params \\ []) do
    with {:ok, validated} <- validate_get_follows(params) do
      client
      |> Client.query(
        "app.bsky.graph.getFollows",
        Runtime.encode_query_params(validated, @fields_get_follows)
      )
    end
  end

  defp validate_get_follows(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_follows)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_sort, e4} = Runtime.get_string(attrs, :sort, "sort", [])

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit, sort: f_sort}}
    else
      {:error, errors}
    end
  end

  @fields_get_known_followers %{actor: "actor", cursor: "cursor", limit: "limit"}

  @doc """
    Enumerates accounts which follow a specified account (actor) and are followed by the viewer.

    ## Parameters

    - `actor` (string, required)
    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_known_followers(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_known_followers(client, params \\ []) do
    with {:ok, validated} <- validate_get_known_followers(params) do
      client
      |> Client.query(
        "app.bsky.graph.getKnownFollowers",
        Runtime.encode_query_params(validated, @fields_get_known_followers)
      )
    end
  end

  defp validate_get_known_followers(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_known_followers)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_list %{cursor: "cursor", limit: "limit", list: "list"}

  @doc """
    Gets a 'view' (with additional context) of a specified list.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `list` (string, required): Reference (AT-URI) of the list record to hydrate.

  """
  @spec get_list(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_list(client, params \\ []) do
    with {:ok, validated} <- validate_get_list(params) do
      client
      |> Client.query(
        "app.bsky.graph.getList",
        Runtime.encode_query_params(validated, @fields_get_list)
      )
    end
  end

  defp validate_get_list(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_list)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_list, e3} = Runtime.get_string(attrs, :list, "list", required: true, format: "at-uri")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, list: f_list}}
    else
      {:error, errors}
    end
  end

  @fields_get_list_blocks %{cursor: "cursor", limit: "limit"}

  @doc """
    Get mod lists that the requesting account (actor) is blocking. Requires auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_list_blocks(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_list_blocks(client, params \\ []) do
    with {:ok, validated} <- validate_get_list_blocks(params) do
      client
      |> Client.query(
        "app.bsky.graph.getListBlocks",
        Runtime.encode_query_params(validated, @fields_get_list_blocks)
      )
    end
  end

  defp validate_get_list_blocks(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_list_blocks)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_list_mutes %{cursor: "cursor", limit: "limit"}

  @doc """
    Enumerates mod lists that the requesting account (actor) currently has muted. Requires auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_list_mutes(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_list_mutes(client, params \\ []) do
    with {:ok, validated} <- validate_get_list_mutes(params) do
      client
      |> Client.query(
        "app.bsky.graph.getListMutes",
        Runtime.encode_query_params(validated, @fields_get_list_mutes)
      )
    end
  end

  defp validate_get_list_mutes(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_list_mutes)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_lists %{actor: "actor", cursor: "cursor", limit: "limit", purposes: "purposes"}

  @doc """
    Enumerates the lists created by a specified account (actor).

    ## Parameters

    - `actor` (string, required): The account (actor) to enumerate lists from.
    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `purposes` (array, optional): Optional filter by list purpose. If not specified, all supported types are returned.

  """
  @spec get_lists(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_lists(client, params \\ []) do
    with {:ok, validated} <- validate_get_lists(params) do
      client
      |> Client.query(
        "app.bsky.graph.getLists",
        Runtime.encode_query_params(validated, @fields_get_lists)
      )
    end
  end

  defp validate_get_lists(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_lists)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_purposes, e4} =
      Runtime.get_array(attrs, :purposes, "purposes", [], fn v, path ->
        Runtime.item_string(v, path, [])
      end)

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit, purposes: f_purposes}}
    else
      {:error, errors}
    end
  end

  @fields_get_lists_with_membership %{
    actor: "actor",
    cursor: "cursor",
    limit: "limit",
    purposes: "purposes"
  }

  @doc """
    Enumerates the lists created by the session user, and includes membership information about `actor` in those lists. Only supports curation and moderation lists (no reference lists, used in starter packs). Requires auth.

    ## Parameters

    - `actor` (string, required): The account (actor) to check for membership.
    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `purposes` (array, optional): Optional filter by list purpose. If not specified, all supported types are returned.

  """
  @spec get_lists_with_membership(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_lists_with_membership(client, params \\ []) do
    with {:ok, validated} <- validate_get_lists_with_membership(params) do
      client
      |> Client.query(
        "app.bsky.graph.getListsWithMembership",
        Runtime.encode_query_params(validated, @fields_get_lists_with_membership)
      )
    end
  end

  defp validate_get_lists_with_membership(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_lists_with_membership)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_purposes, e4} =
      Runtime.get_array(attrs, :purposes, "purposes", [], fn v, path ->
        Runtime.item_string(v, path, [])
      end)

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit, purposes: f_purposes}}
    else
      {:error, errors}
    end
  end

  @fields_get_mutes %{cursor: "cursor", limit: "limit"}

  @doc """
    Enumerates accounts that the requesting account (actor) currently has fully muted. Mutes scoped to specific kinds of content (only reposts, only quote posts) are not included. Responses may contain more items than the requested limit. Requires auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_mutes(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_mutes(client, params \\ []) do
    with {:ok, validated} <- validate_get_mutes(params) do
      client
      |> Client.query(
        "app.bsky.graph.getMutes",
        Runtime.encode_query_params(validated, @fields_get_mutes)
      )
    end
  end

  defp validate_get_mutes(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_mutes)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_relationships %{actor: "actor", others: "others"}

  @doc """
    Enumerates public relationships between one account, and a list of other accounts. Does not require auth.

    ## Parameters

    - `actor` (string, required): Primary account requesting relationships for.
    - `others` (array, optional): List of 'other' accounts to be related back to the primary.

  """
  @spec get_relationships(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_relationships(client, params \\ []) do
    with {:ok, validated} <- validate_get_relationships(params) do
      client
      |> Client.query(
        "app.bsky.graph.getRelationships",
        Runtime.encode_query_params(validated, @fields_get_relationships)
      )
    end
  end

  defp validate_get_relationships(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_relationships)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_others, e2} =
      Runtime.get_array(attrs, :others, "others", [max_length: 30], fn v, path ->
        Runtime.item_string(v, path, format: "at-identifier")
      end)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{actor: f_actor, others: f_others}}
    else
      {:error, errors}
    end
  end

  @fields_get_starter_pack %{starter_pack: "starterPack"}

  @doc """
    Gets a view of a starter pack.

    ## Parameters

    - `starterPack` (string, required): Reference (AT-URI) of the starter pack record.

  """
  @spec get_starter_pack(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_starter_pack(client, params \\ []) do
    with {:ok, validated} <- validate_get_starter_pack(params) do
      client
      |> Client.query(
        "app.bsky.graph.getStarterPack",
        Runtime.encode_query_params(validated, @fields_get_starter_pack)
      )
    end
  end

  defp validate_get_starter_pack(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_starter_pack)

    {f_starter_pack, e1} =
      Runtime.get_string(attrs, :starter_pack, "starterPack", required: true, format: "at-uri")

    errors = e1

    if errors == [] do
      {:ok, %{starter_pack: f_starter_pack}}
    else
      {:error, errors}
    end
  end

  @fields_get_starter_packs %{uris: "uris"}

  @doc """
    Get views for a list of starter packs.

    ## Parameters

    - `uris` (array, required)

  """
  @spec get_starter_packs(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_starter_packs(client, params \\ []) do
    with {:ok, validated} <- validate_get_starter_packs(params) do
      client
      |> Client.query(
        "app.bsky.graph.getStarterPacks",
        Runtime.encode_query_params(validated, @fields_get_starter_packs)
      )
    end
  end

  defp validate_get_starter_packs(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_starter_packs)

    {f_uris, e1} =
      Runtime.get_array(attrs, :uris, "uris", [required: true, max_length: 25], fn v, path ->
        Runtime.item_string(v, path, format: "at-uri")
      end)

    errors = e1

    if errors == [] do
      {:ok, %{uris: f_uris}}
    else
      {:error, errors}
    end
  end

  @fields_get_starter_packs_with_membership %{actor: "actor", cursor: "cursor", limit: "limit"}

  @doc """
    Enumerates the starter packs created by the session user, and includes membership information about `actor` in those starter packs. Requires auth.

    ## Parameters

    - `actor` (string, required): The account (actor) to check for membership.
    - `cursor` (string, optional)
    - `limit` (integer, optional)

  """
  @spec get_starter_packs_with_membership(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_starter_packs_with_membership(client, params \\ []) do
    with {:ok, validated} <- validate_get_starter_packs_with_membership(params) do
      client
      |> Client.query(
        "app.bsky.graph.getStarterPacksWithMembership",
        Runtime.encode_query_params(validated, @fields_get_starter_packs_with_membership)
      )
    end
  end

  defp validate_get_starter_packs_with_membership(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_starter_packs_with_membership)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e3} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{actor: f_actor, cursor: f_cursor, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_follows_by_actor %{actor: "actor"}

  @doc """
    Enumerates follows similar to a given account (actor). Expected use is to recommend additional accounts immediately after following one account.

    ## Parameters

    - `actor` (string, required)

  """
  @spec get_suggested_follows_by_actor(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_follows_by_actor(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_follows_by_actor(params) do
      client
      |> Client.query(
        "app.bsky.graph.getSuggestedFollowsByActor",
        Runtime.encode_query_params(validated, @fields_get_suggested_follows_by_actor)
      )
    end
  end

  defp validate_get_suggested_follows_by_actor(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_follows_by_actor)

    {f_actor, e1} =
      Runtime.get_string(attrs, :actor, "actor", required: true, format: "at-identifier")

    errors = e1

    if errors == [] do
      {:ok, %{actor: f_actor}}
    else
      {:error, errors}
    end
  end

  @doc """
    Creates a mute relationship for the specified account. If a mute already exists for the account, it is updated in place: the stored scope is replaced with the scope in this request. Mutes are private in Bluesky. Requires auth.
  """
  @spec mute_actor(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def mute_actor(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.graph.muteActor", body)
  end

  @doc """
    Creates a mute relationship for the specified list of accounts. Mutes are private in Bluesky. Requires auth.
  """
  @spec mute_actor_list(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def mute_actor_list(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.graph.muteActorList", body)
  end

  @doc """
    Mutes a thread preventing notifications from the thread and any of its children. Mutes are private in Bluesky. Requires auth.
  """
  @spec mute_thread(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def mute_thread(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.graph.muteThread", body)
  end

  @fields_search_starter_packs %{cursor: "cursor", limit: "limit", q: "q"}

  @doc """
    Find starter packs matching search criteria. Does not require auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `q` (string, required): Search query string. Syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.

  """
  @spec search_starter_packs(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_starter_packs(client, params \\ []) do
    with {:ok, validated} <- validate_search_starter_packs(params) do
      client
      |> Client.query(
        "app.bsky.graph.searchStarterPacks",
        Runtime.encode_query_params(validated, @fields_search_starter_packs)
      )
    end
  end

  defp validate_search_starter_packs(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_starter_packs)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_q, e3} = Runtime.get_string(attrs, :q, "q", required: true)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, q: f_q}}
    else
      {:error, errors}
    end
  end

  @fields_search_starter_packs_v2 %{cursor: "cursor", limit: "limit", q: "q"}

  @doc """
    Find starter packs matching search criteria. Does not require auth.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `q` (string, required): Search query string. Syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.

  """
  @spec search_starter_packs_v2(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_starter_packs_v2(client, params \\ []) do
    with {:ok, validated} <- validate_search_starter_packs_v2(params) do
      client
      |> Client.query(
        "app.bsky.graph.searchStarterPacksV2",
        Runtime.encode_query_params(validated, @fields_search_starter_packs_v2)
      )
    end
  end

  defp validate_search_starter_packs_v2(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_starter_packs_v2)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_q, e3} = Runtime.get_string(attrs, :q, "q", required: true)

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, q: f_q}}
    else
      {:error, errors}
    end
  end

  @doc """
    Unmutes the specified account. Requires auth.
  """
  @spec unmute_actor(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def unmute_actor(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.graph.unmuteActor", body)
  end

  @doc """
    Unmutes the specified list of accounts. Requires auth.
  """
  @spec unmute_actor_list(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def unmute_actor_list(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.graph.unmuteActorList", body)
  end

  @doc """
    Unmutes the specified thread. Requires auth.
  """
  @spec unmute_thread(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def unmute_thread(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.graph.unmuteThread", body)
  end
end