# Generated by `mix exosphere.gen.lexicons` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.lexicons

defmodule Exosphere.Bsky.Labeler do
  @moduledoc """
  XRPC client functions for the `app.bsky.labeler` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `get_services` — query: app.bsky.labeler.getServices
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @fields_get_services %{detailed: "detailed", dids: "dids"}

  @doc """
    Get information about a list of labeler services.

    ## Parameters

    - `detailed` (boolean, optional)
    - `dids` (array, required)

  """
  @spec get_services(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_services(client, params \\ []) do
    with {:ok, validated} <- validate_get_services(params) do
      client
      |> Client.query(
        "app.bsky.labeler.getServices",
        Runtime.encode_query_params(validated, @fields_get_services)
      )
    end
  end

  defp validate_get_services(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_services)

    {f_detailed, e1} = Runtime.get_boolean(attrs, :detailed, "detailed", default: false)

    {f_dids, e2} =
      Runtime.get_array(attrs, :dids, "dids", [required: true], fn v, path ->
        Runtime.item_string(v, path, format: "did")
      end)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{detailed: f_detailed, dids: f_dids}}
    else
      {:error, errors}
    end
  end
end
