# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Unspecced do
  @moduledoc """
  XRPC client functions for the `app.bsky.unspecced` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `get_age_assurance_state` — query: app.bsky.unspecced.getAgeAssuranceState
  - `get_config` — query: app.bsky.unspecced.getConfig
  - `get_onboarding_suggested_starter_packs` — query: app.bsky.unspecced.getOnboardingSuggestedStarterPacks
  - `get_onboarding_suggested_starter_packs_skeleton` — query: app.bsky.unspecced.getOnboardingSuggestedStarterPacksSkeleton
  - `get_onboarding_suggested_users_skeleton` — query: app.bsky.unspecced.getOnboardingSuggestedUsersSkeleton
  - `get_popular_feed_generators` — query: app.bsky.unspecced.getPopularFeedGenerators
  - `get_post_thread_other_v2` — query: app.bsky.unspecced.getPostThreadOtherV2
  - `get_post_thread_v2` — query: app.bsky.unspecced.getPostThreadV2
  - `get_suggested_feeds` — query: app.bsky.unspecced.getSuggestedFeeds
  - `get_suggested_feeds_skeleton` — query: app.bsky.unspecced.getSuggestedFeedsSkeleton
  - `get_suggested_onboarding_users` — query: app.bsky.unspecced.getSuggestedOnboardingUsers
  - `get_suggested_starter_packs` — query: app.bsky.unspecced.getSuggestedStarterPacks
  - `get_suggested_starter_packs_skeleton` — query: app.bsky.unspecced.getSuggestedStarterPacksSkeleton
  - `get_suggested_users` — query: app.bsky.unspecced.getSuggestedUsers
  - `get_suggested_users_for_discover` — query: app.bsky.unspecced.getSuggestedUsersForDiscover
  - `get_suggested_users_for_discover_skeleton` — query: app.bsky.unspecced.getSuggestedUsersForDiscoverSkeleton
  - `get_suggested_users_for_explore` — query: app.bsky.unspecced.getSuggestedUsersForExplore
  - `get_suggested_users_for_explore_skeleton` — query: app.bsky.unspecced.getSuggestedUsersForExploreSkeleton
  - `get_suggested_users_for_see_more` — query: app.bsky.unspecced.getSuggestedUsersForSeeMore
  - `get_suggested_users_for_see_more_skeleton` — query: app.bsky.unspecced.getSuggestedUsersForSeeMoreSkeleton
  - `get_suggested_users_skeleton` — query: app.bsky.unspecced.getSuggestedUsersSkeleton
  - `get_suggestions_skeleton` — query: app.bsky.unspecced.getSuggestionsSkeleton
  - `get_tagged_suggestions` — query: app.bsky.unspecced.getTaggedSuggestions
  - `get_trending_topics` — query: app.bsky.unspecced.getTrendingTopics
  - `get_trends` — query: app.bsky.unspecced.getTrends
  - `get_trends_skeleton` — query: app.bsky.unspecced.getTrendsSkeleton
  - `init_age_assurance` — procedure: app.bsky.unspecced.initAgeAssurance
  - `search_actors_skeleton` — query: app.bsky.unspecced.searchActorsSkeleton
  - `search_posts_skeleton` — query: app.bsky.unspecced.searchPostsSkeleton
  - `search_starter_packs_skeleton` — query: app.bsky.unspecced.searchStarterPacksSkeleton
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @doc """
    Returns the current state of the age assurance process for an account. This is used to check if the user has completed age assurance or if further action is required.
  """
  @spec get_age_assurance_state(Client.t()) :: {:ok, map()} | {:error, term()}
  def get_age_assurance_state(client) do
    client
    |> Client.query("app.bsky.unspecced.getAgeAssuranceState")
  end

  @doc """
    Get miscellaneous runtime configuration.
  """
  @spec get_config(Client.t()) :: {:ok, map()} | {:error, term()}
  def get_config(client) do
    client
    |> Client.query("app.bsky.unspecced.getConfig")
  end

  @fields_get_onboarding_suggested_starter_packs %{limit: "limit"}

  @doc """
    Get a list of suggested starterpacks for onboarding

    ## Parameters

    - `limit` (integer, optional)

  """
  @spec get_onboarding_suggested_starter_packs(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_onboarding_suggested_starter_packs(client, params \\ []) do
    with {:ok, validated} <- validate_get_onboarding_suggested_starter_packs(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getOnboardingSuggestedStarterPacks",
        Runtime.encode_query_params(validated, @fields_get_onboarding_suggested_starter_packs)
      )
    end
  end

  defp validate_get_onboarding_suggested_starter_packs(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_onboarding_suggested_starter_packs)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    errors = e1

    if errors == [] do
      {:ok, %{limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_onboarding_suggested_starter_packs_skeleton %{limit: "limit", viewer: "viewer"}

  @doc """
    Get a skeleton of suggested starterpacks for onboarding. Intended to be called and hydrated by app.bsky.unspecced.getOnboardingSuggestedStarterPacks

    ## Parameters

    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_onboarding_suggested_starter_packs_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_onboarding_suggested_starter_packs_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_onboarding_suggested_starter_packs_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getOnboardingSuggestedStarterPacksSkeleton",
        Runtime.encode_query_params(
          validated,
          @fields_get_onboarding_suggested_starter_packs_skeleton
        )
      )
    end
  end

  defp validate_get_onboarding_suggested_starter_packs_skeleton(params) do
    {attrs, _extra} =
      Runtime.atomize(params, @fields_get_onboarding_suggested_starter_packs_skeleton)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    {f_viewer, e2} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_onboarding_suggested_users_skeleton %{
    category: "category",
    limit: "limit",
    viewer: "viewer"
  }

  @doc """
    Get a skeleton of suggested users for onboarding. Intended to be called and hydrated by app.bsky.unspecced.getSuggestedOnboardingUsers

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_onboarding_suggested_users_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_onboarding_suggested_users_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_onboarding_suggested_users_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getOnboardingSuggestedUsersSkeleton",
        Runtime.encode_query_params(validated, @fields_get_onboarding_suggested_users_skeleton)
      )
    end
  end

  defp validate_get_onboarding_suggested_users_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_onboarding_suggested_users_skeleton)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    {f_viewer, e3} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_popular_feed_generators %{cursor: "cursor", limit: "limit", query: "query"}

  @doc """
    An unspecced view of globally popular feed generators.

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `query` (string, optional)

  """
  @spec get_popular_feed_generators(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_popular_feed_generators(client, params \\ []) do
    with {:ok, validated} <- validate_get_popular_feed_generators(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getPopularFeedGenerators",
        Runtime.encode_query_params(validated, @fields_get_popular_feed_generators)
      )
    end
  end

  defp validate_get_popular_feed_generators(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_popular_feed_generators)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_query, e3} = Runtime.get_string(attrs, :query, "query", [])

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, query: f_query}}
    else
      {:error, errors}
    end
  end

  @fields_get_post_thread_other_v2 %{anchor: "anchor"}

  @doc """
    (NOTE: this endpoint is under development and WILL change without notice. Don't use it until it is moved out of `unspecced` or your application WILL break) Get additional posts under a thread e.g. replies hidden by threadgate. Based on an anchor post at any depth of the tree, returns top-level replies below that anchor. It does not include ancestors nor the anchor itself. This should be called after exhausting `app.bsky.unspecced.getPostThreadV2`. Does not require auth, but additional metadata and filtering will be applied for authed requests.

    ## Parameters

    - `anchor` (string, required): Reference (AT-URI) to post record. This is the anchor post.

  """
  @spec get_post_thread_other_v2(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_post_thread_other_v2(client, params \\ []) do
    with {:ok, validated} <- validate_get_post_thread_other_v2(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getPostThreadOtherV2",
        Runtime.encode_query_params(validated, @fields_get_post_thread_other_v2)
      )
    end
  end

  defp validate_get_post_thread_other_v2(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_post_thread_other_v2)

    {f_anchor, e1} =
      Runtime.get_string(attrs, :anchor, "anchor", required: true, format: "at-uri")

    errors = e1

    if errors == [] do
      {:ok, %{anchor: f_anchor}}
    else
      {:error, errors}
    end
  end

  @fields_get_post_thread_v2 %{
    above: "above",
    anchor: "anchor",
    below: "below",
    branching_factor: "branchingFactor",
    sort: "sort"
  }

  @doc """
    (NOTE: this endpoint is under development and WILL change without notice. Don't use it until it is moved out of `unspecced` or your application WILL break) Get posts in a thread. It is based in an anchor post at any depth of the tree, and returns posts above it (recursively resolving the parent, without further branching to their replies) and below it (recursive replies, with branching to their replies). Does not require auth, but additional metadata and filtering will be applied for authed requests.

    ## Parameters

    - `above` (boolean, optional): Whether to include parents above the anchor.
    - `anchor` (string, required): Reference (AT-URI) to post record. This is the anchor post, and the thread will be built around it. It can be any post in the tree, not necessarily a root post.
    - `below` (integer, optional): How many levels of replies to include below the anchor.
    - `branchingFactor` (integer, optional): Maximum of replies to include at each level of the thread, except for the direct replies to the anchor, which are (NOTE: currently, during unspecced phase) all returned (NOTE: later they might be paginated).
    - `sort` (string, optional): Sorting for the thread replies.

  """
  @spec get_post_thread_v2(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_post_thread_v2(client, params \\ []) do
    with {:ok, validated} <- validate_get_post_thread_v2(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getPostThreadV2",
        Runtime.encode_query_params(validated, @fields_get_post_thread_v2)
      )
    end
  end

  defp validate_get_post_thread_v2(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_post_thread_v2)

    {f_above, e1} = Runtime.get_boolean(attrs, :above, "above", default: true)

    {f_anchor, e2} =
      Runtime.get_string(attrs, :anchor, "anchor", required: true, format: "at-uri")

    {f_below, e3} =
      Runtime.get_integer(attrs, :below, "below", minimum: 0, maximum: 20, default: 6)

    {f_branching_factor, e4} =
      Runtime.get_integer(attrs, :branching_factor, "branchingFactor",
        minimum: 0,
        maximum: 100,
        default: 10
      )

    {f_sort, e5} = Runtime.get_string(attrs, :sort, "sort", default: "oldest")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5

    if errors == [] do
      {:ok,
       %{
         above: f_above,
         anchor: f_anchor,
         below: f_below,
         branching_factor: f_branching_factor,
         sort: f_sort
       }}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_feeds %{limit: "limit"}

  @doc """
    Get a list of suggested feeds

    ## Parameters

    - `limit` (integer, optional)

  """
  @spec get_suggested_feeds(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_suggested_feeds(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_feeds(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedFeeds",
        Runtime.encode_query_params(validated, @fields_get_suggested_feeds)
      )
    end
  end

  defp validate_get_suggested_feeds(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_feeds)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    errors = e1

    if errors == [] do
      {:ok, %{limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_feeds_skeleton %{limit: "limit", viewer: "viewer"}

  @doc """
    Get a skeleton of suggested feeds. Intended to be called and hydrated by app.bsky.unspecced.getSuggestedFeeds

    ## Parameters

    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_suggested_feeds_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_feeds_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_feeds_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedFeedsSkeleton",
        Runtime.encode_query_params(validated, @fields_get_suggested_feeds_skeleton)
      )
    end
  end

  defp validate_get_suggested_feeds_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_feeds_skeleton)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    {f_viewer, e2} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_onboarding_users %{category: "category", limit: "limit"}

  @doc """
    Get a list of suggested users for onboarding

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)

  """
  @spec get_suggested_onboarding_users(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_onboarding_users(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_onboarding_users(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedOnboardingUsers",
        Runtime.encode_query_params(validated, @fields_get_suggested_onboarding_users)
      )
    end
  end

  defp validate_get_suggested_onboarding_users(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_onboarding_users)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_starter_packs %{limit: "limit"}

  @doc """
    Get a list of suggested starterpacks

    ## Parameters

    - `limit` (integer, optional)

  """
  @spec get_suggested_starter_packs(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_starter_packs(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_starter_packs(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedStarterPacks",
        Runtime.encode_query_params(validated, @fields_get_suggested_starter_packs)
      )
    end
  end

  defp validate_get_suggested_starter_packs(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_starter_packs)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    errors = e1

    if errors == [] do
      {:ok, %{limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_starter_packs_skeleton %{limit: "limit", viewer: "viewer"}

  @doc """
    Get a skeleton of suggested starterpacks. Intended to be called and hydrated by app.bsky.unspecced.getSuggestedStarterpacks

    ## Parameters

    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_suggested_starter_packs_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_starter_packs_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_starter_packs_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedStarterPacksSkeleton",
        Runtime.encode_query_params(validated, @fields_get_suggested_starter_packs_skeleton)
      )
    end
  end

  defp validate_get_suggested_starter_packs_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_starter_packs_skeleton)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    {f_viewer, e2} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users %{category: "category", limit: "limit"}

  @doc """
    Get a list of suggested users

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)

  """
  @spec get_suggested_users(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_suggested_users(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsers",
        Runtime.encode_query_params(validated, @fields_get_suggested_users)
      )
    end
  end

  defp validate_get_suggested_users(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users_for_discover %{limit: "limit"}

  @doc """
    Get a list of suggested users for the Discover page

    ## Parameters

    - `limit` (integer, optional)

  """
  @spec get_suggested_users_for_discover(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_users_for_discover(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users_for_discover(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsersForDiscover",
        Runtime.encode_query_params(validated, @fields_get_suggested_users_for_discover)
      )
    end
  end

  defp validate_get_suggested_users_for_discover(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users_for_discover)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    errors = e1

    if errors == [] do
      {:ok, %{limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users_for_discover_skeleton %{limit: "limit", viewer: "viewer"}

  @doc """
    Get a skeleton of suggested users for the Discover page. Intended to be called and hydrated by app.bsky.unspecced.getSuggestedUsersForDiscover

    ## Parameters

    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_suggested_users_for_discover_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_users_for_discover_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users_for_discover_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsersForDiscoverSkeleton",
        Runtime.encode_query_params(validated, @fields_get_suggested_users_for_discover_skeleton)
      )
    end
  end

  defp validate_get_suggested_users_for_discover_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users_for_discover_skeleton)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    {f_viewer, e2} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users_for_explore %{category: "category", limit: "limit"}

  @doc """
    Get a list of suggested users for the Explore page

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)

  """
  @spec get_suggested_users_for_explore(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_users_for_explore(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users_for_explore(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsersForExplore",
        Runtime.encode_query_params(validated, @fields_get_suggested_users_for_explore)
      )
    end
  end

  defp validate_get_suggested_users_for_explore(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users_for_explore)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users_for_explore_skeleton %{
    category: "category",
    limit: "limit",
    viewer: "viewer"
  }

  @doc """
    Get a skeleton of suggested users for the Explore page. Intended to be called and hydrated by app.bsky.unspecced.getSuggestedUsersForExplore

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_suggested_users_for_explore_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_users_for_explore_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users_for_explore_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsersForExploreSkeleton",
        Runtime.encode_query_params(validated, @fields_get_suggested_users_for_explore_skeleton)
      )
    end
  end

  defp validate_get_suggested_users_for_explore_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users_for_explore_skeleton)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    {f_viewer, e3} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users_for_see_more %{category: "category", limit: "limit"}

  @doc """
    Get a list of suggested users for the See More page

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)

  """
  @spec get_suggested_users_for_see_more(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_users_for_see_more(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users_for_see_more(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsersForSeeMore",
        Runtime.encode_query_params(validated, @fields_get_suggested_users_for_see_more)
      )
    end
  end

  defp validate_get_suggested_users_for_see_more(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users_for_see_more)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users_for_see_more_skeleton %{
    category: "category",
    limit: "limit",
    viewer: "viewer"
  }

  @doc """
    Get a skeleton of suggested users for the See More page. Intended to be called and hydrated by app.bsky.unspecced.getSuggestedUsersForSeeMore

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_suggested_users_for_see_more_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_users_for_see_more_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users_for_see_more_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsersForSeeMoreSkeleton",
        Runtime.encode_query_params(validated, @fields_get_suggested_users_for_see_more_skeleton)
      )
    end
  end

  defp validate_get_suggested_users_for_see_more_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users_for_see_more_skeleton)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    {f_viewer, e3} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggested_users_skeleton %{category: "category", limit: "limit", viewer: "viewer"}

  @doc """
    Get a skeleton of suggested users. Intended to be called and hydrated by app.bsky.unspecced.getSuggestedUsers

    ## Parameters

    - `category` (string, optional): Category of users to get suggestions for.
    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_suggested_users_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def get_suggested_users_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggested_users_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestedUsersSkeleton",
        Runtime.encode_query_params(validated, @fields_get_suggested_users_skeleton)
      )
    end
  end

  defp validate_get_suggested_users_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggested_users_skeleton)

    {f_category, e1} = Runtime.get_string(attrs, :category, "category", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 50, default: 25)

    {f_viewer, e3} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3

    if errors == [] do
      {:ok, %{category: f_category, limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_suggestions_skeleton %{
    cursor: "cursor",
    limit: "limit",
    relative_to_did: "relativeToDid",
    viewer: "viewer"
  }

  @doc """
    Get a skeleton of suggested actors. Intended to be called and then hydrated through app.bsky.actor.getSuggestions

    ## Parameters

    - `cursor` (string, optional)
    - `limit` (integer, optional)
    - `relativeToDid` (string, optional): DID of the account to get suggestions relative to. If not provided, suggestions will be based on the viewer.
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries). Used to boost followed accounts in ranking.

  """
  @spec get_suggestions_skeleton(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_suggestions_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_suggestions_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getSuggestionsSkeleton",
        Runtime.encode_query_params(validated, @fields_get_suggestions_skeleton)
      )
    end
  end

  defp validate_get_suggestions_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_suggestions_skeleton)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 50)

    {f_relative_to_did, e3} =
      Runtime.get_string(attrs, :relative_to_did, "relativeToDid", format: "did")

    {f_viewer, e4} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok,
       %{cursor: f_cursor, limit: f_limit, relative_to_did: f_relative_to_did, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @doc """
    Get a list of suggestions (feeds and users) tagged with categories

    ## Parameters



  """
  @spec get_tagged_suggestions(Client.t()) :: {:ok, map()} | {:error, term()}
  def get_tagged_suggestions(client) do
    client
    |> Client.query("app.bsky.unspecced.getTaggedSuggestions")
  end

  @fields_get_trending_topics %{limit: "limit", viewer: "viewer"}

  @doc """
    Get a list of trending topics

    ## Parameters

    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries). Used to boost followed accounts in ranking.

  """
  @spec get_trending_topics(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_trending_topics(client, params \\ []) do
    with {:ok, validated} <- validate_get_trending_topics(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getTrendingTopics",
        Runtime.encode_query_params(validated, @fields_get_trending_topics)
      )
    end
  end

  defp validate_get_trending_topics(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_trending_topics)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    {f_viewer, e2} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_get_trends %{limit: "limit"}

  @doc """
    Get the current trends on the network

    ## Parameters

    - `limit` (integer, optional)

  """
  @spec get_trends(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_trends(client, params \\ []) do
    with {:ok, validated} <- validate_get_trends(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getTrends",
        Runtime.encode_query_params(validated, @fields_get_trends)
      )
    end
  end

  defp validate_get_trends(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_trends)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    errors = e1

    if errors == [] do
      {:ok, %{limit: f_limit}}
    else
      {:error, errors}
    end
  end

  @fields_get_trends_skeleton %{limit: "limit", viewer: "viewer"}

  @doc """
    Get the skeleton of trends on the network. Intended to be called and then hydrated through app.bsky.unspecced.getTrends

    ## Parameters

    - `limit` (integer, optional)
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec get_trends_skeleton(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_trends_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_get_trends_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.getTrendsSkeleton",
        Runtime.encode_query_params(validated, @fields_get_trends_skeleton)
      )
    end
  end

  defp validate_get_trends_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_trends_skeleton)

    {f_limit, e1} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 25, default: 10)

    {f_viewer, e2} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{limit: f_limit, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @doc """
    Initiate age assurance for an account. This is a one-time action that will start the process of verifying the user's age.
  """
  @spec init_age_assurance(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def init_age_assurance(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.unspecced.initAgeAssurance", body)
  end

  @fields_search_actors_skeleton %{
    cursor: "cursor",
    limit: "limit",
    q: "q",
    typeahead: "typeahead",
    viewer: "viewer"
  }

  @doc """
    Backend Actors (profile) search, returns only skeleton.

    ## Parameters

    - `cursor` (string, optional): Optional pagination mechanism; may not necessarily allow scrolling through entire result set.
    - `limit` (integer, optional)
    - `q` (string, required): Search query string; syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended. For typeahead search, only simple term match is supported, not full syntax.
    - `typeahead` (boolean, optional): If true, acts as fast/simple 'typeahead' query.
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries). Used to boost followed accounts in ranking.

  """
  @spec search_actors_skeleton(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_actors_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_search_actors_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.searchActorsSkeleton",
        Runtime.encode_query_params(validated, @fields_search_actors_skeleton)
      )
    end
  end

  defp validate_search_actors_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_actors_skeleton)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_q, e3} = Runtime.get_string(attrs, :q, "q", required: true)
    {f_typeahead, e4} = Runtime.get_boolean(attrs, :typeahead, "typeahead", [])
    {f_viewer, e5} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, q: f_q, typeahead: f_typeahead, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end

  @fields_search_posts_skeleton %{
    author: "author",
    cursor: "cursor",
    domain: "domain",
    lang: "lang",
    limit: "limit",
    mentions: "mentions",
    q: "q",
    since: "since",
    sort: "sort",
    tag: "tag",
    until: "until",
    url: "url",
    viewer: "viewer"
  }

  @doc """
    Backend Posts search, returns only skeleton

    ## Parameters

    - `author` (string, optional): Filter to posts by the given account. Handles are resolved to DID before query-time.
    - `cursor` (string, optional): Optional pagination mechanism; may not necessarily allow scrolling through entire result set.
    - `domain` (string, optional): Filter to posts with URLs (facet links or embeds) linking to the given domain (hostname). Server may apply hostname normalization.
    - `lang` (string, optional): Filter to posts in the given language. Expected to be based on post language field, though server may override language detection.
    - `limit` (integer, optional)
    - `mentions` (string, optional): Filter to posts which mention the given account. Handles are resolved to DID before query-time. Only matches rich-text facet mentions.
    - `q` (string, required): Search query string; syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
    - `since` (string, optional): Filter results for posts after the indicated datetime (inclusive). Expected to use 'sortAt' timestamp, which may not match 'createdAt'. Can be a datetime, or just an ISO date (YYYY-MM-DD).
    - `sort` (string, optional): Specifies the ranking order of results.
    - `tag` (array, optional): Filter to posts with the given tag (hashtag), based on rich-text facet or tag field. Do not include the hash (#) prefix. Multiple tags can be specified, with 'AND' matching.
    - `until` (string, optional): Filter results for posts before the indicated datetime (not inclusive). Expected to use 'sortAt' timestamp, which may not match 'createdAt'. Can be a datetime, or just an ISO date (YYY-MM-DD).
    - `url` (string, optional): Filter to posts with links (facet links or embeds) pointing to this URL. Server may apply URL normalization or fuzzy matching.
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries). Used for 'from:me' queries.

  """
  @spec search_posts_skeleton(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def search_posts_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_search_posts_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.searchPostsSkeleton",
        Runtime.encode_query_params(validated, @fields_search_posts_skeleton)
      )
    end
  end

  defp validate_search_posts_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_posts_skeleton)

    {f_author, e1} = Runtime.get_string(attrs, :author, "author", format: "at-identifier")
    {f_cursor, e2} = Runtime.get_string(attrs, :cursor, "cursor", [])
    {f_domain, e3} = Runtime.get_string(attrs, :domain, "domain", [])
    {f_lang, e4} = Runtime.get_string(attrs, :lang, "lang", format: "language")

    {f_limit, e5} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_mentions, e6} = Runtime.get_string(attrs, :mentions, "mentions", format: "at-identifier")
    {f_q, e7} = Runtime.get_string(attrs, :q, "q", required: true)
    {f_since, e8} = Runtime.get_string(attrs, :since, "since", [])
    {f_sort, e9} = Runtime.get_string(attrs, :sort, "sort", default: "latest")

    {f_tag, e10} =
      Runtime.get_array(attrs, :tag, "tag", [], fn v, path ->
        Runtime.item_string(v, path, max_length: 640, max_graphemes: 64)
      end)

    {f_until, e11} = Runtime.get_string(attrs, :until, "until", [])
    {f_url, e12} = Runtime.get_string(attrs, :url, "url", format: "uri")
    {f_viewer, e13} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3 ++ e4 ++ e5 ++ e6 ++ e7 ++ e8 ++ e9 ++ e10 ++ e11 ++ e12 ++ e13

    if errors == [] do
      {:ok,
       %{
         author: f_author,
         cursor: f_cursor,
         domain: f_domain,
         lang: f_lang,
         limit: f_limit,
         mentions: f_mentions,
         q: f_q,
         since: f_since,
         sort: f_sort,
         tag: f_tag,
         until: f_until,
         url: f_url,
         viewer: f_viewer
       }}
    else
      {:error, errors}
    end
  end

  @fields_search_starter_packs_skeleton %{
    cursor: "cursor",
    limit: "limit",
    q: "q",
    viewer: "viewer"
  }

  @doc """
    Backend Starter Pack search, returns only skeleton.

    ## Parameters

    - `cursor` (string, optional): Optional pagination mechanism; may not necessarily allow scrolling through entire result set.
    - `limit` (integer, optional)
    - `q` (string, required): Search query string; syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
    - `viewer` (string, optional): DID of the account making the request (not included for public/unauthenticated queries).

  """
  @spec search_starter_packs_skeleton(Client.t(), map() | keyword()) ::
          {:ok, map()} | {:error, term()}
  def search_starter_packs_skeleton(client, params \\ []) do
    with {:ok, validated} <- validate_search_starter_packs_skeleton(params) do
      client
      |> Client.query(
        "app.bsky.unspecced.searchStarterPacksSkeleton",
        Runtime.encode_query_params(validated, @fields_search_starter_packs_skeleton)
      )
    end
  end

  defp validate_search_starter_packs_skeleton(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_search_starter_packs_skeleton)

    {f_cursor, e1} = Runtime.get_string(attrs, :cursor, "cursor", [])

    {f_limit, e2} =
      Runtime.get_integer(attrs, :limit, "limit", minimum: 1, maximum: 100, default: 25)

    {f_q, e3} = Runtime.get_string(attrs, :q, "q", required: true)
    {f_viewer, e4} = Runtime.get_string(attrs, :viewer, "viewer", format: "did")

    errors = e1 ++ e2 ++ e3 ++ e4

    if errors == [] do
      {:ok, %{cursor: f_cursor, limit: f_limit, q: f_q, viewer: f_viewer}}
    else
      {:error, errors}
    end
  end
end