# Generated by `mix exosphere.gen.bsky` — DO NOT EDIT.
# Regenerate with: mix exosphere.gen.bsky

defmodule Exosphere.Bsky.Video do
  @moduledoc """
  XRPC client functions for the `app.bsky.video` namespace.

  Generated from vendored lexicons — DO NOT EDIT.

  ## Endpoints

  - `abort_upload` — procedure: app.bsky.video.abortUpload
  - `finish_upload` — procedure: app.bsky.video.finishUpload
  - `get_job_status` — query: app.bsky.video.getJobStatus
  - `get_upload_limits` — query: app.bsky.video.getUploadLimits
  - `get_upload_status` — query: app.bsky.video.getUploadStatus
  - `start_upload` — procedure: app.bsky.video.startUpload
  - `upload_part` — procedure: app.bsky.video.uploadPart
  - `upload_video` — procedure: app.bsky.video.uploadVideo
  """

  alias Exosphere.ATProto.XRPC.Client

  alias Exosphere.Bsky.Runtime

  @doc """
    Abort an upload only while it is created, releasing its quota reservation immediately. Terminal sessions are unchanged and return their terminal outcome. A finishing session returns UploadNotReady.
  """
  @spec abort_upload(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def abort_upload(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.video.abortUpload", body)
  end

  @doc """
    Finish an upload. This call is idempotent and safe to retry. On deduplication completedJobId may differ from the input jobId; poll getJobStatus with completedJobId. Probe-based validation failures surface later as JOB_STATE_FAILED from getJobStatus, not as errors from this call.
  """
  @spec finish_upload(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def finish_upload(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.video.finishUpload", body)
  end

  @fields_get_job_status %{job_id: "jobId"}

  @doc """
    Get status details for a video processing job.

    ## Parameters

    - `jobId` (string, required)

  """
  @spec get_job_status(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_job_status(client, params \\ []) do
    with {:ok, validated} <- validate_get_job_status(params) do
      client
      |> Client.query(
        "app.bsky.video.getJobStatus",
        Runtime.encode_query_params(validated, @fields_get_job_status)
      )
    end
  end

  defp validate_get_job_status(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_job_status)

    {f_job_id, e1} = Runtime.get_string(attrs, :job_id, "jobId", required: true)

    errors = e1

    if errors == [] do
      {:ok, %{job_id: f_job_id}}
    else
      {:error, errors}
    end
  end

  @doc """
    Get video upload limits for the authenticated user.
  """
  @spec get_upload_limits(Client.t()) :: {:ok, map()} | {:error, term()}
  def get_upload_limits(client) do
    client
    |> Client.query("app.bsky.video.getUploadLimits")
  end

  @fields_get_upload_status %{job_id: "jobId"}

  @doc """
    Get the authoritative status of the upload phase. Terminal states remain readable. completedJobId and jobStatus are present only for completed sessions; failureReason is present only for failed sessions.

    ## Parameters

    - `jobId` (string, required)

  """
  @spec get_upload_status(Client.t(), map() | keyword()) :: {:ok, map()} | {:error, term()}
  def get_upload_status(client, params \\ []) do
    with {:ok, validated} <- validate_get_upload_status(params) do
      client
      |> Client.query(
        "app.bsky.video.getUploadStatus",
        Runtime.encode_query_params(validated, @fields_get_upload_status)
      )
    end
  end

  defp validate_get_upload_status(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_get_upload_status)

    {f_job_id, e1} =
      Runtime.get_string(attrs, :job_id, "jobId", required: true, min_length: 1, max_length: 256)

    errors = e1

    if errors == [] do
      {:ok, %{job_id: f_job_id}}
    else
      {:error, errors}
    end
  end

  @doc """
    Start a multipart video upload. The declared size is exact, while optional media properties are advisory and used only for early failure; the authoritative probe runs asynchronously after upload.
  """
  @spec start_upload(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def start_upload(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.video.startUpload", body)
  end

  @fields_upload_part %{job_id: "jobId", part_number: "partNumber"}

  @doc """
    Upload one part. Parts are idempotent and may be retried or re-sent while the session is created. Each expected length is derived from the upload size and part size, and Content-Length must match exactly. ETags are never exposed to clients.

    ## Parameters

    - `jobId` (string, required)
    - `partNumber` (integer, required)

  """
  @spec upload_part(Client.t(), map() | keyword(), map()) :: {:ok, map()} | {:error, term()}
  def upload_part(client, params \\ [], body \\ %{}) do
    with {:ok, validated} <- validate_upload_part(params) do
      client
      |> Client.procedure(
        "app.bsky.video.uploadPart",
        body,
        Runtime.encode_query_params(validated, @fields_upload_part)
      )
    end
  end

  defp validate_upload_part(params) do
    {attrs, _extra} = Runtime.atomize(params, @fields_upload_part)

    {f_job_id, e1} =
      Runtime.get_string(attrs, :job_id, "jobId", required: true, min_length: 1, max_length: 256)

    {f_part_number, e2} =
      Runtime.get_integer(attrs, :part_number, "partNumber", required: true, minimum: 1)

    errors = e1 ++ e2

    if errors == [] do
      {:ok, %{job_id: f_job_id, part_number: f_part_number}}
    else
      {:error, errors}
    end
  end

  @doc """
    Upload a video to be processed then stored on the PDS.
  """
  @spec upload_video(Client.t(), map()) :: {:ok, map()} | {:error, term()}
  def upload_video(client, body \\ %{}) do
    client
    |> Client.procedure("app.bsky.video.uploadVideo", body)
  end
end