name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hex_publish:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.19"
          otp-version: "27"
          version-type: loose
          hex-cache: true
          rebar-cache: true
          mix-cache: true

      - name: Install deps
        run: mix deps.get

      - name: Publish package
        run: mix hex.publish --yes

      - name: Build docs (ExDoc)
        run: mix docs

      - name: Publish docs
        run: mix hex.publish docs --yes


